### ISSUE TITLE
Swap fails on Windows when upgrading to v2.4.1

### ISSUE THREAD

**Issue by shoreypu** [NagiosEnterprises/ncpa#1000]
Upgraded from 2.40 to 2.4.1, and swap checks are failing (all of our other NCPA checks work).  The agent is reporting the following errors.
{ "swap":
{ "total": "Error retrieving child: 'PdhAddEnglishCounterW failed. Performance counters may be disabled.'",
"free": "Error retrieving child: 'PdhAddEnglishCounterW failed. Performance counters may be disabled.'",
"percent": "Error retrieving child: 'PdhAddEnglishCounterW failed. Performance counters may be disabled.'",
"used": "Error retrieving child: 'PdhAddEnglishCounterW failed. Performance counters may be disabled.'" } }

The check works fine if we remove 2.4.1 and reinstall 2.4.0.

We are currently testing on Windows Server 2019.

**Comment by sawolf** [comment]
The [forum thread](https://support.nagios.com/forum/viewtopic.php?p=345788) for this issue included this log, figured it would be useful over here:
```

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
  File "C:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
  File "C:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
  File "C:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
  File "C:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
  File "C:\Users\Administrator\Documents\repos\ncpa\agent\listener\server.py", line 310, in token_auth_decoration
  File "C:\Users\Administrator\Documents\repos\ncpa\agent\listener\server.py", line 1121, in api
  File "C:\Users\Administrator\Documents\repos\ncpa\agent\listener\nodes.py", line 99, in run_check
  File "C:\Users\Administrator\Documents\repos\ncpa\agent\listener\nodes.py", line 284, in get_values
  File "C:\Users\Administrator\Documents\repos\ncpa\agent\listener\psapi.py", line 158, in <lambda>
  File "C:\Python27\lib\site-packages\psutil\__init__.py", line 1987, in swap_memory
  File "C:\Python27\lib\site-packages\psutil\_pswindows.py", line 257, in swap_memory
RuntimeError: PdhAddEnglishCounterW failed. Performance counters may be disabled.
```

**Comment by shoreypu** [comment]
We were able to resolve the problem by running c:\windows\system32\lodctr /R, as well as, adding Disable Performance Counters value, set it to 0 to HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\PerfProc\Performance.

Not sure if just running lodctr /R followed by a reboot would fix this as well.

**Comment by ne-bbahn** [comment]
I haven't been able to reproduce this particular issue, but I have found that silent installs on Windows aren't logging, so there is definitely something going wrong there.
