### ISSUE TITLE
Ubuntu 22.04 NCPA 3.0 not starting

### ISSUE THREAD

**Issue by Kwiatjk** [NagiosEnterprises/ncpa#1027]
cat ncpa_listener.log
2023-11-16 20:42:14,215 root INFO main - Python version: 3.11.6 (main, Oct 22 2023, 20:33:16) [GCC 10.2.1 20210130 (Red Hat 10.2.1-11)]
2023-11-16 20:42:14,215 root INFO main - SSL version: OpenSSL 3.0.8 7 Feb 2023
2023-11-16 20:42:14,215 root INFO main - ZLIB version: 1.3
2023-11-16 20:42:14,216 parent INFO Daemon - start() - Initialize and run the daemon
2023-11-16 20:42:14,413 listener INFO run()
2023-11-16 20:42:14,417 listener ERROR exception: [Errno 97] Address family not supported by protocol
Traceback (most recent call last):
  File "ncpa.py", line 280, in run
  File "gevent/baseserver.py", line 398, in serve_forever
  File "gevent/baseserver.py", line 336, in start
  File "gevent/pywsgi.py", line 1668, in init_socket
  File "gevent/server.py", line 173, in init_socket
  File "gevent/server.py", line 185, in get_listener
  File "gevent/server.py", line 260, in _tcp_listener
  File "gevent/_socket3.py", line 125, in __init__
OSError: [Errno 97] Address family not supported by protocol

**Comment by ne-bbahn** [comment]
Hello Kwiatjk,

Can you let us know a little more about your configuration? Could you let me know which address family you have configured for your server? Are you using IPv4 (e.g., '192.168.1.1') or IPv6 (e.g., '2001:0db8:85a3:0000:0000:8a2e:0370:7334') addresses?

Are you working in a specific environment like a local development setup, a virtual machine, a containerized environment like Docker, or a cloud platform? Each of these environments can have unique network configurations and limitations.

**Comment by Kwiatjk** [comment]
Hi,
I'm usin ipv4
Is server on virtual machine.

I have a lot another ubunt and working fine only on 2 servers i have
problem

**Comment by mothbitten** [comment]
I have this issue as well. It's RHEL 8.8 on an IPv4 only system. Physical workstation. To make it work I added ip = 0.0.0.0 to the ncpa.cfg file, but was working fine without that with ncpa 2.

**Comment by Kwiatjk** [comment]
> I added ip = 0.0.0.0 to the ncpa.cfg file,
not working for me

**Comment by ne-bbahn** [comment]
@Kwiatjk 
What do you have set in your `[listener]` section of your `ncpa.cfg`?
The ip and port set in the listener section of the configuration is where NCPA sets the gevent's WSGIServer address and are likely where your issues are initializing from. If not set in the configuration file, the address will default to `::` unless you're on Windows in which case it would be `0.0.0.0` and the port will set to `5693`. 

>> I added ip = 0.0.0.0 to the ncpa.cfg file,

> not working for me

Did you add it under the `[listener]` section where there is an `ip =` and `port =` commented out?

**Comment by mothbitten** [comment]
My listener section looks like this:

[listener]
uid = nagios
gid = nagios
ip =  0.0.0.0
ssl_version = TLSv1_2
certificate = adhoc
loglevel = info
logfile = var/log/ncpa_listener.log
pidfile = var/run/ncpa_listener.pid
admin_gui_access = 1
admin_password = None
admin_auth_only = 0
allowed_hosts = <redacted>

**Comment by ne-bbahn** [comment]
Someone found the issue. It seems that when ipv6 is disabled, NCPA won't start. I will try to get this solved for 3.0.1

**Comment by ne-bbahn** [comment]
Fix will be in 3.0.1
