### ISSUE TITLE
Issue with Executing Ruby on Rails Plugins in NCPA Version 3.0.0

### ISSUE THREAD

**Issue by Meloknight89** [NagiosEnterprises/ncpa#1083]
**Description**

Following the upgrade to NCPA Version 3.0.0, we are experiencing issues executing Gitlab Plugins written in Ruby on Rails. While these checks run successfully when executed locally, they fail when conducted over the NCPA client, resulting in a series of errors.

**Environment**

NCPA Version: 3.0.0
Operating System: Red Hat 8

**Steps to Reproduce**

1. Upgrade to NCPA Version 3.0.0.
2. Attempt to execute a Gitlab Plugin written in Ruby on Rails via the NCPA client. -> https://gitlab.com/6uellerBpanda/check_gitlab
3. Observe that the check fails.

**Expected Behavior**

The Gitlab Plugin checks should execute successfully over the NCPA client, as they do when run locally.

**Actual Behavior**

```
Dec 19 16:15:51 gitsrv ncpa[1399]: 2023-12-19 16:15:51,829 listener.server ERROR Exception on /api/plugins/check_gitlab.rb/ [GET]
Dec 19 16:15:51 gitsrv ncpa[1399]: Traceback (most recent call last):
Dec 19 16:15:51 gitsrv ncpa[1399]:  File "listener/nodes.py", line 346, in run_check
Dec 19 16:15:51 gitsrv ncpa[1399]:  File "listener/nodes.py", line 310, in get_values
Dec 19 16:15:51 gitsrv ncpa[1399]: AttributeError: 'PluginNode' object has no attribute 'method'
Dec 19 16:15:51 gitsrv ncpa[1399]: During handling of the above exception, another exception occurred:
Dec 19 16:15:51 gitsrv ncpa[1399]: Traceback (most recent call last):
Dec 19 16:15:51 gitsrv ncpa[1399]:  File "configparser.py", line 805, in get
Dec 19 16:15:51 gitsrv ncpa[1399]:  File "collections/__init__.py", line 1004, in __getitem__
Dec 19 16:15:51 gitsrv ncpa[1399]:  File "collections/__init__.py", line 996, in __missing__
Dec 19 16:15:51 gitsrv ncpa[1399]: KeyError: '.rb'
Dec 19 16:15:51 gitsrv ncpa[1399]: During handling of the above exception, another exception occurred:
Dec 19 16:15:51 gitsrv ncpa[1399]: Traceback (most recent call last):
Dec 19 16:15:51 gitsrv ncpa[1399]:  File "listener/pluginnodes.py", line 68, in get_plugin_instructions
Dec 19 16:15:51 gitsrv ncpa[1399]:  File "configparser.py", line 808, in get
Dec 19 16:15:51 gitsrv ncpa[1399]: configparser.NoOptionError: No option '.rb' in section: 'plugin directives'
Dec 19 16:15:51 gitsrv ncpa[1399]: During handling of the above exception, another exception occurred:
Dec 19 16:15:51 gitsrv ncpa[1399]: Traceback (most recent call last):
Dec 19 16:15:51 gitsrv ncpa[1399]:  File "flask/app.py", line 1455, in wsgi_app
Dec 19 16:15:51 gitsrv ncpa[1399]:  File "flask/app.py", line 869, in full_dispatch_request
Dec 19 16:15:51 gitsrv ncpa[1399]:  File "flask/app.py", line 867, in full_dispatch_request
Dec 19 16:15:51 gitsrv ncpa[1399]:  File "flask/app.py", line 852, in dispatch_request
Dec 19 16:15:51 gitsrv ncpa[1399]:  File "listener/server.py", line 305, in token_auth_decoration
Dec 19 16:15:51 gitsrv ncpa[1399]:  File "listener/server.py", line 1111, in api
Dec 19 16:15:51 gitsrv ncpa[1399]:  File "listener/nodes.py", line 348, in run_check
Dec 19 16:15:51 gitsrv ncpa[1399]:  File "listener/pluginnodes.py", line 87, in execute_plugin
Dec 19 16:15:51 gitsrv ncpa[1399]:  File "listener/pluginnodes.py", line 69, in get_plugin_instructions
Dec 19 16:15:51 gitsrv ncpa[1399]: AttributeError: type object 'ConfigParser' has no attribute 'NoOptionError'
``` 

**Possible Causes**

From the logs, it seems there are multiple nested exceptions involving listener/nodes.py, configparser.py, and listener/pluginnodes.py. Key errors include AttributeError: 'PluginNode' object has no attribute 'method' and configparser.NoOptionError: No option '.rb' in section: 'plugin directives'.

**Comment by ne-bbahn** [comment]
fix will be included in next release.

**Comment by Meloknight89** [comment]
Thanks for pointing out the workaround and that a fix will be considered for the next release.

**Comment by ne-bbahn** [comment]
Do note that even after the fix, if your PATH doesn't have a way to recognize .rb files, you will still need to add the directive in the configuration since if NCPA doesn't have a directive for a plugin's extension, it will simply attempt to run the plugin file directly in a terminal
