### ISSUE TITLE
Windows NCPA 3.01 Not able to use plugins, AttributeError: 'PluginNode' object has no attribute 'method'

### ISSUE THREAD

**Issue by yderi** [NagiosEnterprises/ncpa#1090]
Have a next issue with a new NCPA 3.0.1 agent on Windows Server 2016 machine:
Even if you try to run plugin manually thru the NCPA web UI
there is a few plugins (ps1 and exe file type), and all have troubles to run, UI simply hang.
In agent logs can see the following:

```
2023-12-21 17:24:43,425 listener.server ERROR Exception on /api/plugins/check_tcp.exe/ [GET]
Traceback (most recent call last):
  File "listener\nodes.py", line 346, in run_check
  File "listener\nodes.py", line 310, in get_values
AttributeError: 'PluginNode' object has no attribute 'method'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "configparser.py", line 805, in get
  File "collections\__init__.py", line 1006, in __getitem__
  File "collections\__init__.py", line 998, in __missing__
KeyError: '.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "listener\pluginnodes.py", line 68, in get_plugin_instructions
  File "configparser.py", line 808, in get
configparser.NoOptionError: No option '.exe' in section: 'plugin directives'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "flask\app.py", line 1455, in wsgi_app
  File "flask\app.py", line 869, in full_dispatch_request
  File "flask\app.py", line 867, in full_dispatch_request
  File "flask\app.py", line 852, in dispatch_request
  File "listener\server.py", line 305, in token_auth_decoration
  File "listener\server.py", line 1111, in api
  File "listener\nodes.py", line 348, in run_check
  File "listener\pluginnodes.py", line 87, in execute_plugin
  File "listener\pluginnodes.py", line 69, in get_plugin_instructions
AttributeError: type object 'ConfigParser' has no attribute 'NoOptionError'
2023-12-21 17:24:51,894 listener.server ERROR Exception on /api/plugins/check_tcp.exe/ [GET]
Traceback (most recent call last):
  File "listener\nodes.py", line 346, in run_check
  File "listener\nodes.py", line 310, in get_values
AttributeError: 'PluginNode' object has no attribute 'method'

During handling of the above exception, another exception occurred:
```
Let me know if anything else should be provided

**Comment by yderi** [comment]
The similar issue with a Linux NCPA 3.0.1 client:
if you try to run the plugin from NCPA Web UI, it shows animation indefinitely.
In the logs, you can see the following:
```
2023-12-26 16:04:32,510 listener.server ERROR Exception on /api/plugins/rabbit_queue_consumer.bash/ [GET]
Traceback (most recent call last):
  File "listener/nodes.py", line 346, in run_check
  File "listener/nodes.py", line 310, in get_values
AttributeError: 'PluginNode' object has no attribute 'method'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "configparser.py", line 805, in get
  File "collections/__init__.py", line 1004, in __getitem__
  File "collections/__init__.py", line 996, in __missing__
KeyError: '.bash'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "listener/pluginnodes.py", line 68, in get_plugin_instructions
  File "configparser.py", line 808, in get
configparser.NoOptionError: No option '.bash' in section: 'plugin directives'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "flask/app.py", line 1455, in wsgi_app
  File "flask/app.py", line 869, in full_dispatch_request
  File "flask/app.py", line 867, in full_dispatch_request
  File "flask/app.py", line 852, in dispatch_request
  File "listener/server.py", line 305, in token_auth_decoration
  File "listener/server.py", line 1111, in api
  File "listener/nodes.py", line 348, in run_check
  File "listener/pluginnodes.py", line 87, in execute_plugin
  File "listener/pluginnodes.py", line 69, in get_plugin_instructions
AttributeError: type object 'ConfigParser' has no attribute 'NoOptionError'

```

**Comment by ne-bbahn** [comment]
This is a known problem and should be fixed in NCPA 3.0.2
