### ISSUE TITLE
v3.0.2 - plugins fail when NFS filesystems are mounted using sec=krb5

### ISSUE THREAD

**Issue by rev138** [NagiosEnterprises/ncpa#1136]
Since updating to 3.0.2 all "plugin" based checks on hosts with mount NFS filesystems using `sec=krb5` fail, even if the plugin does not check the "disks" (possibly related to #911 ?)

```
2024-03-26 09:29:44,533 listener INFO before_request() - request.url: https://xxx.xxx.xxx.xxx:5693/api/plugins/check_load/?token=********&args=-r+-w+10,9,8+-c+18,17,16
2024-03-26 09:29:44,747 listener.server ERROR Exception on /api/plugins/check_load/ [GET]
Traceback (most recent call last):
  File "listener/psapi.py", line 108, in make_mountpoint_nodes
PermissionError: [Errno 13] Permission denied: '/fs/shares'
```

The above shows an error given by the check_load plugin -- `/fs/shares` is an NFS mountpoint mounted using `sec=krb5`. Other hosts checked by NCPA with NFS mounts using `sec=sys` do not seem to be affected.

This issue did not exist in 3.0.1 and the check plugins have not changed. This is new behavior in 3.0.2. For now, we have downgraded.

**Comment by MrPippin66** [comment]
Not that it's directly related, since you say 3.0.1 works on the same system that 3.0.2 is failing, but what's kerberos credential is being used for the NFS mount?

**Comment by fabiuseur** [comment]
I have the same issue on some RHEL servers running on NCPA 3.0.2. Where /data/rvol/home4 our NFS server is mounted for users with a home directory. The users generates a krb5 tickets to our Active Directory services where it grants a kerberos ticket. But the NCPA checks aren't working if this NFS-share is mounted on the Linux server. I am getting the next errors:

`2024-04-15 11:17:06,960 listener INFO before_request() - request.url: https://<linux_servers>:5693/api/disk/logical/|data/?token=********&warning=85&critical=90&check=1
2024-04-15 11:17:06,972 listener.server ERROR Exception on /api/disk/logical/|data/ [GET]
Traceback (most recent call last):
  File "listener/psapi.py", line 108, in make_mountpoint_nodes
PermissionError: [Errno 13] Permission denied: '/data/rvol/home4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "listener/psapi.py", line 417, in get_root_node
  File "listener/psapi.py", line 361, in get_disk_node
  File "listener/psapi.py", line 140, in make_mountpoint_nodes
  File "logging/__init__.py", line 2123, in exception
  File "logging/__init__.py", line 2115, in error
  File "logging/__init__.py", line 1518, in error
  File "logging/__init__.py", line 1634, in _log
  File "logging/__init__.py", line 1644, in handle
  File "logging/__init__.py", line 1706, in callHandlers
  File "logging/__init__.py", line 974, in handle
  File "logging/__init__.py", line 832, in filter
  File "ncpa.py", line 56, in tokenFilter
TypeError: argument of type 'PermissionError' is not iterable
`

When I've unmount the NFS-mount with the kerberos share the NCPA checks works flawless. 


This are the mount options of the NFS-share:
`root@<linux_server>~ # mount | grep -i home  
<nfs_server>:/data/export/home on /data/rvol/home4 type nfs4 (rw,noatime,vers=4.2,rsize=1048576,wsize=1048576,namlen=255,soft,proto=tcp,timeo=600,retrans=2,sec=krb5,clientaddr=<client_ip>,local_lock=none,addr=<addr>)
`

If i do the next NCPA checks from the nagios servers with the nfs-share mounted:

`root@<nagios_server> ~ # /usr/local/nagios/libexec/check_ncpa.py -H <linux_server> -t '<ncpa_token>' -P 5693 -M 'disk/logical/|data' -w 85 -c 90       
UNKNOWN: An error occured connecting to API. (HTTP error: '500 INTERNAL SERVER ERROR')
`
And with the nfs-share unmounted it works:
`root@<nagios_server>~ # /usr/local/nagios/libexec/check_ncpa.py -H <linux_host> -t '<ncpa_token>' -P 5693 -M 'disk/logical/|data' -w 85 -c 90
OK: Used disk space was 31.90 % (Used: 15.95 GiB, Free: 34.02 GiB, Total: 49.97 GiB) | 'used'=15.95GiB;;; 'free'=34.02GiB;;; 'total'=49.97GiB;;;
`
The Linux host is running on RHEL9.3 with NCPA version 3.0.2 (latest version)

How can I solve this issue? 

Kind Regards

Fabiuseur
