### ISSUE TITLE
[Windows] NCPA 3.1.0 to NCPA 3.1.1 - NCPA won't start (Error 1053)

### ISSUE THREAD

**Issue by bramassendorp** [NagiosEnterprises/ncpa#1215]
Event viewer messages:

A timeout was reached (30000 milliseconds) while waiting for the Nagios Cross-Platform Agent service to connect.

The Nagios Cross-Platform Agent service failed to start due to the following error: 
The service did not respond to the start or control request in a timely fashion.

No log files are begin written in C:\Program Files\Nagios\NCPA\var\log, even with loglevel set to debug.

Updated with patchmypc, so I have a whole bunch of server out of monitoring right now.

**Comment by bramassendorp** [comment]
Another error from the eventlog:

Traceback (most recent call last): File "win32serviceutil.py", line 1071, in SvcRun File "win32serviceutil.py", line 1021, in ReportServiceStatus pywintypes.error: (6, 'SetServiceStatus', 'The handle is invalid.') 

On some hosts, I have tried reverting back to 3.1 most hosts successful, but for some the service won't even start anymore on 3.1. When trying to remove NCPA instead of reinstalling, the uninstaller hangs.

Please fix asap as this would affect a lot of hosts at the moment.

**Comment by aaronclegg** [comment]
I am experiencing this as well.  But just on a single host, most of them are completely fine.  Attempting to start the service results in a timeout, uninstall hangs after removing its own exe uninstall.exe
