### ISSUE TITLE
non-ASCII/Unicode character in service name is tripping up the api/services requests

### ISSUE THREAD

**Issue by poseidon042** [NagiosEnterprises/ncpa#1221]
NCPA 3.1.1 on Windows Server 2019
- Using the web GUI and looking at api/services results in three-dots and no service content loading
- In Nagios, the following status is returned for all service running checks for this server: "UNKNOWN: An error occurred connecting to API. (HTTP error: '500 INTERNAL SERVER ERROR')"
- the offending service seems to have a non-ASCII character in both the Service Name and the Display Name
- logs from the ncpa_listener log file are below ("example.com" replaces the real server name)

![image](https://github.com/user-attachments/assets/c822fadc-4d26-480c-86e3-ad5c73e269ed)

> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "flask\app.py", line 1473, in wsgi_app
>   File "flask\app.py", line 882, in full_dispatch_request
>   File "flask\app.py", line 880, in full_dispatch_request
>   File "flask\app.py", line 865, in dispatch_request
>   File "listener\server.py", line 317, in token_auth_decoration
>   File "listener\server.py", line 1507, in api
>   File "listener\services.py", line 354, in run_check
>   File "listener\services.py", line 18, in wrapper
>   File "listener\services.py", line 112, in get_services_via_psutil
>   File "psutil\_pswindows.py", line 628, in status
>   File "psutil\_pswindows.py", line 558, in _query_status
>   File "contextlib.py", line 158, in __exit__
>   File "psutil\_pswindows.py", line 583, in _wrap_exceptions
> psutil.NoSuchProcess: service 'SNAP Live²' does not exist (name='SNAP Live²')
> 2024-10-30 15:26:53,115 listener INFO before_request() - request.url: https://snaps:5693/api/disk/logical/C:|/used_percent/?token=********&warning=80&critical=90&check=1
> 2024-10-30 15:27:11,553 listener INFO before_request() - request.url: https://snaps:5693/api/cpu/count/?token=********&check=1
> 2024-10-30 15:27:32,803 listener INFO before_request() - request.url: https://snaps:5693/api/system/version/?token=********&check=1
> 2024-10-30 15:27:33,897 listener INFO Did not receive normal values. Unable to find meaningful check.
> 2024-10-30 15:27:49,834 listener INFO before_request() - request.url: https://example.com:5693/gui/
> 2024-10-30 15:27:54,084 listener INFO before_request() - request.url: https://example.com:5693/gui/checks
> 2024-10-30 15:27:58,194 listener INFO before_request() - request.url: https://example.com:5693/gui/api
> 2024-10-30 15:27:58,412 listener INFO before_request() - request.url: https://example.com:5693/api
> 2024-10-30 15:28:01,397 listener INFO before_request() - request.url: https://example.com:5693/api/services
> 2024-10-30 15:28:01,491 listener.server ERROR Exception on /api/services [GET]
> Traceback (most recent call last):
>   File "psutil\_pswindows.py", line 570, in _wrap_exceptions
>   File "psutil\_pswindows.py", line 559, in _query_status
> OSError: [WinError 1060] The specified service does not exist as an installed service: '(originated from OpenService)'

**Comment by domme0711** [comment]
I have a similar problem with a windows server running some stupid software with umlauts in its servicename. 
The result of check_ncpa.py requesting the "services" module is:
`UNKNOWN: An error occurred connecting to API. (HTTP error: '500 INTERNAL SERVER ERROR')`

NCPA-Version 3.1.0

**Comment by MrPippin66** [comment]
Out of curiosity, what output do you get for following in PowerShell for an affected system?

$OutputEncoding = [System.Text.Encoding]::UTF8
get-service <service name for the given service>

**Comment by iszl-mt** [comment]
![image](https://github.com/user-attachments/assets/e55a7d20-c45a-477e-8948-b0c2858366ae)
![image](https://github.com/user-attachments/assets/8eb0bb1c-54b7-4e3b-b55b-27d10bb6ede0)

**Comment by MrPippin66** [comment]
I'm thinking this is likely a problem with 'psutil' module.

The code path is straightfoward in NCPA with no UTF string translations occurring.

`        for service in psutil.win_service_iter():
            name = service.name()
            if service.status() == 'running':
                services[name] = 'running'
            else:
                services[name] = 'stopped'`
                
 We essentially get a PSUTIL winservice class, and the error is getting the service status from that object without any variables being changed within NCPA, itself.
 
 `if service.status() == 'running':`
 
 I checked history of psutil, and don't see any known issues on versions of psutil since 3.1.1 deployment of NCPA.

**Comment by poseidon042** [comment]
Thanks ... so how do we move this forwards?
Current situation is that **all** service checks for an affected server fail (non-service checks via NCPA do work OK).

![image](https://github.com/user-attachments/assets/dc766331-756e-4003-90fc-576352a0ca92)

**Comment by ne-bbahn** [comment]
Our version of NCPA agent is 3.1.1. It worked so far with no issues. Recently we have install a new software to the server which created a services which has national character in its name "Č". From that time, any API function regarding service just hangs. In the ncpa_listener.log I can see repeating errros:

`During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "flask\app.py", line 1473, in wsgi_app
File "flask\app.py", line 882, in full_dispatch_request
File "flask\app.py", line 880, in full_dispatch_request
File "flask\app.py", line 865, in dispatch_request
File "listener\server.py", line 317, in token_auth_decoration
File "listener\server.py", line 1507, in api
File "listener\services.py", line 354, in run_check
File "listener\services.py", line 18, in wrapper
File "listener\services.py", line 112, in get_services_via_psutil
File "psutil_pswindows.py", line 628, in status
File "psutil_pswindows.py", line 558, in _query_status
File "contextlib.py", line 158, in exit
File "psutil_pswindows.py", line 583, in _wrap_exceptions
psutil.NoSuchProcess: service 'ČSOB Business Connector' does not exist (name='ČSOB Business Connector')
2025-01-24 13:29:49,843 listener.server ERROR Exception on /api/services [GET]
Traceback (most recent call last):
File "psutil_pswindows.py", line 570, in _wrap_exceptions
File "psutil_pswindows.py", line 559, in _query_status
OSError: [WinError 1060] The specified service does not exist as an installed service: '(originated from OpenService)'`

I believe this is a bug.

Regards
Petr

**Comment by albertbertus** [comment]
Hi,
I have encountered an issue when trying to configure ncpa.cfg to ignore a Windows service that contains an accent in its name. When adding the option ignore_services = Ágora in the [services] section, the NCPA Listener service fails to start and throws an error like:

`psutil.NoSuchProcess: service 'Ágora' does not exist (name='Ágora')
OSError: [WinError 1060] The specified service does not exist as an installed service: '(originated from OpenService)'`

It seems that NCPA does not handle special characters properly in service names. I tried saving ncpa.cfg in different encodings (UTF-8 without BOM, ANSI), but the issue persists.

Is there a way to ignore Windows services with accented characters in ncpa.cfg?
Any suggestions or workarounds to avoid this error would be greatly appreciated.

Thanks!

**Comment by ne-bbahn** [comment]
@albertbertus, We are aware of this issue and will try to fix it as soon as possible. Unfortunately, we have been given other priorities for the near-term and are unable to work on it at the moment. If you can convince the PSUtil team to fix this bug, we can update the version we are using to include the fix earlier. Otherwise it'll be a while before we can get a workaround merged in.

**Comment by albertbertus** [comment]
Hi @ne-bbahn,
Thanks for the response. I understand there are other priorities at the moment. I'll try to contact the PSUtil team to see if they can address this issue.

**Comment by MrPippin66** [comment]
@ne-bbahn, which version of psutils was used for the 3.1.1 build of NCPA?

**Comment by ne-bbahn** [comment]
> [@ne-bbahn](https://github.com/ne-bbahn), which version of psutils was used for the 3.1.1 build of NCPA? I assume 6.0.0, but can't validate.
> 
> I opened psutil issue. I THINK I may have identified the issue and stated it there.
> 
> [giampaolo/psutil#2506](https://github.com/giampaolo/psutil/issues/2506)

Based on the files in lib/library.zip, the version included is 6.1.1. Since a version is not specified, the build just pulls in whatever the default version is. This may have been updated since the Nagios NCPA build artifacts were last created as using pip install --upgrade psutil is now giving me 7.0.0.

**Comment by ne-bbahn** [comment]
@MrPippin66, it will be both in the startup banner in the log and in the web UI's dashboard page

**Comment by ne-bbahn** [comment]
Since PSUtil has been upgraded, this should be fixed. If anyone disagrees, please re-open this issue.

**Comment by poseidon042** [comment]
Thanks for the work & updates ... (BTW I don't have permissions to re-open the issue)

Please help me understand whether this is still a NCPA issue or not, or something else ... 

On the relevant Windows server (WIndows Server 2022 Datacenter, 21H2) I upgraded NCPA to 3.1.4.
When querying the services part of the API, it is unchanged .. page never completes loading.

<img width="706" height="604" alt="Image" src="https://github.com/user-attachments/assets/f2c12d81-1a7d-408b-ac99-9e78020048a1" />
<img width="1688" height="818" alt="Image" src="https://github.com/user-attachments/assets/c8151a07-0131-446e-811b-7ea1c8a37dcd" />

[ncpa_listener.log](https://github.com/user-attachments/files/21749467/ncpa_listener.log)

**Comment by ne-bbahn** [comment]
@poseidon042 Can you show me a picture of the Dashboard page? I'd like to see if psutil was properly upgraded.

**Comment by poseidon042** [comment]
<img width="2006" height="1168" alt="Image" src="https://github.com/user-attachments/assets/3b7f68ec-29a6-4bf3-8d35-0dd3f0b3809c" />

**Comment by ne-bbahn** [comment]
Looks like updating psutil didn't actually solve the problem. I'll investigate and try to get a fix out before too long.

**Comment by MrPippin66** [comment]
@ne-bbahn  I'd opened a psutils issue on this a few months ago. There hasn't been an update, so I directly asked the project owner and it was updated yesterday.

https://github.com/giampaolo/psutil/issues/2506

> I did not investigate it, no. The inverse of PyUnicode_FromWideChar should be PyUnicode_AsWideChar. I don't have time and a Windows virtualized box at the moment, so I can't give it a try, but if you want/can feel free to do it. The gist should be feeding psutil_get_service_handler a PyUnicode_AsWideChar object.

**Comment by MrPippin66** [comment]
@ne-bbahn I don't have the ability to test this, but the psutil maintainer did put in a fix for this

https://github.com/giampaolo/psutil/pull/2626

**Comment by poseidon042** [comment]
Forgive my ignorance ... am I able to make use of this? (if so, how?)
Or does it require a new NCPA release first?
