### ISSUE TITLE
Issue with installing NCPA 1.7.2 on CentOS 7

### ISSUE THREAD

**Issue by kmf** [NagiosEnterprises/ncpa#140]
After install the RPM the out looks like this 
Installed size: 15 M
Is this ok [y/d/N]: y
Downloading packages:
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
uid=1001(nagios) gid=1001(nagcmd) groups=1001(nagcmd)
  Installing : ncpa-1.7.2-1.el7.centos.x86_64                                                                                                                                             1/1 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/cx_Freeze-4.3.2-py2.7-linux-x86_64.egg/cx_Freeze/initscripts/Console.py", line 27, in <module>
  File "ncpa_posix_listener.py", line 6, in <module>
  File "/root/Development/ncpa/agent/listener/server.py", line 15, in <module>
  File "/usr/local/lib/python2.7/site-packages/gevent/__init__.py", line 36, in <module>
  File "/usr/local/lib/python2.7/site-packages/gevent/hub.py", line 8, in <module>
ImportError: /usr/local/ncpa/greenlet.so: file too short
Started listener...
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/cx_Freeze-4.3.2-py2.7-linux-x86_64.egg/cx_Freeze/initscripts/Console.py", line 27, in <module>
  File "ncpa_posix_passive.py", line 7, in <module>
  File "/root/Development/ncpa/agent/passive/nrds.py", line 4, in <module>
  File "/root/Development/ncpa/agent/passive/nagioshandler.py", line 3, in <module>
  File "/root/Development/ncpa/agent/passive/ncpacheck.py", line 5, in <module>
  File "/root/Development/ncpa/agent/listener/server.py", line 15, in <module>
  File "/usr/local/lib/python2.7/site-packages/gevent/__init__.py", line 36, in <module>
  File "/usr/local/lib/python2.7/site-packages/gevent/hub.py", line 8, in <module>
ImportError: /usr/local/ncpa/greenlet.so: file too short
Started passive agent...
  Verifying  : ncpa-1.7.2-1.el7.centos.x86_64                                                                                                                                             1/1 

Installed:
  ncpa.x86_64 0:1.7.2-1.el7.centos                                                                                                                                                            

Complete!

**Comment by varnar** [comment]
This issue is already fixed for version 1.8 https://github.com/NagiosEnterprises/ncpa/issues/90

**Comment by kmf** [comment]
Is there any official builds for version 1.8.0?

**Comment by scot0357** [comment]
Not yet, it is currently going through testing.

**Comment by kmf** [comment]
Is there a way to assist with testing?

**Comment by jhomann** [comment]
Confirming this is fixed on 1.8.0 for cent 7.
