### ISSUE TITLE
Troubles with uptime part in api

### ISSUE THREAD

**Issue by ravenich** [NagiosEnterprises/ncpa#166]
Hi, i have troubles with uptime string in api: 
https://localhost:5693/api/system?token=mytoken
"uptime": "Error retrieving child: 'Invalid format string'"
log:ncpa_listener:
2015-04-08 10:11:24,276:INFO:handler:127.0.0.1 - - [2015-04-08 10:11:24] "GET /api HTTP/1.1" 301 432 0.005000
2015-04-08 10:11:24,292:ERROR:__init__:Invalid format string
Traceback (most recent call last):
  File "C:\ncpa\agent\listener\nodes.py", line 42, in walk
  File "C:\ncpa\agent\listener\nodes.py", line 103, in walk
  File "C:\ncpa\agent\listener\psapi.py", line 21, in get_uptime
ValueError: Invalid format string

NCPA installed in C:\Program Files (x86)\Nagios\NCPA
Same error at the different servers. NCPA: 1.8.0. OS: Windows Server 2008 SP2, 2008R2 SP1, 2012R2.

**Comment by jhomann** [comment]
Hello, this has been fixed in 1.8.1 (the master branch) and will be out shortly.
