### ISSUE TITLE
passive check rename still submitting

### ISSUE THREAD

**Issue by daVikes** [NagiosEnterprises/ncpa#199]
I had a passive check in ncpa.cfg that was: 

%HOSTNAME%|root free = /disk/logical/|/used_percent --warning 90 --critical 95

but I changed the name of it to:

%HOSTNAME%|disk_root_used = /disk/logical/|/used_percent --warning 90 --critical 95

Saved/Restarted the ncpa_passive service. However, the root free passive check keeps showing up in unconfigured objects?? Was there something else I need to do ?

**Comment by jhomann** [comment]
You'll have to remove it via the delete button from un-configured objects for it to actually be removed. Did you remove it and it showed up again?

**Comment by daVikes** [comment]
Yes, it showed up again after removing it from un-configured objects with a new date/time stamp.

**Comment by daVikes** [comment]
Today this seems ok?   Not sure why it was still showing the object last couple of days.      However, when no passive checks are enabled I am getting this error now:


2015-10-15 09:07:33,381 32750 ERROR syntax error: line 1, column 0
Traceback (most recent call last):
  File "ncpa_posix_passive.py", line 41, in run_all_handlers
  File "/root/Development/ncpa/agent/passive/nrdp.py", line 112, in run
  File "/root/Development/ncpa/agent/passive/nrdp.py", line 166, in submit_to_nagios
  File "/root/Development/ncpa/agent/passive/nrdp.py", line 132, in log_result
  File "/usr/local/lib/python2.7/xml/dom/minidom.py", line 1928, in parseString
  File "/usr/local/lib/python2.7/xml/dom/expatbuilder.py", line 940, in parseString
  File "/usr/local/lib/python2.7/xml/dom/expatbuilder.py", line 223, in parseString
ExpatError: syntax error: line 1, column 0

**Comment by jhomann** [comment]
Well it looks like the error is because of the returned result not actually containing the "checkresults" data it is expecting. This can definitely be fixed in the next version.

**Comment by jhomann** [comment]
There are two different issues here:

1. The error when there are no passive checks, which will be fixed.

2. The old check appearing in the un-configured objects section. From what I can tell it looks like clicking the "clear" button it removes the check but if you just delete them all it will come back the next time the checks come in. This may have something to do with NRDP or the un-configured objects page if there is some sort of caching I'm not sure.

**Comment by jhomann** [comment]
Fixed in d60df662906a38c665a5f464bcecec6c5cb01ab5
