### ISSUE TITLE
centos7 services missing

### ISSUE THREAD

**Issue by phenely** [NagiosEnterprises/ncpa#216]
When trying to get ncpa working with centos 7 I'm getting the following error with the services API call.

`2016-02-27 11:25:57,431 2019 ERROR Exception on /api/services [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1504, in wsgi_app
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1264, in full_dispatch_request
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1262, in full_dispatch_request
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1248, in dispatch_request
  File "/root/Development/ncpa/agent/listener/server.py", line 68, in decorated
  File "/root/Development/ncpa/agent/listener/server.py", line 401, in api
  File "/root/Development/ncpa/agent/listener/services.py", line 172, in walk
  File "/root/Development/ncpa/agent/listener/services.py", line 11, in wrapper
  File "/root/Development/ncpa/agent/listener/services.py", line 117, in get_services_via_systemctl
ValueError: too many values to unpack
`
In poking around with the source code it would appear that on line 117 of the services.py the split should be 4 not 5.

`for line in status.readlines():
     print line.split(None,4)
`
['wpa_supplicant.service', 'loaded', 'active', 'running', 'WPA Supplicant daemon\n']

`for line in status.readlines():
     print line.split(None,5)
`
['wpa_supplicant.service', 'loaded', 'active', 'running', 'WPA', 'Supplicant daemon\n']

Is anyone else seeing similar problems or is this just me?

**Comment by phenely** [comment]
seems to be standard across all the systemd systems I've checked (centos 7, fedora 21, debian 8)

**Comment by lgroschen** [comment]
This is great info!  Thanks for posting.

**Comment by jhomann** [comment]
I've fixed this in 1.8.2 (if there is one) otherwise it will be in 2.0.0!

**Comment by guglez** [comment]
@jomann09 when can we expect 1.8.2 or 2.0.0? I'm facing the same issue.

**Comment by jomann09** [comment]
This will be fixed in 2.0.0 - there has been a couple more updates to services in general that should make them much more reliable.
