### ISSUE TITLE
check_ncpa.py throws error: An error occurred:No JSON object could be decoded

### ISSUE THREAD

**Issue by ccztux** [NagiosEnterprises/ncpa#227]
I have tested the new version of the check_ncpa.py plugin and the bug: #219 seems to be fixed.

Here is what i have noticed.

When executing check_ncpa.py with flag -v it throws this error:
```
An error occurred:No JSON object could be decoded
```

When executing check_ncpa.py with flags -v -D it throws this error:
```
An error occurred:No JSON object could be decoded
```

and this exception:
```
The stack trace:Traceback (most recent call last):
  File "./check_ncpa.py", line 277, in main
    info_json = get_json(options)
  File "./check_ncpa.py", line 233, in get_json
    arr = json.load(ret)
  File "/usr/lib64/python2.6/json/__init__.py", line 267, in load
    parse_constant=parse_constant, **kw)
  File "/usr/lib64/python2.6/json/__init__.py", line 307, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.6/json/decoder.py", line 319, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.6/json/decoder.py", line 338, in raw_decode
    raise ValueError("No JSON object could be decoded")
```

In both cases, the return code is 3.

**Comment by jhomann** [comment]
This is fixed in 3dd66be5c02c5f7d1d28aa816cf0a11b79b0765a
