### ISSUE TITLE
Add a encoding variable in cfg

### ISSUE THREAD

**Issue by ethnchao** [NagiosEnterprises/ncpa#259]
Recently, I've installed the NCPA agent in windows, but the Web UI seems wrong, like this:

![image](https://cloud.githubusercontent.com/assets/20638812/17686904/0239a760-63a3-11e6-9fee-bd068ab484b2.png)

And here is the log file:

```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd7 in position 9: ordinal not in range(128)
2016-08-16 10:17:37,444:INFO:handler:192.168.100.119 - - [2016-08-16 10:17:37] "GET /static/img/ncpa-favicon.png HTTP/1.1" 500 412 0.046000
2016-08-16 10:17:37,476:ERROR:app:Exception on /static/img/ncpa-favicon.png [GET]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 1504, in wsgi_app
  File "C:\Python27\lib\site-packages\flask\app.py", line 1264, in full_dispatch_request
  File "C:\Python27\lib\site-packages\flask\app.py", line 1262, in full_dispatch_request
  File "C:\Python27\lib\site-packages\flask\app.py", line 1248, in dispatch_request
  File "C:\Python27\lib\site-packages\flask\helpers.py", line 623, in send_static_file
  File "C:\Python27\lib\site-packages\flask\helpers.py", line 473, in send_from_directory
  File "C:\Python27\lib\site-packages\flask\helpers.py", line 362, in send_file
  File "C:\Python27\lib\mimetypes.py", line 297, in guess_type
  File "C:\Python27\lib\mimetypes.py", line 358, in init
  File "C:\Python27\lib\mimetypes.py", line 258, in read_windows_registry
  File "C:\Python27\lib\mimetypes.py", line 249, in enum_types
```

I search about the issues, and now I already know the reason cause this issue: **My windows server is GBK encoding (Of course, I'm a chinese.)**, and ascii can't decode chinese word, so I have to set other default encoding( gbk or utf8 ).

I tried change the python lib/mimetypes.py to add this line:

```
if sys.getdefaultencoding() != 'gbk':
    reload(sys)
    sys.setdefaultencoding('gbk')
```

and compile it & replace the orignal file.

But I think it's NOT the right solution, so how about NCPA support alternative encoding setting?

**Comment by jomann09** [comment]
So this is interesting... it looks like on Windows there is an issue with non-ASCII filenames/path names. Looking over the other bugs that people have reported to flask it comes down to this bug in Python 2.7.x here **http://bugs.python.org/issue20140**

Did your change fix anything for you? Can you try using the Windows version 2.0.0 nightly build from here: https://assets.nagios.com/downloads/ncpa/nightly and see if that changes anything.

I'll try to take a look into this more to see if it is related to the Python issue I posted or if it's something with the way NCPA is trying to send static files. If you can confirm that your path/filenames have no non-ASCII characters we could rule out the Python issue.
