### ISSUE TITLE
[Windows/Update 1.8.1 ==> 2.0.0] Api endpoint system doesnt work

### ISSUE THREAD

**Issue by ccztux** [NagiosEnterprises/ncpa#277]
After update from 1.8.1 to 2.0.0 the api/system endpoint doesnt work neither in gui nor via check_ncpa.py.

check_ncpa.py:
```
09:31:37 [root@localhost]:/usr/local/nagios/libexec# ./check_ncpa.1.0.2.py -H my_ip -t my_token -M system -l -v
Connecting to: https://my_ip:5693/api/system/?token=my_token
An error occurred:HTTP Error 500: INTERNAL SERVER ERROR

09:31:49 [root@localhost]:/usr/local/nagios/libexec# ./check_ncpa.1.0.2.py -H my_ip -t my_token -M api/system -l -v
Connecting to: https://my_ip:5693/api/system/?token=my_token
An error occurred:HTTP Error 500: INTERNAL SERVER ERROR

09:31:55 [root@localhost]:/usr/local/nagios/libexec# ./check_ncpa.1.0.2.py -H my_ip -t my_token -M api/agent/system -l -v
Connecting to: https://my_ip:5693/api/agent/system/?token=my_token
File returned contained:
{
    "plugins": [
        "test.ps1",
        "test2.ps1"
    ]
}
plugins: [u'test.ps1', u'test2.ps1']

```

In the gui i only see the loading indicator.

**Comment by ccztux** [comment]
But this works:
```
09:39:37 [root@localhost]:/usr/local/nagios/libexec# ./check_ncpa.1.0.2.py -H my_ip -t my_token -M api/system/agent_version -l -v
Connecting to: https://my_ip:5693/api/system/agent_version/?token=my_token
File returned contained:
{
    "agent_version": "2.0.0"
}
agent_version: 2.0.0
```

**Comment by jomann09** [comment]
Can you show me your logs for this? `C:\Program Files (x86)\Nagios\NCPA\var`

**Comment by ludmilmm** [comment]
@ccztux 
Try removing the ncpa *.tmp files on the client:

`rm -rf /tmp/ncpa-*`

Next, try again:

`./check_ncpa.1.0.2.py -H my_ip -t my_token -M system -l -v`

Did this help?

**Comment by jomann09** [comment]
I believe he's running his NCPA on a Windows machine and it is returning that, if you'd like to clarify. I would need to see the logs in `C:\Program Files (x86)\Nagios\NCPA\var` to see why the 500 error is occurring.

**Comment by ludmilmm** [comment]
My bad. I should read titles, too. :) BTW, I had the same error (HTTP Error 500: INTERNAL SERVER ERROR) on CentOS machine, where removing the ncpa *.tmp files fixed the issue. 
And yeah, the logs should give us some clues.

**Comment by ccztux** [comment]
Here are the log entries in case of ```-M /api/system```:
```
2016-12-16 20:48:38,012:DEBUG:handler:Initializing WebSocket
2016-12-16 20:48:38,012:DEBUG:handler:Validating WebSocket request
2016-12-16 20:48:38,043:DEBUG:psapi:Imported windowscounters into the API tree.
2016-12-16 20:48:38,043:DEBUG:psapi:Imported windowslogs into the API tree.
2016-12-16 20:48:38,059:ERROR:app:Exception on /api/system [GET]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
  File "C:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
  File "C:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
  File "C:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
  File "C:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
  File "C:\ncpa\agent\listener\server.py", line 152, in token_auth_decoration
  File "C:\ncpa\agent\listener\server.py", line 932, in api
  File "C:\Python27\lib\json\__init__.py", line 244, in dumps
  File "C:\Python27\lib\json\encoder.py", line 207, in encode
  File "C:\Python27\lib\json\encoder.py", line 270, in iterencode
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe4 in position 11: invalid continuation byte
2016-12-16 20:48:38,059:INFO:handler:127.0.0.1 - - [2016-12-16 20:48:38] "GET /api/system HTTP/1.1" 500 4145 0.047000
```

**Comment by ccztux** [comment]
I have deleted all tempfiles under: ```C:\Windows\Temp\ncpa-*.tmp``` but it doesnt help.

**Comment by jomann09** [comment]
Hmm what language is your Windows OS in right now? And can you run through the nodes quick to see if you can find the node that causes it using the GUI?

**Comment by ccztux** [comment]
The OS language is german.
OS version: Windows 7 Enterprise SP1.
I have tried all nodes in the gui, but i have not noticed an issue there.

**Comment by ccztux** [comment]
On the affected machine there exists a python 2.7 and a python 3.5 installation. I thought, that this could have an impact and so i have removed them from PATH variable, but the issue still exists.

**Comment by jomann09** [comment]
Yeah it shouldn't be a problem having other versions of Python, I'm thinking it's character encodings somewhere - I will take a look into this... this would all be easier if we could use Python 3 :)

**Comment by ccztux** [comment]
Yeah, it sounds like an encoding issue. The path in the log messages gave me the idea it could be an issue with the existing python installation:
```
File "C:\Python27\lib\json\__init__.py", line 244, in dumps
````

The following requests work:
```
2016-12-16 22:45:50,148:INFO:handler:127.0.0.1 - - [2016-12-16 22:45:50] "GET /api/system/node HTTP/1.1" 200 303 0.031000
2016-12-16 22:46:02,019:DEBUG:handler:Initializing WebSocket
2016-12-16 22:46:02,019:DEBUG:handler:Validating WebSocket request
2016-12-16 22:46:02,051:DEBUG:psapi:Imported windowscounters into the API tree.
2016-12-16 22:46:02,051:DEBUG:psapi:Imported windowslogs into the API tree.
2016-12-16 22:46:02,051:INFO:handler:127.0.0.1 - - [2016-12-16 22:46:02] "GET /api/system/uptime HTTP/1.1" 200 331 0.031000
2016-12-16 22:46:06,059:DEBUG:handler:Initializing WebSocket
2016-12-16 22:46:06,059:DEBUG:handler:Validating WebSocket request
2016-12-16 22:46:06,092:DEBUG:psapi:Imported windowscounters into the API tree.
2016-12-16 22:46:06,092:DEBUG:psapi:Imported windowslogs into the API tree.
2016-12-16 22:46:06,092:INFO:handler:127.0.0.1 - - [2016-12-16 22:46:06] "GET /api/system/system HTTP/1.1" 200 304 0.032000
2016-12-16 22:46:17,137:DEBUG:handler:Initializing WebSocket
2016-12-16 22:46:17,137:DEBUG:handler:Validating WebSocket request
2016-12-16 22:46:17,183:DEBUG:psapi:Imported windowscounters into the API tree.
2016-12-16 22:46:17,183:DEBUG:psapi:Imported windowslogs into the API tree.
2016-12-16 22:46:17,183:INFO:handler:127.0.0.1 - - [2016-12-16 22:46:17] "GET /api/system/machine HTTP/1.1" 200 303 0.046000
2016-12-16 22:46:28,275:DEBUG:handler:Initializing WebSocket
2016-12-16 22:46:28,275:DEBUG:handler:Validating WebSocket request
2016-12-16 22:46:28,290:DEBUG:psapi:Imported windowscounters into the API tree.
2016-12-16 22:46:28,290:DEBUG:psapi:Imported windowslogs into the API tree.
2016-12-16 22:46:28,290:INFO:handler:127.0.0.1 - - [2016-12-16 22:46:28] "GET /api/system/version HTTP/1.1" 200 306 0.016000
2016-12-16 22:46:34,467:DEBUG:handler:Initializing WebSocket
2016-12-16 22:46:34,467:DEBUG:handler:Validating WebSocket request
2016-12-16 22:46:34,515:DEBUG:psapi:Imported windowscounters into the API tree.
2016-12-16 22:46:34,515:DEBUG:psapi:Imported windowslogs into the API tree.
2016-12-16 22:46:34,515:INFO:handler:127.0.0.1 - - [2016-12-16 22:46:34] "GET /api/system/release HTTP/1.1" 200 299 0.047000
2016-12-16 22:46:42,611:DEBUG:handler:Initializing WebSocket
2016-12-16 22:46:42,611:DEBUG:handler:Validating WebSocket request
2016-12-16 22:46:42,627:DEBUG:psapi:Imported windowscounters into the API tree.
2016-12-16 22:46:42,627:DEBUG:psapi:Imported windowslogs into the API tree.
2016-12-16 22:46:42,627:INFO:handler:127.0.0.1 - - [2016-12-16 22:46:42] "GET /api/system/processor HTTP/1.1" 200 350 0.015000
2016-12-16 22:46:55,778:DEBUG:handler:Initializing WebSocket
2016-12-16 22:46:55,778:DEBUG:handler:Validating WebSocket request
2016-12-16 22:46:55,793:DEBUG:psapi:Imported windowscounters into the API tree.
2016-12-16 22:46:55,793:DEBUG:psapi:Imported windowslogs into the API tree.
2016-12-16 22:46:55,809:INFO:handler:127.0.0.1 - - [2016-12-16 22:46:55] "GET /api/system/system HTTP/1.1" 200 304 0.031000
2016-12-16 22:46:59,490:DEBUG:handler:Initializing WebSocket
2016-12-16 22:46:59,490:DEBUG:handler:Validating WebSocket request
2016-12-16 22:46:59,506:DEBUG:psapi:Imported windowscounters into the API tree.
2016-12-16 22:46:59,506:DEBUG:psapi:Imported windowslogs into the API tree.
```

**Comment by ccztux** [comment]
Are there some new endpoints under the api/system nodes? I have done the requests, which work, on the output of an 1.8.1 installation. Maybe there is a new endpoint, which i dont know, because i could not list them, and the new endpoint is causing this issue?

**Comment by jomann09** [comment]
`system/time` and `system/timezone` were added recently and weren't in 1.8.1

**Comment by ccztux** [comment]
Maybe we are one step closer:

```system/time``` works:
```
2016-12-16 23:08:53,312:INFO:handler:127.0.0.1 - - [2016-12-16 23:08:53] "GET /api/system/time HTTP/1.1" 200 307 0.024000
2016-12-16 23:09:03,207:DEBUG:handler:Initializing WebSocket
2016-12-16 23:09:03,207:DEBUG:handler:Validating WebSocket request
2016-12-16 23:09:03,230:DEBUG:psapi:Imported windowscounters into the API tree.
2016-12-16 23:09:03,232:DEBUG:psapi:Imported windowslogs into the API tree.
```


```system/timezone``` doesnt work:
```
2016-12-16 23:09:03,232:ERROR:app:Exception on /api/system/timezone [GET]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
  File "C:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
  File "C:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
  File "C:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
  File "C:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
  File "C:\ncpa\agent\listener\server.py", line 152, in token_auth_decoration
  File "C:\ncpa\agent\listener\server.py", line 932, in api
  File "C:\Python27\lib\json\__init__.py", line 251, in dumps
  File "C:\Python27\lib\json\encoder.py", line 209, in encode
  File "C:\Python27\lib\json\encoder.py", line 434, in _iterencode
  File "C:\Python27\lib\json\encoder.py", line 408, in _iterencode_dict
  File "C:\Python27\lib\json\encoder.py", line 313, in _iterencode_list
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe4 in position 11: invalid continuation byte
2016-12-16 23:09:03,233:INFO:handler:127.0.0.1 - - [2016-12-16 23:09:03] "GET /api/system/timezone HTTP/1.1" 500 4145 0.026000
```
