### ISSUE TITLE
Install 2.0 on centOS

### ISSUE THREAD

**Issue by kingdingaling83** [NagiosEnterprises/ncpa#281]
[root@grhldesv02 ncpa]# /etc/init.d/ncpa_listener start
Starting NCPA Listener:                                    [  OK  ]
[root@grhldesv02 ncpa]# /etc/init.d/ncpa_listener status
service is not running
NCPA Listener

did an uninstall of the previous version, installed the new update. 

for some reason the service wont stay up.

what logs should i provide?

**Comment by jomann09** [comment]
What version of CentOS are you installing on? You can look in the logs at `/usr/local/ncpa/var/log`, the `ncpa_listener.log` should have Python errors if it's not working that will give us some insight.

**Comment by kingdingaling83** [comment]
root@grhldesv02(~):cat /etc/*release
CentOS release 6.8 (Final)
LSB_VERSION=base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
CentOS release 6.8 (Final)
CentOS release 6.8 (Final)

`root@grhldesv02(~):cat /usr/local/ncpa/var/log/ncpa_listener.log
2016-12-16 11:30:12,453 131001 INFO started
2016-12-16 11:30:12,454 131001 INFO Using SSL version TLSv1_2
2016-12-16 11:30:12,620 131001 ERROR [Errno 98] Address already in use: ('0.0.0.0', 5693)
Traceback (most recent call last):
  File "ncpa_listener.py", line 78, in run
  File "/usr/local/lib/python2.7/site-packages/gevent/baseserver.py", line 347, in serve_forever
  File "/usr/local/lib/python2.7/site-packages/gevent/baseserver.py", line 291, in start
  File "/usr/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 1222, in init_socket
  File "/usr/local/lib/python2.7/site-packages/gevent/server.py", line 80, in init_socket
  File "/usr/local/lib/python2.7/site-packages/gevent/server.py", line 91, in get_listener
  File "/usr/local/lib/python2.7/site-packages/gevent/server.py", line 177, in _tcp_listener
  File "<string>", line 1, in bind
error: [Errno 98] Address already in use: ('0.0.0.0', 5693)
2016-12-16 11:30:12,620 131001 INFO stopped
2016-12-16 11:33:04,059 131590 INFO started
2016-12-16 11:33:04,060 131590 INFO Using SSL version TLSv1_2
2016-12-16 11:33:04,060 131590 ERROR [Errno 98] Address already in use: ('0.0.0.0', 5693)
Traceback (most recent call last):
  File "ncpa_listener.py", line 78, in run
  File "/usr/local/lib/python2.7/site-packages/gevent/baseserver.py", line 347, in serve_forever
  File "/usr/local/lib/python2.7/site-packages/gevent/baseserver.py", line 291, in start
  File "/usr/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 1222, in init_socket
  File "/usr/local/lib/python2.7/site-packages/gevent/server.py", line 80, in init_socket
  File "/usr/local/lib/python2.7/site-packages/gevent/server.py", line 91, in get_listener
  File "/usr/local/lib/python2.7/site-packages/gevent/server.py", line 177, in _tcp_listener
  File "<string>", line 1, in bind
error: [Errno 98] Address already in use: ('0.0.0.0', 5693)
2016-12-16 11:33:04,061 131590 INFO stopped
2016-12-16 11:36:31,354 132292 INFO started
2016-12-16 11:36:31,355 132292 INFO Using SSL version TLSv1_2
2016-12-16 11:36:31,356 132292 ERROR [Errno 98] Address already in use: ('0.0.0.0', 5693)
Traceback (most recent call last):
  File "ncpa_listener.py", line 78, in run
  File "/usr/local/lib/python2.7/site-packages/gevent/baseserver.py", line 347, in serve_forever
  File "/usr/local/lib/python2.7/site-packages/gevent/baseserver.py", line 291, in start
  File "/usr/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 1222, in init_socket
  File "/usr/local/lib/python2.7/site-packages/gevent/server.py", line 80, in init_socket
  File "/usr/local/lib/python2.7/site-packages/gevent/server.py", line 91, in get_listener
  File "/usr/local/lib/python2.7/site-packages/gevent/server.py", line 177, in _tcp_listener
  File "<string>", line 1, in bind
error: [Errno 98] Address already in use: ('0.0.0.0', 5693)
2016-12-16 11:36:31,356 132292 INFO stopped
2016-12-16 11:42:04,928 133613 INFO started
2016-12-16 11:42:04,929 133613 INFO Using SSL version TLSv1_2
2016-12-16 11:42:04,930 133613 ERROR [Errno 98] Address already in use: ('0.0.0.0', 5693)
Traceback (most recent call last):
  File "ncpa_listener.py", line 78, in run
  File "/usr/local/lib/python2.7/site-packages/gevent/baseserver.py", line 347, in serve_forever
  File "/usr/local/lib/python2.7/site-packages/gevent/baseserver.py", line 291, in start
  File "/usr/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 1222, in init_socket
  File "/usr/local/lib/python2.7/site-packages/gevent/server.py", line 80, in init_socket
  File "/usr/local/lib/python2.7/site-packages/gevent/server.py", line 91, in get_listener
  File "/usr/local/lib/python2.7/site-packages/gevent/server.py", line 177, in _tcp_listener
  File "<string>", line 1, in bind
error: [Errno 98] Address already in use: ('0.0.0.0', 5693)
2016-12-16 11:42:04,930 133613 INFO stopped`

**Comment by jomann09** [comment]
Was this an upgrade? It looks like something is already using port 5693. Can you do a `ps aux | grep ncpa`

**Comment by kingdingaling83** [comment]
root@grhldesv02(/tmp):ps aux | grep ncpa
root      47940  0.0  0.0 230180 20792 ?        S    Dec14   0:06 /usr/local/ncpa/ncpa_posix_passive --start
root      48121  1.0  0.0 325140 28948 ?        Sl   Dec14  76:35 ./ncpa_posix_listener --start
root     128531  0.0  0.0 103316   904 pts/0    S+   10:18   0:00 grep ncpa
nagios   131022  0.0  0.0 257068 31144 ?        S    Dec16   0:24 /usr/local/ncpa/ncpa_passive --start
root@grhldesv02(/tmp):

**Comment by jomann09** [comment]
Interesting, looks like you have the old version still running - when you install the rpm it's supposed to stop the old one but looks like it never did.

```
root 47940 0.0 0.0 230180 20792 ? S Dec14 0:06 /usr/local/ncpa/ncpa_posix_passive --start
root 48121 1.0 0.0 325140 28948 ? Sl Dec14 76:35 ./ncpa_posix_listener --start
```

Are the old ones, you can just kill them and then restart both the services
