### ISSUE TITLE
Troubles with api/network in Windows 8.1 (Russian Language)

### ISSUE THREAD

**Issue by ravenich** [NagiosEnterprises/ncpa#296]
When i try to open https://localhost:5693/gui/ap/network on Windows 8.1 (with russian mui), i see loading animation and nothing more.
Same error - https://localhost:5693/api/system
No errors on windows with english mui.

ncpa_listener.log:
2017-01-05 16:45:13,562:INFO:handler:127.0.0.1 - - [2017-01-05 16:45:13] "GET /api/interface HTTP/1.1" 500 4145 0.137000
2017-01-05 16:45:13,565:DEBUG:handler:Initializing WebSocket
2017-01-05 16:45:13,565:DEBUG:handler:Validating WebSocket request
2017-01-05 16:45:13,572:DEBUG:psapi:Imported windowscounters into the API tree.
2017-01-05 16:45:13,572:DEBUG:psapi:Imported windowslogs into the API tree.
2017-01-05 16:45:13,661:ERROR:app:Exception on /api/interface [GET]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
  File "C:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
  File "C:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
  File "C:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
  File "C:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
  File "C:\ncpa\agent\listener\server.py", line 154, in token_auth_decoration
  File "C:\ncpa\agent\listener\server.py", line 942, in api
  File "C:\Python27\lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xcf in position 0: invalid continuation byte
2017-01-05 16:45:13,667:INFO:handler:127.0.0.1 - - [2017-01-05 16:45:13] "GET /api/interface HTTP/1.1" 500 4145 0.101000

**Comment by ravenich** [comment]
Same as #295
