### ISSUE TITLE
/api/service/sshd/running

### ISSUE THREAD

**Issue by metabsd** [NagiosEnterprises/ncpa#308]
Hi, I try to use NCPA to monitor the status of sshd service but NCPA return permission denied on another init.d script.

2017-02-03 12:39:36,572 24816 ERROR Exception on /api/service/sshd/running/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
  File "/root/ncpa/agent/listener/server.py", line 154, in token_auth_decoration
  File "/root/ncpa/agent/listener/server.py", line 937, in api
  File "/root/ncpa/agent/listener/services.py", line 266, in run_check
  File "/root/ncpa/agent/listener/services.py", line 17, in wrapper
  File "/root/ncpa/agent/listener/services.py", line 156, in get_services_via_initctl
  File "/root/ncpa/agent/listener/services.py", line 17, in wrapper
  File "/root/ncpa/agent/listener/services.py", line 197, in get_services_via_initd
  File "/root/ncpa/agent/listener/services.py", line 197, in <lambda>
OSError: [Errno 13] Permission denied: '/etc/init.d/dsmcad'

I valide the script is ok,

[root@slqwas0554 log]# /etc/init.d/dsmcad
Usage: /etc/init.d/dsmcad {start|stop|restart|status}

I validate the permission of the script :

ll /etc/init.d/dsmcad
lrwxrwxrwx 1 root bin 39 Feb 18  2013 /etc/init.d/dsmcad -> /opt/tivoli/tsm/client/ba/bin/rc.dsmcad
ll /opt/tivoli/tsm/client/ba/bin/rc.dsmcad
-r-xr-xr-x 1 root bin 1638 Oct 19  2012 /opt/tivoli/tsm/client/ba/bin/rc.dsmcad

The problem was /opt/tivoli can be use only by root. I make sure /opt/tivoli can be use by other user to make accessible the init script by Nagios. Can you make sure ncpa don't crash if another init script is not accessible by Nagios.

Thank you!

**Comment by jomann09** [comment]
Just so you know I will put this in the next release, whatever type of release that may be. Not sure on when that will be but probably a couple weeks unless there are other problems that show up.

**Comment by jomann09** [comment]
Fixed this crashing but it may not show up in the list of services. I actually couldn't get the error to replicate even with setting very restrictive permissions on things so although the fix will cause it to not crash it is likely not the "best" option, this way of getting services may be something I need to refactor in another release.

**Comment by jomann09** [comment]
Oh also as a side note, you may want to update checks to use the `/api/services?service=<servicename>&status=running` way of calling that specific check so that it will work in future versions including 2.1 which should be out in a couple months.

**Comment by metabsd** [comment]
Another possibility ::

2017-02-16 09:24:06,104 6706 ERROR Exception on /api/service/sshd/running/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
  File "/root/ncpa/agent/listener/server.py", line 154, in token_auth_decoration
  File "/root/ncpa/agent/listener/server.py", line 939, in api
  File "/root/ncpa/agent/listener/services.py", line 266, in run_check
  File "/root/ncpa/agent/listener/services.py", line 17, in wrapper
  File "/root/ncpa/agent/listener/services.py", line 156, in get_services_via_initctl
  File "/root/ncpa/agent/listener/services.py", line 17, in wrapper
  File "/root/ncpa/agent/listener/services.py", line 197, in get_services_via_initd
  File "/root/ncpa/agent/listener/services.py", line 197, in <lambda>
OSError: [Errno 2] No such file or directory: '/etc/init.d/archiva'

**Comment by jomann09** [comment]
Is that on CentOS 6? Can you test the 2.0.3 version to see if that is fixed properly?
https://assets.nagios.com/downloads/ncpa/dev/

I can't seem to get the OSError to happen for me.
