### ISSUE TITLE
Windows 2008 R2 with French Language Pack - API never get back

### ISSUE THREAD

**Issue by metabsd** [NagiosEnterprises/ncpa#330]
NCPA DEBUG LOG
-------------------------

2017-04-07 11:30:29,322:INFO:ncpa_windows:Parsed config from: ['C:\\Program Files (x86)\\Nagios\\NCPA\\etc\\ncpa.cfg', 'C:\\Program Files (x86)\\Nagios\\NCPA\\etc\\ncpa.cfg.d\\example.cfg']
2017-04-07 11:30:29,322:INFO:ncpa_windows:Looking for plugins at: C:\Program Files (x86)\Nagios\NCPA\plugins
2017-04-07 11:30:29,323:INFO:ncpa_windows:Using SSL version TLSv1_2
2017-04-07 11:30:47,469:DEBUG:handler:Initializing WebSocket
2017-04-07 11:30:47,469:DEBUG:handler:Validating WebSocket request
2017-04-07 11:30:47,471:INFO:handler:172.26.240.22 - - [2017-04-07 11:30:47] "GET /gui/api HTTP/1.1" 302 540 0.003000
2017-04-07 11:30:47,523:DEBUG:handler:Initializing WebSocket
2017-04-07 11:30:47,525:DEBUG:handler:Validating WebSocket request
2017-04-07 11:30:47,556:INFO:handler:172.26.240.22 - - [2017-04-07 11:30:47] "GET /login HTTP/1.1" 200 3070 0.033000
2017-04-07 11:30:54,874:DEBUG:handler:Initializing WebSocket
2017-04-07 11:30:54,875:DEBUG:handler:Validating WebSocket request
2017-04-07 11:30:54,875:DEBUG:handler:Can only upgrade connection if using GET method.
2017-04-07 11:30:54,877:INFO:handler:172.26.240.22 - - [2017-04-07 11:30:54] "POST /login HTTP/1.1" 302 599 0.003000
2017-04-07 11:30:54,943:DEBUG:handler:Initializing WebSocket
2017-04-07 11:30:54,943:DEBUG:handler:Validating WebSocket request
2017-04-07 11:30:54,987:INFO:handler:172.26.240.22 - - [2017-04-07 11:30:54] "GET /gui/api HTTP/1.1" 200 52056 0.044000
2017-04-07 11:30:55,346:DEBUG:handler:Initializing WebSocket
2017-04-07 11:30:55,348:DEBUG:handler:Validating WebSocket request
2017-04-07 11:30:56,377:DEBUG:psapi:Imported windowscounters into the API tree.
2017-04-07 11:30:56,377:DEBUG:psapi:Imported windowslogs into the API tree.
2017-04-07 11:30:56,417:ERROR:app:Exception on /api/ [GET]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
  File "C:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
  File "C:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
  File "C:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
  File "C:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
  File "C:\ncpa\agent\listener\server.py", line 154, in token_auth_decoration
  File "C:\ncpa\agent\listener\server.py", line 944, in api
  File "C:\Python27\lib\json\__init__.py", line 244, in dumps
  File "C:\Python27\lib\json\encoder.py", line 207, in encode
  File "C:\Python27\lib\json\encoder.py", line 270, in iterencode
UnicodeDecodeError: 'utf8' codec can't decode byte 0x92 in position 12: invalid start byte
2017-04-07 11:30:56,424:INFO:handler:172.26.240.22 - - [2017-04-07 11:30:56] "GET /api/ HTTP/1.1" 500 4145 1.078000

**Comment by jomann09** [comment]
This is a common issue it seems with non-English due to some weird utf8 problems in Python 2.x, let me try a couple things and get back to you on this. It's related to #296 and #277.

**Comment by jomann09** [comment]
I'm updating 2.0.4 to hopefully not throw errors when this happens. Note that until NCPA 3, some text may not be encoded properly in the web UI.

**Comment by metabsd** [comment]
It's about that ?

https://docs.python.org/3/reference/lexical_analysis.html#grammar-token-stringprefix

**Comment by jomann09** [comment]
That I believe is how it represents characters that it cannot decode (I think) but has something to do with all of this - essentially the change that I added in 2.0.4 would print out a value that doesn't look like a character if it cannot decode it.

**Comment by jomann09** [comment]
You can download a dev build of 2.0.4 here if you'd like https://assets.nagios.com/downloads/ncpa/dev/ and see if it'll output from the API without causing errors. It may have un-decoded text in it though.

**Comment by jomann09** [comment]
Going to close this because I think 2.0.4 will help and I can't recreate it myself even with a French setup on Server 2008 R2 or Windows 7!
