### ISSUE TITLE
NCPA 2.0.3 passive check ExpatError: syntax error: line 1, column 49

### ISSUE THREAD

**Issue by lovemenot** [NagiosEnterprises/ncpa#331]
Good day.

I configured the client for NCPA passive check.

```
%HOSTNAME%|__HOST__ = system/agent_version
%HOSTNAME%|CPU Usage = cpu/percent --warning 60 --critical 80 --aggregate avg
%HOSTNAME%|Swap Usage = memory/swap --warning 60 --critical 80 --units Gi
%HOSTNAME%|Memory Usage = memory/virtual --warning 80 --critical 90 --units Gi
%HOSTNAME%|Process Count = processes --warning 300 --critical 400
```

Checking the file /usr/local/ncpa/var/log/ncpa_passive.log found error below:

ExpatError: syntax error: line 1, column 49
Traceback (most recent call last)
   File "ncpa_passive.py:, line 45, in run_all_handlers
   File "/root/ncpa/agent/passive/nrdp.py", line 124, in run
   File "/root/ncpa/agent/passive/nrdp.py", line 179, in submit_to_nagios
   File "/root/ncpa/agent/passive/nrdp.py", line 145, in log_result
   File "/usr/local/lib/python2.7/xml/dom/minidom.py", line 1928, in parseString
   File "/usr/local/lib/python2.7/xml/dom/expatbuilder.py", line 940, in parseString
   File "/usr/local/lib/python2.7/xml/dom/expatbuilder.py", line 223, in parseString

Thanks,

Ronald

**Comment by jomann09** [comment]
This looks like it's erroring out at the end of the send command. Did it send the data back to the NRDP server? The ExpatError could be from the return value not being a string like it expected.

**Comment by lovemenot** [comment]
Thank you Jomann09, You are correct, from the receiving server (Nagios NRDP) the error issues are coming. Need to add from nrdp.conf file "Require all granted".

**Comment by jomann09** [comment]
Glad to hear it, must have had Apache 2.4 installed and the Apache 2.2 nrdp configuration. Not sure how that would have happened but glad you got it sorted out.
