### ISSUE TITLE
NCPA 2.0.3 doesn't start on Opensuse 13.2

### ISSUE THREAD

**Issue by meabandit** [NagiosEnterprises/ncpa#334]
```
linux-5c8n:~ # /usr/local/ncpa/ncpa_listener
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/cx_Freeze-4.3.4-py2.7-linux-x86_64.egg/cx_Freeze/initscripts/Console.py", line 27, in <module>
  File "ncpa_listener.py", line 8, in <module>
  File "/root/ncpa/agent/listener/certificate.py", line 2, in <module>
  File "/usr/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
  File "/usr/lib/python2.7/site-packages/OpenSSL/rand.py", line 12, in <module>
  File "/usr/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
  File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 141, in <module>
  File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 125, in init_static_locks
ImportError: /usr/local/ncpa/_ssl.so: undefined symbol: SSLv2_method
```
```
# rpm -qa |grep ncpa
ncpa-2.0.3-1.x86_64
```
The system is fully updated against stock 13.2 repos.

**Comment by jomann09** [comment]
Looking into this. It looks like openssl was updated in the repos and SSLv2 was removed (they upgraded to 1.0.1i by default) so we will just need to re-build these with updated build boxes.

**Comment by jomann09** [comment]
Latest builds should show up in the next 5 minutes and will work on 13.2 - it was definitely due to the version of OpenSSL that is available. For the time being, we will be using the libssl.so that is bundled with the NCPA agent.
