### ISSUE TITLE
NCPA - RHEL - Database lock ??

### ISSUE THREAD

**Issue by metabsd** [NagiosEnterprises/ncpa#348]
I have to restart couple server this morning. After the reboot I wait for the agent coming back but he never come back. I find that in the log.

2017-05-31 16:08:59,573 2413 INFO stopped
2017-05-31 16:11:00,756 2248 INFO started
2017-05-31 16:11:05,969 2248 ERROR stopping with an exception
Traceback (most recent call last):
  File "/root/ncpa/agent/ncpadaemon.py", line 197, in start
  File "ncpa_listener.py", line 43, in run
  File "/root/ncpa/agent/listener/database.py", line 57, in run_db_maintenance
OperationalError: database is locked
2017-05-31 16:11:05,970 2248 INFO stopped
2017-06-01 08:59:49,094 2341 INFO started
2017-06-01 08:59:54,311 2341 ERROR stopping with an exception
Traceback (most recent call last):
  File "/root/ncpa/agent/ncpadaemon.py", line 197, in start
  File "ncpa_listener.py", line 43, in run
  File "/root/ncpa/agent/listener/database.py", line 57, in run_db_maintenance
OperationalError: database is locked
2017-06-01 08:59:54,312 2341 INFO stopped
2017-06-05 09:19:32,984 23727 INFO started
2017-06-05 09:19:33,045 23727 INFO Using SSL version TLSv1_2

ncpa_listener is stop.
ncpa_passive is started.

I try to start couple time ncpa_listener. I see nothing new in the log. I have to stop ncpa_passive and after that I was able to start ncpa_listener.

I don't understand ...

**Comment by jomann09** [comment]
I'm going to consider this a bug, so I will look into it further.

To fix the problem though, it looks like the db is corrupt somehow. You can safely delete the `/usr/local/ncpa/var/ncpa.db` and restart both the listener and the passive agents and it should re-create the database automatically.

**Comment by jomann09** [comment]
Should be fixed by 57d4f410c1d64127bf6ba67d3de6ca827237e72e since it seems like the db timeout typically resolves this issue. Since on startup the passive and listener services do a bit of db maintenance, it may have been running at the time it was trying to connect.

**Comment by metabsd** [comment]
Hi,

I restart a server and after the reboot I see tha message in the ncpa_listener.log

```
2017-06-15 14:16:45,113 2423 ERROR stopping with an exception
Traceback (most recent call last):
  File "/root/ncpa/agent/ncpadaemon.py", line 197, in start
  File "ncpa_listener.py", line 43, in run
  File "/root/ncpa/agent/listener/database.py", line 57, in run_db_maintenance
OperationalError: database is locked
2017-06-15 14:16:45,114 2423 INFO stopped
```

I try to delete ` /usr/local/ncpa/var/ncpa.db` and restart ncpa_listener but it's not working.

ncpa_passive work fine but ncpa_listener don't work.

Can you help me to troubleshoot that.

I use RHEL 7.

Thank you!

**Comment by jomann09** [comment]
Are you running the latest version of the code?

**Comment by metabsd** [comment]
I run 2.0.3. I make sure listener and passive is stopped and delete ncpa.db and restart and it's working. Do you know the reason of that bug ??? I don't understand.. We only reboot the server.

**Comment by jomann09** [comment]
It is possible it was trying to write to the DB when the server went down or something... I'm not really sure, it's a pretty vague error code from what I've read.

That being said, I am looking into ways to make sure that doesn't happen.

**Comment by metabsd** [comment]
I think the init script not working fine on RHEL 7.

**Comment by jomann09** [comment]
I tested restarting the RHEL 7 system I installed on without problems, is it possible for you to post the ncpa.cfg and any other configs you have set up? Remove anything that you can't post of course!
