### ISSUE TITLE
NCPA listener service has status 'starting' after windows restart

### ISSUE THREAD

**Issue by svanwijk** [NagiosEnterprises/ncpa#357]
Periodically when a windows OS is rebooted (i.e. after windows updates) the NCPAlistener service does not fully start after reboot but hangs in the 'starting' state.

in the win32service_ncpalistener.log the following error is logged:

```

[03752] 2017/06/29 14:40:22.977 starting logging at level ERROR
[03752] 2017/06/29 14:40:24.523 Python exception encountered:
[03752] 2017/06/29 14:40:24.523     Internal Message: cannot import service module
[03752] 2017/06/29 14:40:24.539     Type => <type 'exceptions.EOFError'>
[03752] 2017/06/29 14:40:24.539     Value => EOF read where not expected
[03752] 2017/06/29 14:40:24.539     Traceback (most recent call last):
[03752] 2017/06/29 14:40:24.539       File "C:\ncpa\agent\ncpa_windows.py", line 15, in <module>
[03752] 2017/06/29 14:40:24.539       File "C:\ncpa\agent\passive\nrds.py", line 4, in <module>
[03752] 2017/06/29 14:40:24.539       File "C:\ncpa\agent\passive\nagioshandler.py", line 3, in <module>
[03752] 2017/06/29 14:40:24.539       File "C:\ncpa\agent\passive\ncpacheck.py", line 9, in <module>
[03752] 2017/06/29 14:40:24.539       File "C:\ncpa\agent\listener\server.py", line 3, in <module>
[03752] 2017/06/29 14:40:24.539       File "C:\Python27\lib\site-packages\flask\__init__.py", line 17, in <module>
[03752] 2017/06/29 14:40:24.539       File "C:\Python27\lib\site-packages\werkzeug\__init__.py", line 152, in <module>
[03752] 2017/06/29 14:40:24.539       File "C:\Python27\lib\site-packages\werkzeug\exceptions.py", line 71, in <module>
[03752] 2017/06/29 14:40:24.539       File "C:\Python27\lib\site-packages\werkzeug\wrappers.py", line 26, in <module>
[03752] 2017/06/29 14:40:24.539       File "C:\Python27\lib\site-packages\werkzeug\http.py", line 1012, in <module>
[03752] 2017/06/29 14:40:24.539       File "C:\Python27\lib\site-packages\werkzeug\datastructures.py", line 13, in <module>
[03752] 2017/06/29 14:40:24.539     EOFError: EOF read where not expected
```

This seem to occur randomly, we can restart 3 servers with the exam same configuration and only 1 will have the problem. The frequency does seem higher after a restart caused by windows updates.

It does not seem to be dependent on the NCPA client version or the Windows OS version.

**Comment by jomann09** [comment]
I have not seen this before, I will have to look into it and see what could be causing the error.

**Comment by jomann09** [comment]
Hi there, I know this is almost a month old now but I wanted to see if you could answer a couple questions for me:
- What version of NCPA are you running?
- When you go into services and look at NCPA is the `startup type` set to `Automatic (Delayed Start)`?
- Can you also let me know what version of Windows you're using, if it's multiple that's fine too

**Comment by svanwijk** [comment]
Hi,

- We are running the 2.0.4 version
- The startup is set to Automatic delayed start
- The problems occurs on both Windows Server 2008R2 and Server 2012R2 hosts.

THe problem only occurs when the server has restart to install windows updates and even in that its not consistent. I restarted a server a dozen times using a normal restart, and the issue did not occur, when i rebooted 3 server after windows updates 1 provided me with the problem and the other 2 did not.

Please let me know of i can provide you with any other information.

**Comment by svanwijk** [comment]
If you need any extra information please let me know.

**Comment by metabsd** [comment]
I have the same bug on RHEL 7 and I fix it by rm -f /usr/local/ncpa/var/ncpa.db and restart the service.
Some corruption in the ncpa.db

**Comment by jomann09** [comment]
Interesting, I haven't been able to re-create it, that is what it's been waiting on. I will double check some things with the DB though, it may be that the DB is getting corrupt when trying to write, NCPA getting closed or shut down, and the write not going through all the way.

**Comment by jomann09** [comment]
I'm going to close this, since there really isn't anything I can do about this error.

From my research it looks like the issue has to do with the caching that werkzeug does, or possibly the way it reads in files/cached items. The likely issues is that they were in some sort of non-readable state that caused it to crash.

I hope that with version 3 and the change to Python 3.x / cx_Freeze 5+ will fix the issues that we have had with certain errors when the actual service itself starts, like this one.
