### ISSUE TITLE
ncpa_passive failed to start with systemd (Debian Jessie)

### ISSUE THREAD

**Issue by acefreakz** [NagiosEnterprises/ncpa#366]
I got this error in /usr/local/ncpa/var/log/ncpa_passive.log after running `systemctl start ncpa_passive`.
```
2017-05-31 19:47:26,031 1070 INFO started
2017-05-31 19:47:26,036 1070 ERROR stopping with an exception
Traceback (most recent call last):
  File "/root/ncpa/agent/ncpadaemon.py", line 197, in start
  File "ncpa_passive.py", line 53, in run
  File "/root/ncpa/agent/ncpadaemon.py", line 127, in read_basic_config
  File "/root/ncpa/agent/ncpadaemon.py", line 362, in get_uid_gid
  File "/usr/local/lib/python2.7/ConfigParser.py", line 607, in get
NoSectionError: No section: u'passive'
2017-05-31 19:47:26,036 1070 INFO stopped
```

Here's the output of the status:
```
root@microsys-r610:/usr/local/ncpa# systemctl status ncpa_passive
â ncpa_passive.service - LSB: This manages the NCPA Passive service
   Loaded: loaded (/etc/init.d/ncpa_passive)
   Active: active (exited) since Sun 2017-08-13 22:24:52 +08; 1h 17min ago
  Process: 6460 ExecStop=/etc/init.d/ncpa_passive stop (code=exited, status=0/SUCCESS)
  Process: 6686 ExecStart=/etc/init.d/ncpa_passive start (code=exited, status=0/SUCCESS)

Aug 13 22:24:52 microsys-r610 ncpa_passive[6686]: Started NCPA Passive
Aug 13 22:24:52 microsys-r610 ncpa_passive[6686]: another instance seems to be running (pid 6653), exiting
Aug 13 22:24:52 microsys-r610 systemd[1]: Started LSB: This manages the NCPA Passive service.
```

However running it by `/etc/init.d/ncpa_passive --start` works just fine. Any idea? 
btw, am on NCPA 2.0.3.

**Comment by jomann09** [comment]
This error is probably due to your `ncpa.cfg` missing the [passive] portion. Can you copy in your config? Make sure you remove any information that might be sensitive like tokens/passwords.

**Comment by acefreakz** [comment]
Mmm i checked that the ncpa.cfg did have the passive portion.
```
#
#   NCPA Main Config File
#   ---------------------
#
#
#
# -------------------------------
# General Configuration
# -------------------------------
#

[general]

#
# Check logging is on by default, you can disable it if you do not want to record
# the check requests that are coming in or checks being sent over NRDP.
# Default: check_logging = 1
#
check_logging = 1

#
# Check logging time - how long in DAYS you'd like to keep checks in the database.
# Default: 30
#
check_logging_time = 30

#
# -------------------------------
# Listener Configuration (daemon)
# -------------------------------
#

[listener]

#
# User and group to run plugins as (recommended to use nagios:nagios)
# Default: uid = nagios
# Default: gid = nagios
#
# ** Note - The daemon runs as root, but forks a child process when running a plugin
#    that is defined by the user, for security reasons. However, without the main daemon
#    running as root, much of the system information would be missing. This is typical behavior. **
#
# This is for Unix only (Linux, Mac OS X, etc)
#
uid = nagios
gid = nagios

#
# IP address and port number for the Listener to use for the web GUI and API
# Default: ip = 0.0.0.0
# Default: port = 5963
#
ip = 0.0.0.0
port = 5693

#
# SSL connection and certificate config (if an SSL option is not available on some older
# operating systems it will default back to TLSv1)
# ssl_version options: TLSv1, TLSv1_1, TLSv1_2
#
ssl_version = TLSv1_2
certificate = adhoc

#
# Listener logging file level, location, and the PID location
# Default: loglevel = info (debug, info, warning, error)
# Default: logfile = var/log/ncpa_listener.log
# Default: pidfile = var/run/ncpa_listener.pid (leave listener in pid file name)
#
loglevel = info
logfile = var/log/ncpa_listener.log
pidfile = var/run/ncpa_listener.pid

#
# Delay the listener (API & web GUI) from starting in seconds
# Default: 0
#
# delay_start = 30

#
# Allow admin functionality in the web GUI. When this is set to 0, the admin section will not
# be displayed in the header and will not be available to be accessed.
# Default: 1
#
admin_gui_access = 1

#
# Admin password for the admin section in the web GUI, by default there is no admin
# password and the admin section of the GUI can be accessed by anyone if admin_gui_access is set to 1.
# Default: None
#
# Note: Setting this value to 'None' will automatically log you in, setting it empty will allow you to
# log in using a blank password.
#
admin_password = None

#
# Require admin password to access ALL of the web GUI.
# This does not affect API access via token (community_string).
# Default: 0
#
admin_auth_only = 0

#
# -------------------------------
# Listener Configuration (API)
# -------------------------------
#

[api]

#
# The token that will be used to log into the basic web GUI (API browser, graphs, top charts, etc)
# and to authenticate requests to the API and requests through check_ncpa.py
#
community_string = ****

#
# -------------------------------
# Passive Configuration (daemon)
# -------------------------------
#

[passive]

#
# Handlers are a comma separated list of what you would like the passive agent to run
# Default: None
# Options:
#   nrds, nrdp
#
# Example:
# handlers = nrds,ndrp
#
handlers = nrdp

#
# User and group to run passive checks as (Recommended to use nagios:nagios)
# Default: uid = nagios
# Default: gid = nagios
#
uid = nagios
gid = nagios

#
# Passive check interval - the amount in seconds to wait between each passive check by default,
# this can be overwritten by adding on a "|<duration>" in seconds to the passive check config
# Default: 300 (5 minutes)
#
sleep = 300

#
# Passive logging file level, location, and the PID location
# Default: loglevel = info (debug, info, warning, error)
# Default: logfile = var/log/ncpa_passive.log
# Default: pidfile = var/run/ncpa_passive.pid (leave passive in pid file name)
#
loglevel = info
logfile = var/log/ncpa_passive.log
pidfile = var/run/ncpa_passive.pid

#
# Delay passive checks from starting in seconds
# Default: 0
#
# delay_start = 30

#
# -------------------------------
# Passive Configuration (NRDP)
# -------------------------------
#

[nrdp]

#
# Connection settings to the NRDP server
# token = NRDP server token used to send NRDP results
# parent = NRDP server location (ex: http://<address>/nrdp)
#
parent =****
token =****

#
# The hostname that will replace %HOSTNAME% in the check definitions and will be
# sent to NRDP with the check name as the service description (service name)
#
hostname =****

#
# -------------------------------
# Passive Configuration (NRDS)
# -------------------------------
#

[nrds]

#
# NRDS CONFIGURATION DOES NOT WORK YET. MORE TO COME IN VERSION 2.1.0.
#

#
# NRDS connection information
#
url = 
token = 
config_name = 
config_version = 
update_config = 1
update_plugins = 1

#
# -------------------------------
# Plugin Configuration
# -------------------------------
#

[plugin directives]

#
# Plugin path where all plugins will be ran from.
#
plugin_path = plugins/

#
# Plugin execution timeout in seconds. Different than the check_ncpa.py timeout, which is
# normally for network connection issues. Will return a CRITICAL value and error when the plugin
# reaches the defined max execution timeout and kills the process.
# Default: 60
#
# plugin_timeout = 60

#
# Extensions for plugins
# ----------------------
# The extension for the plugin denotes how NCPA will try to run the plugin. Use this
# for setting how you want to run the plugin in the command line.
#
# Defaults:
# .sh = /bin/sh $plugin_name $plugin_args
# .ps1 = powershell -ExecutionPolicy Bypass -File $plugin_name $plugin_args
# .vbs = cscript $plugin_name $plugin_args //NoLogo
# .py = python $plugin_name $plugin_args
#
# Since windows NCPA is 32-bit, if you need to use 64-bit powershell, try the following for
# the powershell plugin definition:
# .ps1 = c:\windows\sysnative\windowspowershell\v1.0\powershell.exe -ExecutionPolicy Unrestricted -File $plugin_name $plugin_args
#
.sh = /bin/sh $plugin_name $plugin_args
.ps1 = powershell -ExecutionPolicy Bypass -File $plugin_name $plugin_args
.vbs = cscript $plugin_name $plugin_args //NoLogo
.py = python $plugin_name $plugin_args
```
Here's the content of passive.cfg (resides at /usr/local/ncpa/etc/ncpa.cfg.d/passive.cfg
```
[passive checks]
%HOSTNAME%|NCPA Listener Service = services --service ncpa_listener --status running
%HOSTNAME%|NCPA Listener Process = processes --name ncpa_passive --critical 1:1
%HOSTNAME%|APT = /plugins/negate/-w/OK/-s/'/usr/local/ncpa/plugins/check_apt'
```
Thanks for response btw :)

**Comment by jomann09** [comment]
Hmm interesting I guess I didn't read the bottom portion of your original version carefully enough, it looks like it isn't tracking the pid file and was already running when it was trying to start again... I don't know why that'd could systemctl to not be able to run it. However we are going to be adding a .service definition for system V in the next release (#349) so that should help address that.

It looks like it may not be able to read the config file when trying to run the second copy of ncpa, does it run fine once you start it the other way?

**Comment by acefreakz** [comment]
Hi jomann09, 

Ok, I wasn't looking into the pid file earlier. Somehow the problem gone away after i run `/etc/init.d/ncpa_passive stop`, make sure the pid file is gone, then run `systemctl restart ncpa_passive`, well now it's working... *facepalm*

Status output:
```
root@microsys-r610:/home/microsys# systemctl status ncpa_passive
â ncpa_passive.service - LSB: This manages the NCPA Passive service
   Loaded: loaded (/etc/init.d/ncpa_passive)
   Active: active (running) since Tue 2017-08-15 12:11:15 +08; 8s ago
  Process: 29230 ExecStop=/etc/init.d/ncpa_passive stop (code=exited, status=0/SUCCESS)
  Process: 29240 ExecStart=/etc/init.d/ncpa_passive start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/ncpa_passive.service
           ââ29248 /usr/local/ncpa/ncpa_passive --start

root@microsys-r610:/home/microsys# /etc/init.d/ncpa_passive status
NCPA Passive: Service is running. (pid 29248)
```

At the end, am not sure what has gone wrong. FML, have to assume it has something to do with the pid file. Thanks for assisting tho!

**Comment by omnitec** [comment]
Just had the same problem, .. tried 2.3 and 2.1, then back to 2.4. Seems like the critical step is to install and do nothing - the daemons are started automatically.

Copy over the correct files (ncpa.cfg, PassiveChecks.cfg, plugins, ..) and then a systemctl restart ncpa_ to read the new config and happiness occurs.
