### ISSUE TITLE
NCPA aix permission denied on samba share

### ISSUE THREAD

**Issue by metabsd** [NagiosEnterprises/ncpa#372]
Can you handle that please and add the message in the log
```
 ./ncpa_listener
Traceback (most recent call last):
  File "/opt/freeware/lib/python2.7/site-packages/cx_Freeze-4.3.4-py2.7-aix-6.1.egg/cx_Freeze/initscripts/Console.py", line 27, in <module>
  File "ncpa_listener.py", line 5, in <module>
  File "/tmp/test/ncpa/agent/ncpadaemon.py", line 14, in <module>
  File "/tmp/test/ncpa/agent/listener/database.py", line 5, in <module>
  File "/tmp/test/ncpa/agent/listener/server.py", line 11, in <module>
  File "/tmp/test/ncpa/agent/listener/psapi.py", line 213, in <module>
  File "/tmp/test/ncpa/agent/listener/psapi.py", line 184, in get_root_node
  File "/tmp/test/ncpa/agent/listener/psapi.py", line 153, in get_disk_node
  File "/tmp/test/ncpa/agent/listener/psapi.py", line 59, in make_mountpoint_nodes
OSError: [Errno 13] Permission denied: '/SERVERNAME/jde'
```

The mount point :
```
SERVERNAME/jde             /SERVERNAME/jde  cifs   Jun 29 08:20 uid=XXXX,gid=XXXX,fmode=755,wrkgrp=DOMAINNAME,noprompt,rw
```

The permission :
```
drwxr-xr-x    1 jde920   jde920        16384 Jun 29 08:20 jde
```

Other can read and execute.

**Comment by jomann09** [comment]
This will be fixed with #368 although the NFS shares will still show up for the time being.
