### ISSUE TITLE
NCPA 2.0.5 passive check ExpatError: syntax error: line 1, column 49

### ISSUE THREAD

**Issue by ddelmont** [NagiosEnterprises/ncpa#385]
Good day.

If this sounds familiar, it is. It's the same as reported in issue #331 expect the fix did not work in my case.

Client is RHEL 7.2 with NCPA version 2.0.5
Server is RHEL 7.3 with NRDP version 1.4.0, HTTP 2.4.6 and Nagios 4.3.4

I configured the client for NCPA passive check.: 
```
%HOSTNAME%|__HOST__ = system/agent_version
%HOSTNAME%|CPU Usage = cpu/percent --warning 60 --critical 80 --aggregate avg
%HOSTNAME%|Swap Usage = memory/swap --warning 60 --critical 80 --units Gi
%HOSTNAME%|Memory Usage = memory/virtual --warning 80 --critical 90 --units Gi
%HOSTNAME%|Process Count = processes --warning 300 --critical 400
```
Checking the file /usr/local/ncpa/var/log/ncpa_passive.log found error below:

From log:
```
2017-09-24 19:30:44,745 9746 INFO started
2017-09-24 19:30:44,752 9746 INFO Delayed start in configuration. Waiting 15 seconds to start.
2017-09-24 19:30:59,768 9746 INFO Running check: system/agent_version
2017-09-24 19:30:59,792 9746 INFO Did not receive normal values. Unable to find meaningful check.
2017-09-24 19:30:59,795 9746 INFO Running check: cpu/percent --warning 60 --critical 80 --aggregate avg
2017-09-24 19:31:00,816 9746 INFO Running check: memory/swap --warning 60 --critical 80 --units Gi
2017-09-24 19:31:00,837 9746 INFO Running check: memory/virtual --warning 80 --critical 90 --units Gi
2017-09-24 19:31:00,856 9746 INFO Running check: processes --warning 300 --critical 400
2017-09-24 19:31:01,345 9746 ERROR syntax error: line 1, column 49
Traceback (most recent call last):
  File "ncpa_passive.py", line 45, in run_all_handlers
  File "/root/ncpa/agent/passive/nrdp.py", line 124, in run
  File "/root/ncpa/agent/passive/nrdp.py", line 179, in submit_to_nagios
  File "/root/ncpa/agent/passive/nrdp.py", line 145, in log_result
  File "/usr/local/lib/python2.7/xml/dom/minidom.py", line 1928, in parseString
  File "/usr/local/lib/python2.7/xml/dom/expatbuilder.py", line 940, in parseString
  File "/usr/local/lib/python2.7/xml/dom/expatbuilder.py", line 223, in parseString
ExpatError: syntax error: line 1, column 49
```
/etc/httpd/conf.d/nrdp.conf (the fix reported in #331 is in place):
```
#  SSLRequireSSL
   Options None
   AllowOverride None
   Require all granted
#   Order allow,deny
#   Allow from all
#  Order deny,allow
#  Deny from all
#  Allow from 127.0.0.1
#   AuthName "NRDP"
#   AuthType Basic
#   AuthUserFile /usr/local/nrdp/htpasswd.users
#  Require valid-user
Require all granted
</Directory>

Alias /nrdp "/usr/local/nagios/share/nrdp/server"
```

TCPDUMP:
```
Host: XX.XX.XXX.226
Connection: keep-alive
Accept-Encoding: gzip, deflate
Accept: */*
User-Agent: python-requests/2.18.4
Content-Length: 1705
Content-Type: application/x-www-form-urlencoded

token=token&cmd=submitcheck&XMLDATA=%3C%3Fxml+version%3D%221.0%22+%3F%3E%3Ccheckresults%3E%3Ccheckresult+type%3D%22host%22%3E%3Chostname%3Esoclab-rh7%3C%2Fhostname%3E%3Cstate%3E0%3C%2Fstate%3E%3Coutput%3EOK%3A+Agent_version+was+%5B%272.0.5%27%5D%3C%2Foutput%3E%3C%2Fcheckresult%3E%3Ccheckresult+type%3D%22service%22%3E%3Cservicename%3ECPU+Usage%3C%2Fservicename%3E%3Chostname%3Esoclab-rh7%3C%2Fhostname%3E%3Cstate%3E0%3C%2Fstate%3E%3Coutput%3EOK%3A+Percent+was+0.50+%25+%7C+%27percent%27%3D0.50%25%3B60%3B80%3B%3C%2Foutput%3E%3C%2Fcheckresult%3E%3Ccheckresult+type%3D%22service%22%3E%3Cservicename%3ESwap+Usage%3C%2Fservicename%3E%3Chostname%3Esoclab-rh7%3C%2Fhostname%3E%3Cstate%3E0%3C%2Fstate%3E%3Coutput%3EOK%3A+Used+swap+was+0.00+%25+%28Total%3A+2.00+GiB%2C+Used%3A+0.00+GiB%2C+Free%3A+2.00+GiB%29+%7C+%27percent%27%3D0.00%25%3B60%3B80%3B%3C%2Foutput%3E%3C%2Fcheckresult%3E%3Ccheckresult+type%3D%22service%22%3E%3Cservicename%3EMemory+Usage%3C%2Fservicename%3E%3Chostname%3Esoclab-rh7%3C%2Fhostname%3E%3Cstate%3E0%3C%2Fstate%3E%3Coutput%3EOK%3A+Used+memory+was+26.00+%25+%28Available%3A+4.20+GiB%2C+................
19:07:28.599433 IP soclab-rh7.45834 > x.x.x.226.http: Flags [P.], seq 1461:1927, ack 1, win 29200, length 466
E....s@.@.n..]...@...
.P..>.....P.r..b..Total%3A+5.67+GiB%2C+Free%3A+2.17+GiB%2C+Used%3A+0.94+GiB%29+%7C+%27percent%27%3D26.00%25%3B80%3B90%3B%3C%2Foutput%3E%3C%2Fcheckresult%3E%3Ccheckresult+type%3D%22service%22%3E%3Cservicename%3EProcess+Count%3C%2Fservicename%3E%3Chostname%3Esoclab-rh7%3C%2Fhostname%3E%3Cstate%3E0%3C%2Fstate%3E%3Coutput%3EOK%3A+Process+count+was+208+%7C+%27process_count%27%3D208%3B300%3B400%3B%3C%2Foutput%3E%3C%2Fcheckresult%3E%3C%2Fcheckresults%3E................
19:07:28.602149 IP XX.XX.XXX.226.http > soclab-rh7.45834: Flags [.], ack 1, win 29200, options [nop,nop,nop,nop], length 0
E..,..@.;.nV.@...]...P.
......9-`.r.k.......oS................
19:07:28.602595 IP XX.XX.XXX.226.http > soclab-rh7.45834: Flags [.], ack 1927, win 32742, length 0
E..(.0@.<..).@...]...P.
......@.P...h-........................
19:07:28.603119 IP XX.XX.XXX.226.http > soclab-rh7.45834: Flags [P.], seq 1:677, ack 1927, win 32742, length 676
E....1@.<....@...]...P.
...HTTP/1.1 401 Unauthorized
Date: Sun, 24 Sep 2017 19:21:47 GMT
Server: Apache/2.4.6 (Red Hat Enterprise Linux) PHP/5.4.16
WWW-Authenticate: Basic realm="Nagios Access"
Content-Length: 381
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: text/html; charset=iso-8859-1

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>401 Unauthorized</title>
</head><body>
<h1>Unauthorized</h1>
<p>This server could not verify that you
are authorized to access the document
requested.  Either you supplied the wrong
credentials (e.g., bad password), or your
browser doesn't understand how to supply
the credentials required.</p>
</body></html>
```

I set the tokens to match and to a very simple string to test:
```
parent = http://XX.XX.XXX.226/nrdp
token = token
```
and:
```
$cfg['authorized_tokens'] = array(
        "token"
        );
```
Tokens work if entered at http://XX.XX.XXX.226/nrdp page and curl to client.

Thanks,
Diana

**Comment by jomann09** [comment]
It looks like from your error that is being returned, you have apache configured somehow to force basic auth required, even on the NRDP url. Your tcpdump is showing `WWW-Authenticate: Basic realm="Nagios Access"` which shouldn't be required for the nrdp endpoint.

**Comment by ddelmont** [comment]
Thanks.  I’ll investigate that.

**Comment by ddelmont** [comment]
Thanks for the quick response.  Basic Authentication is set to off in the NRDP config.inc.php file.

```
// Do we require that basic authentication be used to access NRDP?
// set this value to 'false' to disable basic auth requirement
$cfg["require_basic_auth"] = false;
```

But set to on for the /usr/local/nagios/share directory in the /etc/httpd/conf.d/nagios.conf file.

```
<Directory "/usr/local/nagios/share">
   Options None
   AllowOverride None
      <IfVersion >= 2.3>
         <RequireAll>
            Require all granted
            AuthName "Nagios Access"
            AuthType Basic
            AuthUserFile /usr/local/nagios/etc/htpasswd.users
            Require valid-user
         </RequireAll>
      </IfVersion>
      <IfVersion < 2.3>
         Order allow,deny
         Allow from all
         AuthName "Nagios Access"
         AuthType Basic
         AuthUserFile /usr/local/nagios/etc/htpasswd.users
         Require valid-user
      </IfVersion>
</Directory>

```

I added to the bottom of the file to disable it:

```
<Directory "/usr/local/nagios/share/nrdp/server">
   Satisfy Any
<\/Directory>
```

This resolved the issue.  Not sure how it got set either.  It was a clean install.  Must be an issue with the specific install directions I followed.  Thanks again.

**Comment by jomann09** [comment]
Glad you got it working!
