### ISSUE TITLE
Multiple Firefox connections to websocket create error

### ISSUE THREAD

**Issue by jomann09** [NagiosEnterprises/ncpa#392]
When you're connected to the NCPA websocket (on a Windows NCPA install) from multiple Firefox browsers the websocket throws an error and disconnects/drops the socket connection.

```
2017-10-05 16:25:34,882:ERROR:app:Exception on /ws/top [GET]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\ncpa\agent\listener\server.py", line 154, in token_auth_decoration
  File "C:\ncpa\agent\listener\server.py", line 667, in top_websocket
  File "C:\Python27\lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa0 in position 979: invalid start byte
```

**Comment by jomann09** [comment]
Fixed in ee8745e273cd17a9867fa3be1ee48b1ceb371dd7 by setting encoding using `sys.stdin.encoding`
