### ISSUE TITLE
v2.0.5 python error argument 1 must be string, not unicode

### ISSUE THREAD

**Issue by gregwalters** [NagiosEnterprises/ncpa#397]
After upgrading some Windows servers from 2.0.2 to 2.0.5 I see this error in the win32service_ncpalistener (and passive) log file:

```
[18788] 2017/10/23 11:01:13.077 starting logging at level ERROR
[18788] 2017/10/23 11:01:13.327 Python exception encountered:
[18788] 2017/10/23 11:01:13.327     Internal Message: cannot import service module
[18788] 2017/10/23 11:01:13.327     Type => <type 'exceptions.TypeError'>
[18788] 2017/10/23 11:01:13.327     Value => LoadLibrary() argument 1 must be string, not unicode
[18788] 2017/10/23 11:01:13.342     Traceback (most recent call last):

[18788] 2017/10/23 11:01:13.342       File "C:\ncpa\agent\ncpa_windows.py", line 15, in <module>

[18788] 2017/10/23 11:01:13.342       File "C:\ncpa\agent\passive\nrds.py", line 4, in <module>

[18788] 2017/10/23 11:01:13.342       File "C:\ncpa\agent\listener\server.py", line 10, in <module>

[18788] 2017/10/23 11:01:13.342       File "C:\Python27\lib\site-packages\requests\__init__.py", line 84, in <module>

[18788] 2017/10/23 11:01:13.342       File "C:\Python27\lib\site-packages\urllib3\contrib\pyopenssl.py", line 46, in <module>

[18788] 2017/10/23 11:01:13.342       File "C:\Python27\lib\site-packages\OpenSSL\__init__.py", line 8, in <module>

[18788] 2017/10/23 11:01:13.342       File "C:\Python27\lib\site-packages\OpenSSL\crypto.py", line 12, in <module>

[18788] 2017/10/23 11:01:13.342       File "C:\Python27\lib\site-packages\cryptography\x509\__init__.py", line 9, in <module>

[18788] 2017/10/23 11:01:13.342       File "C:\Python27\lib\site-packages\cryptography\x509\base.py", line 16, in <module>

[18788] 2017/10/23 11:01:13.342       File "C:\Python27\lib\site-packages\cryptography\x509\extensions.py", line 13, in <module>

[18788] 2017/10/23 11:01:13.342       File "C:\Python27\lib\site-packages\asn1crypto\keys.py", line 22, in <module>

[18788] 2017/10/23 11:01:13.342       File "C:\Python27\lib\site-packages\asn1crypto\_elliptic_curve.py", line 51, in <module>

[18788] 2017/10/23 11:01:13.342       File "C:\Python27\lib\site-packages\asn1crypto\_int.py", line 56, in <module>

[18788] 2017/10/23 11:01:13.342       File "C:\Python27\lib\site-packages\asn1crypto\_perf\_big_num_ctypes.py", line 35, in <module>

[18788] 2017/10/23 11:01:13.342       File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__

[18788] 2017/10/23 11:01:13.342     TypeError: LoadLibrary() argument 1 must be string, not unicode
```

**Comment by jomann09** [comment]
What version of Windows are these running on?

**Comment by gregwalters** [comment]
Should have included that, sorry for the obvious omission. These servers are 2008 Server R2.

**Comment by jomann09** [comment]
Quick search looks like this might be an issue in python iteself, which seems odd that I haven't seen this issue running this on Windows myself. I will double check on a Windows Server 2008 R2 and see if I can't re-create it. Either way I would suggest switching back to the version that worked for the time being and 2.0.6 should be out shortly with Python 2.7.14, which "should" fix this.

**Comment by jomann09** [comment]
https://bugs.python.org/issue29082

There is also a fix we could do manually but the upgrade should take care of it for us.

**Comment by gregwalters** [comment]
I'll keep an eye out for 2.0.6. Thanks for the quick responses.

**Comment by jomann09** [comment]
Closing this since updated the Python source to 2.7.14 so 2.0.6 should solve this.
