### ISSUE TITLE
AIX plugin execution error 500

### ISSUE THREAD

**Issue by metabsd** [NagiosEnterprises/ncpa#407]
Hi,

We try to use NCPA to run a custom script to monitor something in house.

The script return that result.
```
nagios@servername:/usr/local/ncpa/plugins$ ./check_jde_porttest
OK: JDEPORT Porttest JDE 9.2 fonctionnel !
```

We have to wrap that because of the legacy stuff.

check_jde_porttest
```
sudo -u username -i /jde/nagios/jde_check_porttest > /usr/local/ncpa/plugins/check_jde_porttest.log

grep JDEPORT /usr/local/ncpa/plugins/check_jde_porttest.log | read LIGNE_RC

if [ -n $LIGNE_RC ]; then
    echo "$LIGNE_RC"
else
    echo "JDEPORT Critical: Porttest script non fonctionnel"
fi
```

Error log in ncpa_listener.log

```
2017-12-12 15:39:01,122 4194648 ERROR Exception on /api/plugins/check_jde_porttest [GET]
Traceback (most recent call last):
  File "/opt/freeware/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
  File "/opt/freeware/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
  File "/opt/freeware/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
  File "/opt/freeware/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
  File "/opt/freeware/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
  File "/tmp/test/ncpa/agent/listener/server.py", line 154, in token_auth_decoration
  File "/tmp/test/ncpa/agent/listener/server.py", line 933, in api
  File "/tmp/test/ncpa/agent/listener/pluginnodes.py", line 42, in walk
  File "/tmp/test/ncpa/agent/listener/pluginnodes.py", line 99, in execute_plugin
  File "/opt/freeware/lib/python2.7/site-packages/gevent/subprocess.py", line 585, in __init__
  File "/opt/freeware/lib/python2.7/site-packages/gevent/subprocess.py", line 554, in __init__
  File "/opt/freeware/lib/python2.7/site-packages/gevent/subprocess.py", line 1312, in _execute_child
OSError: [Errno 8] Exec format error
2017-12-12 15:39:01,130 4194648 INFO 172.21.1.12 - - [2017-12-12 15:39:01] "GET /api/plugins/check_jde_porttest HTTP/1.1" 500 3980 0.053573
```

**Comment by jomann09** [comment]
Does your script have the `#!` line at the top? It looks like that is the most common issue, it isn't in your example, but by default if you look in the `ncpa.cfg` you can specify extensions, but if there is no extension given it is just ran in Python using popen. I am assuming it's not using the correct shell.

**Comment by metabsd** [comment]
Thank you!!! Work fine now 👍 @jomann09 👍
