### ISSUE TITLE
Adding multilple nrdp parents

### ISSUE THREAD

**Issue by karatalapu80** [NagiosEnterprises/ncpa#409]
Hi there;

This is more of a question.

Is there a way I can add multiple nrdp parents to the client?

if yes what is the syntax I need to use. I added two nrdp parents separated by comma (enclosed below). This does not seem to work.

parent = http://XXXX/nrdp/,http://XXXX/nrdp/
token = mytoken

-Krishna

**Comment by karatalapu80** [comment]
This is the error I am seeing in passive log

2017-12-14 23:39:46,078 13734 INFO Running check: plugins/check_serverConn.py
2017-12-14 23:39:46,170 13734 INFO Running check: plugins/check_file.pl -e /bin/bash
2017-12-14 23:39:46,198 13734 ERROR syntax error: line 1, column 49
Traceback (most recent call last):
  File "ncpa_passive.py", line 45, in run_all_handlers
  File "/root/ncpa/agent/passive/nrdp.py", line 124, in run
  File "/root/ncpa/agent/passive/nrdp.py", line 179, in submit_to_nagios
  File "/root/ncpa/agent/passive/nrdp.py", line 145, in log_result
  File "/usr/local/lib/python2.7/xml/dom/minidom.py", line 1928, in parseString
  File "/usr/local/lib/python2.7/xml/dom/expatbuilder.py", line 940, in parseString
  File "/usr/local/lib/python2.7/xml/dom/expatbuilder.py", line 223, in parseString
ExpatError: syntax error: line 1, column 49

**Comment by jomann09** [comment]
There is currently no way to add multiple NRDP parents. I can add this as an enhancement that we can possibly get into 2.1, if not in that one, the next release.

It shouldn't be too hard, we just need a sane way to define them.

**Comment by karatalapu80** [comment]
Thank you 

Do you know when will version 2.1 be real released ?

-Krishna

**Comment by jomann09** [comment]
We are planning to release it early this coming week!

**Comment by jomann09** [comment]
This is added in 73058bb3875ca0e863a225cf0cc24e6e5da7c957

**Comment by karatalapu80** [comment]
Great thank you !!!
