### ISSUE TITLE
 ERROR HTTPSConnectionPool(host='nagios', port=443): Max retries exceeded with url: /nrdp/

### ISSUE THREAD

**Issue by pilot513** [NagiosEnterprises/ncpa#413]
Hello. i'm reopened 
https://github.com/NagiosEnterprises/ncpa/issues/412#issuecomment-353837157

The problem is manifested.
I have two absolutely identical passive checks. Only the names are different. On the last one I get an error. The first works fine. It seems there are limits somewhere?
```
%HOSTNAME%|Tomcat.ThreadCount = plugins/check_jmx/-U/"service:jmx:rmi:///jndi/rmi://localhost:5670/jmxrmi"/-O/"java.lang:type=Threading"/-A/ThreadCount/-w/300/-c/500/-username/nagiosmon/-password/<password>/
```
```
%HOSTNAME%|Tomcat.ThreadCount2 = plugins/check_jmx/-U/"service:jmx:rmi:///jndi/rmi://localhost:5670/jmxrmi"/-O/"java.lang:type=Threading"/-A/ThreadCount/-w/300/-c/500/-username/nagiosmon/-password/<password>/
```
```
2017-12-26 14:27:41,156 109635 ERROR HTTPSConnectionPool(host='10.97.141.22', port=443): Max retries exceeded with url: /nrdp/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7ba5682890>: Failed to establish a new connection: [Errno 111] Connection refused',))
Traceback (most recent call last):
  File "ncpa_passive.py", line 45, in run_all_handlers
  File "/root/ncpa/agent/passive/nrdp.py", line 124, in run
  File "/root/ncpa/agent/passive/nrdp.py", line 178, in submit_to_nagios
  File "/root/ncpa/agent/passive/utils.py", line 13, in send_request
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 112, in post
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 58, in request
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
ConnectionError: HTTPSConnectionPool(host='10.97.141.22', port=443): Max retries exceeded with url: /nrdp/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7ba5682890>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

**Comment by pilot513** [comment]
Maybe it's the limits on Apache24's side?
In httpd.conf i set:
<IfModule mpm_prefork_module>
        ServerLimit         1024
        StartServers          10
        MinSpareServers       20
        MaxSpareServers       40
        MaxClients           512
        MaxRequestsPerChild 4500
</IfModule>

**Comment by pilot513** [comment]
The problem not new.  
Example: `https://github.com/kubernetes-incubator/client-python/issues/385`

**Comment by pilot513** [comment]
It's a python bug ?!

**Comment by pilot513** [comment]
I'm switch apache24 form mod_mpm_prefork.so to mod_mpm_worker.so
And set: /etc/httpd/conf.modules.d/10-worker.conf

`<IfModule mpm_worker_module>
    ServerLimit             512
    StartServers             32
    MinSpareThreads          75
    MaxSpareThreads         250
    ThreadLimit              64
    ThreadsPerChild          32
    MaxClients             8000
    MaxRequestsPerChild   10000
</IfModule>`

**no result**

`2017-12-26 15:20:38,508 121271 ERROR HTTPSConnectionPool(host='10.97.141.22', port=443): Max retries exceeded with url: /nrdp/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f6447e8ba50>: Failed to establish a new connection: [Errno 111] Connection refused',))
Traceback (most recent call last):
  File "ncpa_passive.py", line 45, in run_all_handlers
  File "/root/ncpa/agent/passive/nrdp.py", line 124, in run
  File "/root/ncpa/agent/passive/nrdp.py", line 178, in submit_to_nagios
  File "/root/ncpa/agent/passive/utils.py", line 13, in send_request
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 112, in post
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 58, in request
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
ConnectionError: HTTPSConnectionPool(host='10.97.141.22', port=443): Max retries exceeded with url: /nrdp/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f6447e8ba50>: Failed to establish a new connection: [Errno 111] Connection refused',))`

**Comment by pilot513** [comment]
https://stackoverflow.com/questions/37763510/connectionerror-max-retries-exceeded-with-url-caused-by-none

**Comment by jomann09** [comment]
From reading requests own issues here https://github.com/requests/requests/issues/1198 it looks like the issue you are having is actually the `urllib3` error, `Failed to establish a new connection: [Errno 111] Connection refused` which I would not know why your Apache is not allowing new connections. I'm not familiar with mpm setups for Apache either.

**Comment by pilot513** [comment]
resolved. Thanks!

**Comment by veereshgs** [comment]
> From reading requests own issues here [psf/requests#1198](https://github.com/psf/requests/issues/1198) it looks like the issue you are having is actually the `urllib3` error, `Failed to establish a new connection: [Errno 111] Connection refused` which I would not know why your Apache is not allowing new connections. I'm not familiar with mpm setups for Apache either.

**Comment by AdamRussak** [comment]
hi, I know the issue is closed, but I didn't understand how it was fixed?
- the https/fqdn/nrdp workes (and the Nagios too).
- got an NCPA sending NRDP passive checks 
`ConnectionError: HTTPSConnectionPool(host='<FQDN>', port=443): Max retries exceeded with url: /nrdp/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x026D9550>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))`

tnx for the help :)
