### ISSUE TITLE
CentOS 7.4 - NCPA 2.1.1/2.1.2 - ERROR Exception on /ws/top

### ISSUE THREAD

**Issue by soxfor** [NagiosEnterprises/ncpa#419]
Similar to #392 , after upgrading from NCPA 2.0.6 to 2.1.1, there's no graphing and when accessing the Top Processes the info below is logged on ncpa_listener.log.

Installed 2.1.2 available at https://assets.nagios.com/downloads/ncpa/dev/ncpa-2.1.2.el7.x86_64.rpm after looking at this commit 0a5e95c97de8b71d40aafdd1d2f11e821b0d3923 but the issue remains.

Tried on Waterfox/Firefox and Chromium.

```
2018-01-05 10:37:21,578 32226 ERROR Exception on /ws/top [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
  File "/root/ncpa/agent/listener/server.py", line 168, in token_auth_decoration
  File "/root/ncpa/agent/listener/server.py", line 678, in top_websocket
  File "/usr/local/lib/python2.7/json/__init__.py", line 251, in dumps
  File "/usr/local/lib/python2.7/json/encoder.py", line 207, in encode
  File "/usr/local/lib/python2.7/json/encoder.py", line 270, in iterencode
  File "/usr/local/lib/python2.7/json/encoder.py", line 233, in _encoder
TypeError: decode() argument 1 must be string, not None
```
OS: CentOS Linux release 7.4.1708 (Core)

**Comment by CSimpiFoN** [comment]
Experiencing the same problem on the same operating system.

**Comment by jomann09** [comment]
That dev version should have fixed it but I can't remember if it was build before or after that commit. I will test it again and re-build if I can get it working properly today.

**Comment by soxfor** [comment]
@jomann09 thanks. By checking the files inside the .rpm, modified date is 29/Dec/2017 22H17, the commit is from 21H47 GMT, I guess the fix didn't make it. 😄

**Comment by jomann09** [comment]
Okay, I rebuilt it and tested it, should work if you'd like to use it for now: https://assets.nagios.com/downloads/ncpa/dev/ncpa-2.1.2.el7.x86_64.rpm

**Comment by soxfor** [comment]
@jomann09 thanks. Installed, it's working. :)

**Comment by CSimpiFoN** [comment]
This is working as expected. Thank you very much! When will this go to NagiosXI repository?

**Comment by jomann09** [comment]
Should be out at the end of the week, there's a couple other things I want to get fixed before it is released.

Thanks for testing and confirming!
