### ISSUE TITLE
ncpa 2.1.1 - HTTP Error 500: INTERNAL SERVER ERROR

### ISSUE THREAD

**Issue by numj** [NagiosEnterprises/ncpa#421]
I upgraded my NCPA client from 2.0.5 to 2.1.1.  I'm now getting the following error when doing API checks that were previously working : 

_$ /usr/local/nagios/libexec/check_ncpa.py -H ctelqcd001 -t 'xxx' -P 5693 -M 'windowscounters/DirectoryServices(*)/LDAP Searches/sec' -w 1000 -c 2000 -q 'sleep=5' -v
Connecting to: https://ctelqcd001:5693/api/windowscounters/DirectoryServices%28%2A%29/LDAP%20Searches/sec/?token=xxx&warning=1000&critical=2000&check=1&sleep=5_
**An error occurred:HTTP Error 500: INTERNAL SERVER ERROR**

Here's a portion of the ncpa_listener.log file : 

2018-01-08 13:09:21,571:INFO:handler:172.26.14.250 - - [2018-01-08 13:09:21] "GET /api/windowscounters/DirectoryServices%28%2A%29/LDAP%20Client%20Sessions/?token=qAGq42xVkzE2uSvxp6fgCr4fT44WASHA&warning=1111&critical=1112&check=1 HTTP/1.1" 500 2362 1.203000
2018-01-08 13:09:35,180:DEBUG:handler:Initializing WebSocket
2018-01-08 13:09:35,180:DEBUG:handler:Validating WebSocket request
2018-01-08 13:09:36,384:DEBUG:psapi:Imported windowscounters into the API tree.
2018-01-08 13:09:36,384:DEBUG:psapi:Imported windowslogs into the API tree.
2018-01-08 13:09:36,384:ERROR:app:Exception on /api/windowscounters/DirectoryServices(*)/LDAP Searches/sec/ [GET]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
  File "C:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
  File "C:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
  File "C:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
  File "C:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
  File "C:\Users\jomann\Documents\ncpa\agent\listener\server.py", line 168, in token_auth_decoration
  File "C:\Users\jomann\Documents\ncpa\agent\listener\server.py", line 896, in api
  File "C:\Users\jomann\Documents\ncpa\agent\listener\psapi.py", line 272, in getter
  File "C:\Users\jomann\Documents\ncpa\agent\listener\nodes.py", line 55, in accessor
TypeError: accessor() takes exactly 4 arguments (5 given)

**Comment by jomann09** [comment]
It looks like the update didn't happen for the windowscounters node, so I just fixed that in 1553c446b03b7ba11cf0d0a5ae1de635e3cf9a5a and we will be releasing 2.1.2 soon.
