### ISSUE TITLE
AIX memory swap bad result

### ISSUE THREAD

**Issue by metabsd** [NagiosEnterprises/ncpa#428]
Hi,

I just noticed that the NCPA agent on AIX does not return the correct SWAP information.

`https://servername:5693/api/memory/swap?units=Mi`

`{ "swap": { "total": [ 4.37, "MiB" ], "percent": [ 0.1, "%" ], "free": [ 4.37, "MiB" ], "used": [ 0, "MiB" ] } }`

Agent Information

`{ "system": { "node": "servername", "machine": "00FA1A814C00", "uptime": [ 96140, "s" ], "version": "7", "time": 1517424780.427929, "release": "2", "timezone": [ "EST", "EDT" ], "agent_version": "2.0.4", "system": "AIX", "processor": "powerpc" } }`

Thank you!

**Comment by jomann09** [comment]
Can you give me the actual swap usage from the command line too? It'll take a look at this.

**Comment by metabsd** [comment]
I just update the agent to 2.1.1 and it's working fine.

`{ "system": { "node": "servername", "machine": "00FA1A814C00", "uptime": [ 97719, "s" ], "version": "7", "time": 1517426359.894035, "release": "2", "timezone": [ "EST", "EDT" ], "agent_version": "2.1.1", "system": "AIX", "processor": "powerpc" } }`

I don't find the service or the entry in inittab and I don't understand how NCPA version 2.1.1 will start by itself during the next reboot of the server.

**Comment by metabsd** [comment]
Now I don't have access to services and processes.

`{ "root": { "services": [], "processes": [],`

**Comment by jomann09** [comment]
When you're in the root API endpoint I don't think it expands the services and processes, but I'm not 100% certain. The inittab shouldn't have changed, although since you moved from 2.0.4 to 2.1.1 you may have been on that version that had the wrong uninit in the RPM so you may have to manually add it. I can give you the command.

**Comment by metabsd** [comment]
Yes please share the command. I also try to use those link.

`https://servername:5693/api/processes`
`https://servername:5693/api/services`

I never see return from NCPA.

**Comment by jomann09** [comment]
Hmm I just tested those two api endpoints on the test system I build it on and it is giving me processes and services using the api endpoints you're giving me. Can you check the ncpa_listener.log and see if there is anything in there that could be the issue?

The inittab commands are as follows:
```
mkitab "ncpa_listener:2:once:/usr/bin/startsrc -e LIBPATH=$RPM_INSTALL_PREFIX/ncpa -s ncpa_listener >/dev/null 2>&1"
    mkitab "ncpa_passive:2:once:/usr/bin/startsrc -e LIBPATH=$RPM_INSTALL_PREFIX/ncpa -s ncpa_passive >/dev/null 2>&1"
```

**Comment by metabsd** [comment]
`LIBPATH=$RPM_INSTALL_PREFIX/ncpa == LIBPATH=/usr/local/ncpa`
???
`mkitab "ncpa_listener:2:once:/usr/bin/startsrc -e LIBPATH=/usr/local/ncpa -s ncpa_listener >/dev/null 2>&1"
    mkitab "ncpa_passive:2:once:/usr/bin/startsrc -e LIBPATH=/usr/local/ncpa -s ncpa_passive >/dev/null 2>&1"`

**Comment by metabsd** [comment]
Do you have a workaround for processes and processes ?

**Comment by jomann09** [comment]
Yes sorry you're right I updated it. I am not sure why you're not seeing it, can you look at `/usr/local/ncpa/var/log/ncpa_listener.log` and see if there are any errors when you got to the services or processes sections?

**Comment by metabsd** [comment]
Hi Jake,

This is the content of ncpa_listener.log about Services/Process/Network Int
```
2018-01-31 14:29:34,322 9240868 ERROR Exception on /api/processes [GET]
Traceback (most recent call last):
  File "/opt/freeware/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
  File "/opt/freeware/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
  File "/opt/freeware/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
  File "/opt/freeware/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
  File "/opt/freeware/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
  File "/tmp/test/ncpa/agent/listener/server.py", line 168, in token_auth_decoration
  File "/tmp/test/ncpa/agent/listener/server.py", line 913, in api
  File "/tmp/test/ncpa/agent/listener/processes.py", line 336, in walk
  File "/tmp/test/ncpa/agent/listener/processes.py", line 308, in get_process_dict
  File "/opt/freeware/lib/python2.7/tempfile.py", line 511, in TemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags)
  File "/opt/freeware/lib/python2.7/tempfile.py", line 244, in _mkstemp_inner
    fd = _os.open(file, flags, 0600)
OSError: [Errno 13] Permission denied: '/tmp/tmpln0H9W'
2018-01-31 14:29:34,327 9240868 INFO 172.26.45.81 - - [2018-01-31 14:29:34] "GET /api/processes HTTP/1.1" 500 3980 0.012741
```
```
2018-01-31 14:30:44,431 9240868 ERROR Exception on /api/services [GET]
Traceback (most recent call last):
  File "/opt/freeware/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
  File "/opt/freeware/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
  File "/opt/freeware/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
  File "/opt/freeware/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
  File "/opt/freeware/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
  File "/tmp/test/ncpa/agent/listener/server.py", line 168, in token_auth_decoration
  File "/tmp/test/ncpa/agent/listener/server.py", line 913, in api
  File "/tmp/test/ncpa/agent/listener/services.py", line 276, in walk
  File "/tmp/test/ncpa/agent/listener/services.py", line 20, in wrapper
  File "/tmp/test/ncpa/agent/listener/services.py", line 252, in get_services_via_lssrc
  File "/opt/freeware/lib/python2.7/tempfile.py", line 511, in TemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags)
  File "/opt/freeware/lib/python2.7/tempfile.py", line 244, in _mkstemp_inner
    fd = _os.open(file, flags, 0600)
OSError: [Errno 13] Permission denied: '/tmp/tmpknLrPW'
```
```
2018-01-31 14:37:59,349 9240868 ERROR Exception on /api/interface/en0/bytes_recv/ [GET]
Traceback (most recent call last):
  File "/opt/freeware/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
  File "/opt/freeware/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
  File "/opt/freeware/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
  File "/opt/freeware/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
  File "/opt/freeware/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
  File "/tmp/test/ncpa/agent/listener/server.py", line 168, in token_auth_decoration
  File "/tmp/test/ncpa/agent/listener/server.py", line 911, in api
  File "/tmp/test/ncpa/agent/listener/nodes.py", line 273, in run_check
  File "/tmp/test/ncpa/agent/listener/nodes.py", line 196, in get_delta_values
  File "/tmp/test/ncpa/agent/listener/nodes.py", line 439, in deltaize_values
IOError: [Errno 13] Permission denied: '/tmp/ncpa-1565530400.tmp'
```
This is the detail about `/tmp`
mount
`/dev/hd3         /tmp             jfs2   Jan 30 11:09 rw,log=/dev/hd8`
`ls -al /tmp`
`drwxr-xr-x   43 root     system         4096 Jan 31 15:45 tmp`

NCPA run as nagios
`
/usr/local/ncpa/var/log# ps -ef | grep ncpa
  nagios  8847636  4456706   0 14:15:53      -  0:00 /usr/local/ncpa/ncpa_passive -n
  nagios  9240868  4456706   0 14:15:53      -  0:07 /usr/local/ncpa/ncpa_listener -n
`

**Comment by metabsd** [comment]
Do you think it's a good idea to use your own `/usr/local/ncpa/tmp` temp folder? I will open `/tmp/` for the moment to see if it's fix the problem.

**Comment by metabsd** [comment]
Are you still using the AIX server we provided to compile NCPA versions?

**Comment by metabsd** [comment]
I confirm chmod 777 /tmp fix the problem.

**Comment by jomann09** [comment]
Oh that is good, is it typical that things can't write to the `/tmp` directory on AIX? If that is so, we can possibly get it to use a local temp directory in the ncpa folder instead.

**Comment by metabsd** [comment]
I make sure with the other member of the AIX team and we normaly can write in the /tmp folder...
No need to change your code 👍

**Comment by metabsd** [comment]
@jomann09 Are you still using the AIX server we provided to compile NCPA versions?

**Comment by jomann09** [comment]
Yeah that is what I have been using, if you need it that's fine, but that setup is where I have been building them. I have most of the installation and setup for the dev environment saved so I can set it up again any time.

**Comment by metabsd** [comment]
@jomann09 We plan to move from perlz rpm repo to ibmtoolbox. Do you think you have to retest your stuff ? Make sure you have backup because we plan to reinstall the server with ibmtoolbox rpm.

**Comment by jomann09** [comment]
You should be fine, it shouldn't affect it as long as we can get access to python and the couple things we installed from perlz. It should not affect the built NCPA rpms either since they should run no matter what.

**Comment by jomann09** [comment]
From my notes:

```
Install gcc
Install requirements for python (zlib, zlib-devel, sqlite, sqlite-devel)
Install xlc
Install python2.7.x
Install python-devel and python-libs
```

gcc is only needed for gevent building, although they may have fixed it to work with xlc by now.

**Comment by metabsd** [comment]
I will contact you when we finish. We just find a bug with perlz repo and AIX. It's like perlz and AIX TL update is incompatible. We choose to switch to the official rpm repo of IBM. A year ago that repo is really bad but now it's seem to be more active.

**Comment by jomann09** [comment]
Okay thanks! I have looked at the ibmtoolbox packages in the past and I am pretty sure they have everything we need so it should be able to build it.

**Comment by metabsd** [comment]
The inittab is not working.

/usr/bin/startsrc -e LIBPATH=/usr/local/ncpa -s ncpa_listener
0513-085 The ncpa_listener Subsystem is not on file.

I think something is missing.

**Comment by jomann09** [comment]
You must be missing the src commands, you can run this to add them
```
mkssys -s ncpa_listener -p /usr/local/ncpa/ncpa_listener -u 0 -S -n 15 -f 9 -a '-n'
mkssys -s ncpa_passive -p /usr/local/ncpa/ncpa_passive -u 0 -S -n 15 -f 9 -a '-n'
```

**Comment by jomann09** [comment]
I was trying to build NCPA 2.1.2 on the AIX box and it looks like it was reverted to an older version, which is fine, mostly everything is okay except it looks like the openssl libraries are messed up somehow. Would it be possible to remove them all and put in the ones that you're now using in your AIX environment?
