### ISSUE TITLE
Passive checks not working RHEL7.4

### ISSUE THREAD

**Issue by sillihkram** [NagiosEnterprises/ncpa#436]
ncpa version information:
```
$ sudo yum info ncpa

Loaded plugins: enabled_repos_upload, package_upload, product-id, search-disabled-repos, subscription-manager
Repodata is over 2 weeks old. Install yum-cron? Or run: yum makecache fast
Installed Packages
Name        : ncpa
Arch        : x86_64
Version     : 2.1.1
Release     : 1.el7.centos
Size        : 20 M
Repo        : installed
From repo   : nagios-base
Summary     : A cross-platform active and passive monitoring agent
URL         : https://www.nagios.org/ncpa/help.php
License     : Nagios Open Software License Version 1.3
Description : The Nagios Cross-Platform Agent is used with Nagios XI and Nagios Core to run active
            : and/or passive checks on any operating system. Installs with zero requirements using a
            : bundled version of Python.

Uploading Enabled Repositories Report
Loaded plugins: product-id
```

configured passive checks: 

```
$ sudo cat /usr/local/ncpa/etc/ncpa.cfg.d/passive.cfg

[passive checks]

%HOSTNAME%|__HOST__ = system/agent_version
%HOSTNAME%|Disk Usage = disk/logical/|/used_percent --warning 80 --critical 90 --units Gi
%HOSTNAME%|CPU Usage = cpu/percent --warning 80 --critical 90 --aggregate avg
%HOSTNAME%|Swap Usage = memory/swap --warning 60 --critical 80 --units Gi
%HOSTNAME%|Memory Usage = memory/virtual --warning 80 --critical 90 --units Gi
%HOSTNAME%|Process Count = processes --warning 500 --critical 600
```

systemd service info  (replaced sensitive info w/ '****')
```
$ sudo systemctl restart ncpa_{listener,passive}
$ sudo systemctl status ncpa_{listener,passive} 

● ncpa_listener.service - LSB: This manages the NCPA Listener service
   Loaded: loaded (/etc/rc.d/init.d/ncpa_listener; bad; vendor preset: disabled)
   Active: active (running) since Wed 2018-02-28 13:30:42 CST; 7s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 224262 ExecStop=/etc/rc.d/init.d/ncpa_listener stop (code=exited, status=0/SUCCESS)
  Process: 224290 ExecStart=/etc/rc.d/init.d/ncpa_listener start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/ncpa_listener.service
           └─224307 /usr/local/ncpa/ncpa_listener --start

Feb 28 13:30:41 **** systemd[1]: Starting LSB: This manages the NCPA Listener service...
Feb 28 13:30:42 **** ncpa_listener[224290]: Starting NCPA Listener: [  OK  ]
Feb 28 13:30:42 **** systemd[1]: Started LSB: This manages the NCPA Listener service.

● ncpa_passive.service - LSB: This manages the NCPA Passive service
   Loaded: loaded (/etc/rc.d/init.d/ncpa_passive; bad; vendor preset: disabled)
   Active: active (running) since Wed 2018-02-28 13:30:42 CST; 7s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 224263 ExecStop=/etc/rc.d/init.d/ncpa_passive stop (code=exited, status=0/SUCCESS)
  Process: 224283 ExecStart=/etc/rc.d/init.d/ncpa_passive start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/ncpa_passive.service
           └─224305 /usr/local/ncpa/ncpa_passive --start

Feb 28 13:30:41 **** systemd[1]: Starting LSB: This manages the NCPA Passive service...
Feb 28 13:30:42 **** systemd[1]: Started LSB: This manages the NCPA Passive service.
Feb 28 13:30:42 **** ncpa_passive[224283]: Starting NCPA Passive:  [  OK  ]
```

ncpa_listener log file(replaced sensitive info w/ '****'):
```
$ sudo tail /usr/local/ncpa/var/log/ncpa_listener.log

2018-02-28 13:29:38,208 224143 INFO 10.0.0.20 - - [2018-02-28 13:29:38] "GET /api/disk/logical/%7C/used_percent/?token=****&warning=80&critical=95&check=1 HTTP/1.1" 200 242 0.006024
2018-02-28 13:30:41,721 224143 INFO stopped
2018-02-28 13:30:42,317 224307 INFO started
2018-02-28 13:30:42,328 224307 INFO Using SSL version TLSv1_2
2018-02-28 13:30:54,621 224307 INFO 10.171.24.155 - - [2018-02-28 13:30:54] "GET /api/cpu/percent/?token=****&warning=80&critical=90&check=1&aggregate=sum HTTP/1.1" 200 229 0.509899
2018-02-28 13:33:21,095 224307 INFO stopped
2018-02-28 13:33:35,396 224469 INFO started
2018-02-28 13:33:35,407 224469 INFO Using SSL version TLSv1_2
2018-02-28 13:33:58,403 224469 INFO 10.0.0.20 - - [2018-02-28 13:33:58] "GET /api/disk/logical/%7Cvar%7Clib%7Cpulp/used_percent/?token=****&warning=80&critical=95&check=1 HTTP/1.1" 200 242 0.008262
2018-02-28 13:34:02,437 224469 INFO 10.0.0.20 - - [2018-02-28 13:34:02] "GET /api/memory/virtual/?token=****&warning=90&critical=99&units=G&check=1 HTTP/1.1" 200 369 0.007226
```

ncpa_passive log file
```
$ sudo tail /usr/local/ncpa/var/log/ncpa_passive.log

  File "/usr/local/lib/python2.7/ConfigParser.py", line 642, in items
NoSectionError: No section: 'passive checks'
2018-02-28 13:35:24,541 224467 ERROR No section: 'passive checks'
Traceback (most recent call last):
  File "ncpa_passive.py", line 46, in run_all_handlers
  File "/root/ncpa/agent/passive/nrdp.py", line 112, in run
  File "/root/ncpa/agent/passive/nagioshandler.py", line 78, in run
  File "/root/ncpa/agent/passive/nagioshandler.py", line 35, in get_commands_from_config
  File "/usr/local/lib/python2.7/ConfigParser.py", line 642, in items
NoSectionError: No section: 'passive checks'
```

ncpa.cfg
```
$ sudo cat /usr/local/ncpa/etc/ncpa.cfg

#
#   NCPA Main Config File
#   ---------------------
#

#
# -------------------------------
# General Configuration
# -------------------------------
#

[general]

#
# Check logging is on by default, you can disable it if you do not want to record
# the check requests that are coming in or checks being sent over NRDP.
# Default: check_logging = 1
#
check_logging = 1

#
# Check logging time - how long in DAYS you'd like to keep checks in the database.
# Default: 30
#
check_logging_time = 30

#
# -------------------------------
# Listener Configuration (daemon)
# -------------------------------
#

[listener]

#
# User and group to run plugins as (recommended to use nagios:nagios)
# Default: uid = nagios
# Default: gid = nagios
#
# ** Note - The daemon runs as root, but forks a child process when running a plugin
#    that is defined by the user, for security reasons. However, without the main daemon
#    running as root, much of the system information would be missing. This is typical behavior. **
#
# This is for Unix only (Linux, Mac OS X, etc)
#
uid = nagios
gid = nagios

#
# IP address and port number for the Listener to use for the web GUI and API
# Default: ip = 0.0.0.0
# Default: port = 5693
#
ip = 0.0.0.0
port = 5693

#
# SSL connection and certificate config (if an SSL option is not available on some older
# operating systems it will default back to TLSv1)
# ssl_version options: TLSv1, TLSv1_1, TLSv1_2
#
ssl_version = TLSv1_2
certificate = adhoc

#
# Listener logging file level, location, and the PID location
# Default: loglevel = info (debug, info, warning, error)
# Default: logfile = var/log/ncpa_listener.log
# Default: pidfile = var/run/ncpa_listener.pid (leave listener in pid file name)
#
loglevel = info
logfile = var/log/ncpa_listener.log
pidfile = var/run/ncpa_listener.pid

#
# Delay the listener (API & web GUI) from starting in seconds
# Default: 0
#
# delay_start = 30

#
# Allow admin functionality in the web GUI. When this is set to 0, the admin section will not
# be displayed in the header and will not be available to be accessed.
# Default: 1
#
admin_gui_access = 1

#
# Admin password for the admin section in the web GUI, by default there is no admin
# password and the admin section of the GUI can be accessed by anyone if admin_gui_access is set to 1.
# Default: None
#
# Note: Setting this value to 'None' will automatically log you in, setting it empty will allow you to
# log in using a blank password.
#
admin_password = None

#
# Require admin password to access ALL of the web GUI.
# This does not affect API access via token (community_string).
# Default: 0
#
admin_auth_only = 0

#
# -------------------------------
# Listener Configuration (API)
# -------------------------------
#

[api]

#
# The token that will be used to log into the basic web GUI (API browser, graphs, top charts, etc)
# and to authenticate requests to the API and requests through check_ncpa.py
#
community_string = ****
#
# -------------------------------
# Passive Configuration (daemon)
# -------------------------------
#

[passive]

#
# Handlers are a comma separated list of what you would like the passive agent to run
# Default: None
# Options:
#   nrds, nrdp
#
# Example:
# handlers = nrds,nrdp
#
handlers = nrdp

#
# User and group to run passive checks as (Recommended to use nagios:nagios)
# Default: uid = nagios
# Default: gid = nagios
#
uid = nagios
gid = nagios

#
# Passive check interval - the amount in seconds to wait between each passive check by default,
# this can be overwritten by adding on a "|<duration>" in seconds to the passive check config
# Default: 300 (5 minutes)
#
sleep = 300

#
# Passive logging file level, location, and the PID location
# Default: loglevel = info (debug, info, warning, error)
# Default: logfile = var/log/ncpa_passive.log
# Default: pidfile = var/run/ncpa_passive.pid (leave passive in pid file name)
#
loglevel = info
logfile = var/log/ncpa_passive.log
pidfile = var/run/ncpa_passive.pid

#
# Delay passive checks from starting in seconds
# Default: 0
#
# delay_start = 30

#
# -------------------------------
# Passive Configuration (NRDP)
# -------------------------------
#

[nrdp]

#
# Connection settings to the NRDP server
# parent = NRDP server location (ex: http://<address>/nrdp)
# token = NRDP server token used to send NRDP results
#
parent = https://****/nrdp
token = ****

#
# The hostname that will replace %HOSTNAME% in the check definitions and will be
# sent to NRDP with the check name as the service description (service name)
#
hostname = ****

#
# -------------------------------
# Passive Configuration (NRDS)
# -------------------------------
#

[nrds]

#
# NRDS CONFIGURATION DOES NOT WORK YET. MORE TO COME IN VERSION 2.1.0.
#

#
# NRDS connection information
#
url = 
token = 
config_name = 
config_version = 
update_config = 1
update_plugins = 1

#
# -------------------------------
# Plugin Configuration
# -------------------------------
#

[plugin directives]

#
# Plugin path where all plugins will be ran from.
#
plugin_path = plugins/

#
# Plugin execution timeout in seconds. Different than the check_ncpa.py timeout, which is
# normally for network connection issues. Will return a CRITICAL value and error when the plugin
# reaches the defined max execution timeout and kills the process.
# Default: 60
#
# plugin_timeout = 60

#
# Extensions for plugins
# ----------------------
# The extension for the plugin denotes how NCPA will try to run the plugin. Use this
# for setting how you want to run the plugin in the command line.
#
# NOTE: Plugins without an extension will be ran in the cmdline as follows:
#       $plugin_name $plugin_args
#
# Defaults:
# .sh = /bin/sh $plugin_name $plugin_args
# .py = python $plugin_name $plugin_args
# .ps1 = powershell -ExecutionPolicy Bypass -File $plugin_name $plugin_args
# .vbs = cscript $plugin_name $plugin_args //NoLogo
# .bat = cmd /c $plugin_name $plugin_args
#
# Since windows NCPA is 32-bit, if you need to use 64-bit powershell, try the following for
# the powershell plugin definition:
# .ps1 = c:\windows\sysnative\windowspowershell\v1.0\powershell.exe -ExecutionPolicy Unrestricted -File $plugin_name $plugin_args
#

# Linux / Mac OS X
.sh = /bin/sh $plugin_name $plugin_args
.py = python $plugin_name $plugin_args

# Windows
.ps1 = powershell -ExecutionPolicy Bypass -File $plugin_name $plugin_args
.vbs = cscript $plugin_name $plugin_args //NoLogo
.wsf = cscript $plugin_name $plugin_args //NoLogo
.bat = cmd /c $plugin_name $plugin_args
```

What other information can I provide?

**Comment by jomann09** [comment]
Can you do a quick test by putting your `[passive checks]` section into your base `ncpa.cfg` at the very bottom and see if it will load them after you restart the passive daemon? I would assume that NCPA is not resolving the path properly for the `ncpa.cfg.d` directory for some reason, even though everything looks normal to me. The only other thing that stands out is the EOL for the `passive.cfg` file not being UNIX or something like that.

**Comment by sillihkram** [comment]
Well I think you're right...

added the "[passive checks]" section from /usr/local/ncpa/etc/ncpa.cfg.d/passive.cfg to /usr/local/ncpa/etc/ncpa.cfg  

Then restarted NCPA:
sudo systemctl restart ncpa_{listener,passive}


$ sudo tail /usr/local/ncpa/var/log/ncpa_passive.log
2018-02-28 14:07:15,886 226051 INFO started
2018-02-28 14:07:15,900 226051 INFO Running check: system/agent_version
2018-02-28 14:07:15,909 226051 INFO Did not receive normal values. Unable to find meaningful check.
2018-02-28 14:07:15,921 226051 INFO Running check: disk/logical/|/used_percent --warning 80 --critical 90 --units Gi
2018-02-28 14:07:15,930 226051 INFO Running check: cpu/percent --warning 80 --critical 90 --aggregate avg
2018-02-28 14:07:16,437 226051 INFO Running check: memory/swap --warning 60 --critical 80 --units Gi
2018-02-28 14:07:16,444 226051 INFO Running check: memory/virtual --warning 80 --critical 90 --units Gi
2018-02-28 14:07:16,451 226051 INFO Running check: processes --warning 500 --critical 600
2018-02-28 14:07:16,851 226051 INFO Message from NRDP server: OK
2018-02-28 14:07:16,852 226051 INFO Meta output from NRDP server: 6 checks processed.

what would cause the /usr/local/ncpa/etc/ncpa.cfg.d/ dir not to be read?

**Comment by jomann09** [comment]
By default it's always read when the daemon is loaded. Since it's not the `example.cfg` is it set to `nagios:nagios` ownership? If you made it as root, it can't read it unless the nagios user has read permissions.

**Comment by sillihkram** [comment]
I've not modified the ownership of that directory or the configs in it.

```
$ ll /usr/local/ncpa/etc/ncpa.cfg.d/

total 16
-rw-r--r--. 1 nagios nagios 510 Dec 21 10:12 example.cfg
-rw-------. 1 root   root   516 Feb  6 23:09 localhost.cfg
-rw-------. 1 root   root   448 Feb 28 13:27 passive.cfg
-rw-r--r--. 1 nagios nagios 100 Dec 21 10:12 README.txt
```

```
sudo chmod 644 /usr/local/ncpa/etc/ncpa.cfg.d/*
sudo chown nagios:nagios /usr/local/ncpa/etc/ncpa.cfg.d/*
```

```
ll /usr/local/ncpa/etc/ncpa.cfg.d/*
-rw-r--r--. 1 nagios nagios 510 Dec 21 10:12 /usr/local/ncpa/etc/ncpa.cfg.d/example.cfg
-rw-r--r--. 1 nagios nagios 516 Feb  6 23:09 /usr/local/ncpa/etc/ncpa.cfg.d/localhost.cfg
-rw-r--r--. 1 nagios nagios 448 Feb 28 13:27 /usr/local/ncpa/etc/ncpa.cfg.d/passive.cfg
-rw-r--r--. 1 nagios nagios 100 Dec 21 10:12 /usr/local/ncpa/etc/ncpa.cfg.d/README.txt
```

That looks better let me test..

Moved ```"[Passive checks]"``` section back to ```/usr/local/ncpa/etc/ncpa.cfg.d/passive.cfg``` after ownership and permissions change..

Restarted services:
```
$ sudo systemctl restart ncpa_{listener,passive}
```
Checked log:
```
$ sudo tail /usr/local/ncpa/var/log/ncpa_passive.log

2018-02-28 14:29:39,357 226850 INFO started
2018-02-28 14:29:39,370 226850 INFO Running check: system/agent_version
2018-02-28 14:29:39,378 226850 INFO Did not receive normal values. Unable to find meaningful check.
2018-02-28 14:29:39,381 226850 INFO Running check: disk/logical/|/used_percent --warning 80 --critical 90 --units Gi
2018-02-28 14:29:39,387 226850 INFO Running check: cpu/percent --warning 80 --critical 90 --aggregate avg
2018-02-28 14:29:39,894 226850 INFO Running check: memory/swap --warning 60 --critical 80 --units Gi
2018-02-28 14:29:39,901 226850 INFO Running check: memory/virtual --warning 80 --critical 90 --units Gi
2018-02-28 14:29:39,908 226850 INFO Running check: processes --warning 500 --critical 600
2018-02-28 14:29:40,029 226850 INFO Message from NRDP server: OK
2018-02-28 14:29:40,029 226850 INFO Meta output from NRDP server: 6 checks processed.
```

Looks like that was the issue. I will update my ncpa instances to chmod/chown files in that dir respectively.
