### ISSUE TITLE
Python custom plugins with NCPA

### ISSUE THREAD

**Issue by boneill81** [NagiosEnterprises/ncpa#478]
I was wondering if issue #68 ever addressed in the end? I'm on 2.1.5 and I can see from the change-log of 2.1.2 that an issue was addressed with python plug-ins not running correctly but it still does not seem to work for me. I wrote a small python dummy plug-in to test the functionality.

```PYTHON
import os, sys

OK = 0
WARNING  = 1
CRITICAL = 2
UNKNOWN  = 3

def main():

   print "OK: This is working"
   sys.exit(OK)

if __name__ == "__main__":
   main()
```
However this does not work. When run via check_ncpa.py on the command line from nagios core, it returns a 500 internal server error.

When executed via the api tester in the ncpa web server, it just stays at loading forever. Perhaps the functionality to execute custom python custom plugins via the bundled interpreter was never implemented, but I just wanted to check if this was the case since it would be amazingly useful if it were available.

Thanks.

**Comment by boneill81** [comment]
Hmm that is unusual. I wonder is it anything to do with Python being installed already on CentOS. I'm on windows and this client machine does not have Python installed, I am trying to get NCPA to use the bundled python version. Have you got Python installed on your machine as well as NCPA?

**Comment by box293** [comment]
Yeah on the CentOS machine it had Python 2.7.5 installed.

However I jumped to a Windows 10 box that already has Python 2.7.13 installed and when I try the plugin on I also get the same error message:

```
2018-07-31 11:12:32,816:ERROR:app:Exception on /api/plugins/test.py [GET]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
  File "C:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
  File "C:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
  File "C:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
  File "C:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
  File "C:\ncpa\agent\listener\server.py", line 169, in token_auth_decoration
  File "C:\ncpa\agent\listener\server.py", line 929, in api
  File "C:\ncpa\agent\listener\pluginnodes.py", line 53, in walk
  File "C:\ncpa\agent\listener\pluginnodes.py", line 107, in execute_plugin
  File "C:\Python27\lib\site-packages\gevent\subprocess.py", line 585, in __init__
  File "C:\Python27\lib\site-packages\gevent\subprocess.py", line 554, in __init__
  File "C:\Python27\lib\site-packages\gevent\subprocess.py", line 898, in _execute_child
WindowsError: [Error 2] The system cannot find the file specified
```

**Comment by boneill81** [comment]
Ah right, so Python was indeed installed on the CentOX machine and your error on the Windows machine was the same as mine, that is really helpful. I had seen an entry about adding .py to the config file also in #68 but there again it did not work for the built in interpreter. #288 seems to reference this issue also regarding the previously shipped frozen interpreter executable having been dropped from recent NCPA versions but I was hopeful that it had been reinstated when reading the 2.1.2 change-log. Perhaps we can get an update from @jomann09 on this to see if it will or already has been implemented in some manner. Installing Python on a client machine is no great burden of course, but if it were possible to execute Python plug-ins via the self contained interpreter it would be a real game changer I feel. @box293 Thanks a million for your help in debugging this issue, it is much appreciated.

**Comment by jomann09** [comment]
The python interpreter won't be available until NCPA 3. The other issue with using the bundled interpreter is that it won't give you nearly as much flexibility with plugins since it won't have all the extra modules that you can install using pip and whatnot, it's only packaged with what we need.

**Comment by boneill81** [comment]
OK thanks very much for the update. I expected as much also regarding the limitations of using the built in interpreter but for the basic sys/os stuff it would be super handy I guess. Thanks again for the help.

**Comment by jomann09** [comment]
Well it will definitely be available in NCPA 3 but just pointing out that if the plugin relies on any third-party modules it won't work ... however there may be ways to add modules also if you needed to, but that would require making your own build of NCPA.
