### ISSUE TITLE
windowscounters returning errors

### ISSUE THREAD

**Issue by acstryker** [NagiosEnterprises/ncpa#483]
NCPA (Windows Server 2016) agent_version is 2.1.5
NRDP (Ubuntu 16.04) tested on 1.5.1 and 1.5.2
The following passive checks work fine:
%HOSTNAME%|CPU Usage = /cpu/percent --warning 95 --critical 98 --aggregate avg
%HOSTNAME%|C Drive Space = /disk/logical/C:|/used_percent --warning 90 --critical 95 --units G

Any passive check with a windows counter appears to fail:
%HOSTNAME%|Page File Peak Usage = /windowscounters/Paging File(*)/% Usage Peak
%HOSTNAME%|SQL Allocated Memory = windowscounters/SQLServer:Memory Manager/Total Server Memory (KB)

The following is the .json
[User Connections.txt](https://github.com/NagiosEnterprises/ncpa/files/2278593/User.Connections.txt)

However, when the check runs I get the following in the ncpa_passive.log:
`2018-08-10 10:42:24,151:ERROR:app:Exception on /api/windowscounters/SQLServer:Memory/ [GET]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
  File "C:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
  File "C:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
  File "C:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
  File "C:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
  File "C:\ncpa\agent\listener\server.py", line 169, in token_auth_decoration
  File "C:\ncpa\agent\listener\server.py", line 927, in api
  File "C:\ncpa\agent\listener\windowscounters.py", line 39, in run_check
  File "C:\ncpa\agent\listener\windowscounters.py", line 83, in get_counter_path
IndexError: list index out of range
2018-08-10 10:42:24,154:ERROR:ncpacheck:Error with JSON: No JSON object could be decoded. JSON was: <!DOCTYPE html>
<html lang='en'>
    <head>
        <title>Page Not Found &middot; NCPA</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="NCPA Web Interface">
        <meta name="author" content="Nagios Enterprises, LLC">
        <link rel="shortcut icon" type="image/png" href="/static/img/ncpa.png" />
        <link rel="icon" type="image/png" href="/static/img/ncpa.png" />
        <link rel='stylesheet' href='/static/css/bootstrap.min.css'>
        <link rel='stylesheet' href='/static/css/font-awesome.min.css'>
        <link rel='stylesheet' href='/static/css/ncpa.css'>
        
        
        <script src='/static/js/jquery.2.2.4.min.js'></script>
        <script src='/static/js/bootstrap.min.js'></script>
        <script src='/static/js/d3.v4.min.js'></script>
        <script src='/static/js/main.js'></script>
        
        
    </head>
    <body style="padding-top: 50px;">
        
        <nav class="navbar navbar-inverse navbar-default navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-left">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/gui/">NCPA</a>
                </div>
                <div class="collapse navbar-collapse" id="navbar-collapse-left">
                    <ul class="nav navbar-nav">
                        
                    </ul>
                </div>
            </div>
        </nav>
        
        
        
        <div id="main-content-container">
            

<div style="text-align: center;">
    <h1 style="font-size: 12rem; padding: 8rem 0 3rem 0; color: #CCC;">500</h1>
    <p style="font-size: 1.8rem;">There was a internal server error. Please contact your system administrator.</p>
</div>

        </div>
    </body>
</html>
2018-08-10 10:42:24,154:ERROR:ncpa_windows:Stdout or returncode was None, cannot return meaningfully.
Traceback (most recent call last):
  File "C:\ncpa\agent\ncpa_windows.py", line 235, in run_all_handlers
  File "C:\ncpa\agent\passive\nrdp.py", line 115, in run
  File "C:\ncpa\agent\passive\nrdp.py", line 97, in get_xml_of_checkresults
  File "C:\ncpa\agent\passive\nrdp.py", line 56, in make_xml
  File "C:\ncpa\agent\passive\ncpacheck.py", line 84, in run
ValueError: Stdout or returncode was None, cannot return meaningfully.`

I am not sure what I am missing, any help is appreciated.

**Comment by jomann09** [comment]
You may need to URL encode certain parts of the URL. Essentially you should encode the actual counter after the `windowscounter/` portion so like this:

```
windowscounters/Paging%20File%28%2A%29%2F%25%20Usage%20Peak
```

**Comment by acstryker** [comment]
That worked, thanks for the help!
