### ISSUE TITLE
Missing dependency? Ubuntu 16.04.5 LTS (Xenial Xerus)

### ISSUE THREAD

**Issue by omnitec** [NagiosEnterprises/ncpa#500]
New install on this Ubuntu box, .. it seems like there is one or more Python dependency missing:

#/etc/init.d/ncpa_listener start
Started NCPA Listener
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/cx_Freeze/initscripts/Console.py", line 27, in <module>
  File "ncpa_listener.py", line 5, in <module>
  File "/root/ncpa/agent/ncpadaemon.py", line 14, in <module>
  File "/root/ncpa/agent/listener/database.py", line 5, in <module>
  File "/root/ncpa/agent/listener/server.py", line 11, in <module>
  File "/root/ncpa/agent/listener/psapi.py", line 250, in <module>
  File "/root/ncpa/agent/listener/psapi.py", line 221, in get_root_node
  File "/root/ncpa/agent/listener/psapi.py", line 157, in get_disk_node
  File "/usr/local/lib/python2.7/site-packages/psutil/__init__.py", line 2017, in disk_io_counters
  File "/usr/local/lib/python2.7/site-packages/psutil/_pslinux.py", line 1114, in disk_io_counters
NotImplementedError: /proc/diskstats nor /sys/block filesystem are available on this system

Nothing in the log files, ..

**Comment by jomann09** [comment]
What version of NCPA are you using? That looks like an issue with the way psutils is grabbing disk information... I can test it here too this afternoon.

**Comment by omnitec** [comment]
On Wed, 31 Oct 2018, Jake Omann wrote:

> What version of NCPA are you using? That looks like an issue with the way psutils is grabbing disk information... I can test it here too this afternoon.
>
Install from repo:

#aptitude show ncpa
Package: ncpa
New: yes
State: installed
Automatically installed: no
Version: 2.1.6-1
Priority: extra
Section: alien
Maintainer: root <root@localhost>
Architecture: amd64
Uncompressed Size: 34.9 M
Depends: libc6 (>= 2.14), libffi6 (>= 3.0.4), libsqlite3-0 (>= 3.5.9),
libssl1.0.0 (>= 1.0.1d), zlib1g (>= 1:1.2.0)
Conflicts: ncpa:i386

**Comment by jomann09** [comment]
You can have NCPA ignore disk types but if it is not able to read diskstats it is probably giving a Python error. Have you tried running the agent as root? Setting user/group to root in the ncpa.cfg? If it's a VPS and it doesn't allow access to /proc/diskstats even as root then it is likely we will need to do some catching of exceptions from psutil.

**Comment by jomann09** [comment]
I'm fairly certain this is fixed in NCPA 2.1.7 due to a fix in psutils and how it handles no disks.
