### ISSUE TITLE
ncpa_passive will not run on new OpenSuSE 15.1 installation

### ISSUE THREAD

**Issue by omnitec** [NagiosEnterprises/ncpa#556]
New machine, .. new 2.1.8 install, .. copied config from working machine and changed the hostname. Permissions match (nagios:nagios), .. there IS a [passive] section in ncpa.cfg, .. reinstalled twice just to verify. Same configuration is already running on other machines, so the config itself is OK.

How does one isolate the problem?

2019-08-07 17:00:51,738 8139 ERROR No section: u'passive'
Traceback (most recent call last):
  File "ncpa_passive.py", line 93, in <module>
  File "/root/ncpa/agent/ncpadaemon.py", line 80, in main
  File "/root/ncpa/agent/ncpadaemon.py", line 202, in start
  File "ncpa_passive.py", line 59, in run
  File "/root/ncpa/agent/ncpadaemon.py", line 131, in read_basic_config
  File "/root/ncpa/agent/ncpadaemon.py", line 372, in get_uid_gid
  File "/usr/local/lib/python2.7/ConfigParser.py", line 607, in get
NoSectionError: No section: u'passive'

**Comment by jomann09** [comment]
Unfortunately finding the error will be us relying on what ConfigParser wants to output. Can you show your config files (remove any sensitive data) so we can have a closer look. It looks like it's erroring out at the uid and gid sections of the passive config, do you have those values defined in there?

**Comment by omnitec** [comment]
That would only be a red herring, .. the exact same config runs fine on other systems, so the only way to test would be on this particular system. Did a fresh remove/install after removing the residual directory, worked this time.

Thanks!

**Comment by jomann09** [comment]
Very strange, thanks for the update though.
