### ISSUE TITLE
ncpa 2.1.9 on Ubuntu 18.04.3 LTS doesn't work

### ISSUE THREAD

**Issue by micoots** [NagiosEnterprises/ncpa#578]
Hi. I've been using 2.1.9 since its release, and it seems that recently when Ubuntu 18.0.4x LTS auto-applied the latest packages, I can no longer get ncpa passive working. It bombs out with:

From /usr/local/ncpa/var/log/ncpa_passive.log

OperationalError: attempt to write a readonly database
2019-09-23 04:36:33,007 15890 ERROR attempt to write a readonly database
Traceback (most recent call last):
  File "ncpa_passive.py", line 93, in <module>
  File "/root/ncpa/agent/ncpadaemon.py", line 80, in main
  File "/root/ncpa/agent/ncpadaemon.py", line 185, in start
  File "/root/ncpa/agent/ncpadaemon.py", line 66, in setup_user
  File "/root/ncpa/agent/listener/database.py", line 41, in setup
OperationalError: attempt to write a readonly database

From /usr/local/ncpa/var/log/ncpa_listener.log

2019-09-23 04:36:32,100 15840 ERROR failed to start due to an exception
Traceback (most recent call last):
  File "/root/ncpa/agent/ncpadaemon.py", line 185, in start
  File "/root/ncpa/agent/ncpadaemon.py", line 66, in setup_user
  File "/root/ncpa/agent/listener/database.py", line 41, in setup
OperationalError: attempt to write a readonly database

I've enabled "loglevel = debug" in ncpa.cfg but to no available, all I see is the above.

Has anyone else experienced this?

I'm thinking maybe the latest python version:

# which python
/usr/bin/python

# /usr/bin/python -V
Python 2.7.15+

?

**Comment by jomann09** [comment]
Can you verify the permissions of the /usr/local/ncpa/var folder? To resolve the issues, you can delete the /usr/local/ncpa/var/ncpa.db file (the sqlite database it uses) and it will re-built it when you restart the active or passive service, provided it has proper permissions.

**Comment by micoots** [comment]
# ll -d /usr/local/ncpa/var
drwxrwxr-x 4 root nagios 4096 Sep 20 15:17 /usr/local/ncpa/var/

and:

# ll /usr/local/ncpa/var/ncpa.db
-rw-rw-r-- 1 root root 0 Sep  3 19:48 /usr/local/ncpa/var/ncpa.db

I also removed the ncpa.db and restarted NCPA, and it seems to have worked fine.

Many thanks, great advice.

**Comment by jomann09** [comment]
Thanks for the update, I'll take a look and verify that it's installing with proper permissions also.
