### ISSUE TITLE
Error in plugin parameter argument with commas

### ISSUE THREAD

**Issue by foxpluto** [NagiosEnterprises/ncpa#602]
Dear developer, 

I need to call a plugin in this way from Nagios: 
```bash
/usr/lib/nagios/plugins/check_ncpa.py -H 10.0.20.200 -t 'xxxxxxx' -M 'plugins/check_load' -q 'args= -w 4,3,2 -c 6,5,4'
```
I have tested from web interface and it works but from Nagios I have this error:
```
[root@ces ~]# sudo -u centreon-engine /usr/lib/nagios/plugins/check_ncpa.py -H 10.0.20.200 -t 'xxxxxxx' -M 'plugins/check_load' -q 'args= -w 4,3,2 -c 6,5,4' -D
The stack trace:
Traceback (most recent call last):
  File "/usr/lib/nagios/plugins/check_ncpa.py", line 320, in main
    info_json = get_json(options)
  File "/usr/lib/nagios/plugins/check_ncpa.py", line 235, in get_json
    url = get_url_from_options(options)
  File "/usr/lib/nagios/plugins/check_ncpa.py", line 154, in get_url_from_options
    arguments = get_arguments_from_options(options)
  File "/usr/lib/nagios/plugins/check_ncpa.py", line 221, in get_arguments_from_options
    key, value = argument.split('=', 1)
ValueError: need more than 1 value to unpack
```

If I remove the comma values everything works fine.

How could I pass plugins parameters with commas? 

Regards,
S.

**Comment by box293** [comment]
I think you need `-a`:
```
 /usr/lib/nagios/plugins/check_ncpa.py -H 10.0.20.200 -t 'xxxxxxx' -M 'plugins/check_load' -a '-w 4,3,2 -c 6,5,4'
```

From the `check_ncpa.py` help:
```
  -a ARGUMENTS, --arguments=ARGUMENTS
                        Arguments for the plugin to be run. Not necessary
                        unless you're running a custom plugin. Given in the
                        same as you would call from the command line. Example:
                        -a '-w 10 -c 20 -f /usr/local'
```

**Comment by foxpluto** [comment]
Ohhhh my gosh!!! 

Sorry for the ticket I have misunderstood the documentation, you are right! 

Thanks for your help and time.
Ciao,
Stefano
