### ISSUE TITLE
check_ncpa.py: AttributeError: 'HTTPError' object has no attribute 'reason'

### ISSUE THREAD

**Issue by ccztux** [NagiosEnterprises/ncpa#603]
The plugin check_ncpa.py throws an AttributeError when using with python 2.6.x in case of a http error.

Python version:
```
[root@localhost check_ncpa]# env python --version
Python 2.6.6
```

Plugin version:
```
[root@localhost check_ncpa]# ./check_ncpa.py --version
check_ncpa.py, Version 1.2.0
```

Error (verbose mode):
```
[root@localhost check_ncpa]# ../../check_ncpa.py -H 192.168.1.10 -t my_token -M 'agent/plugin/check_cluster_service_ncpa/-H/192.168.1.17 192.168.1.1/-c/check_ntp_time/-a/-w 1 -c 30 -q/-n 1/' -T 58 -v
Connecting to: https://192.168.1.10:5693/api/agent/plugin/check_cluster_service_ncpa/-H/192.168.1.17%20192.168.1.1/-c/check_ntp_time/-a/-w%201%20-c%2030%20-q/-n%201//?token=my_token&check=1
An error occurred:
'HTTPError' object has no attribute 'reason'
```

Error (verbose and debug mode):
```
[root@localhost check_ncpa]# ../../check_ncpa.py -H 192.168.1.10 -t my_token -M 'agent/plugin/check_cluster_service_ncpa/-H/192.168.1.17 192.168.1.1/-c/check_ntp_time/-a/-w 1 -c 30 -q/-n 1/' -T 58 -v -D
Connecting to: https://192.168.1.10:5693/api/agent/plugin/check_cluster_service_ncpa/-H/192.168.1.17%20192.168.1.1/-c/check_ntp_time/-a/-w%201%20-c%2030%20-q/-n%201//?token=my_token&check=1
The stack trace:
Traceback (most recent call last):
  File "../../check_ncpa.py", line 320, in main
    info_json = get_json(options)
  File "../../check_ncpa.py", line 252, in get_json
    if e.reason:
AttributeError: 'HTTPError' object has no attribute 'reason'
```

**Comment by jomann09** [comment]
Merged in your pull request, this looks fine!
