### ISSUE TITLE
Install issues on macOS 10.15.3

### ISSUE THREAD

**Issue by ashp8i** [NagiosEnterprises/ncpa#609]
I'm having touble cleaning up a failed install on 10.15.3, once installed can not access WebGUI

Starting upgrade...
Stopping old NCPA services...% 

getting stuck somewhere

**Comment by jomann09** [comment]
Is there anything left in /usr/local/ncpa? and if so, is there a running ncpa_listener process? If there are running ncpa processes you should be able to kill them before you do the install?

**Comment by ashp8i** [comment]
it looks like the process never gets loaded as I never see the web GUI, do you have a manual set of instructions for Install and Clean Removal so I can work out where it gets stuck,

the installer shows various messages

jmladmin@Mac-Pro local % sudo zsh /Volumes/NCPA-2.2.0/install.sh
Starting install...
<main> attribute status: eDSRecordAlreadyExists
<dscl_cmd> DS Error: -14135 (eDSRecordAlreadyExists)
jmladmin@Mac-Pro local % sudo zsh /usr/local/ncpa/uninstall.sh
zsh: can't open input file: /usr/local/ncpa/uninstall.sh
jmladmin@Mac-Pro local % sudo zsh /usr/local/ncpa/uninstall.sh
zsh: can't open input file: /usr/local/ncpa/uninstall.sh
jmladmin@Mac-Pro local % sudo zsh /Volumes/NCPA-2.2.0/install.sh
Starting install...
Users and group set
Loading services...done
Setting permissions...chown: nagios: illegal group name
jmladmin@Mac-Pro local % sudo zsh /Volumes/NCPA-2.2.0/install.sh
Starting upgrade...
Stopping old NCPA services...%                                                  jmladmin@Mac-Pro local % sudo zsh /Volumes/NCPA-2.2.0/install.sh
Starting upgrade...
Stopping old NCPA services...%                                                  jmladmin@Mac-Pro local % sudo zsh /usr/local/ncpa/uninstall.sh  
Starting uninstall...
Stopping NCPA services...%                                                      jmladmin@Mac-Pro local % sudo zsh /usr/local/ncpa/uninstall.sh
Starting uninstall...

I end up cleaning using

rm -r /usr/local/ncpa
sudo dscl . -delete /Users/nagios
sudo dscl . -delete /groups/nagios

**Comment by ashp8i** [comment]
can anyone chime in how to re-install a failed install for ncpa macos

**Comment by epaulsen5** [comment]
I've tried removing everything, including the user and group, and then installing a new copy. Still doesn't work:
~$ sudo zsh /Volumes/NCPA-2.2.1/install.sh
Password:
Starting install...
Loading services...done
Setting permissions...chown: nagios: illegal group name

If I run it again:
~$ sudo zsh /Volumes/NCPA-2.2.1/install.sh
Starting upgrade...
Stopping old NCPA services...smlsadmin@mm3:~$ sudo zsh /Volumes/NCPA-2.2.1/install.sh
Starting upgrade...
Stopping old NCPA services...

And then it kicks me right out to command prompt. Any further suggestions on this? It seems like I'm running into Mac SIP.
---
Eric

**Comment by epaulsen5** [comment]
I can confirm that I'm running into an issue with SIP.

Boot into recovery, launch terminal, csrutil disable, and reboot.
NCPA launches and runs without an issue. 

Boot back into recovery mode and enable SIP, reboot, and I'm presented with a series of dialogs for the various parts of NCPA not being able to run due to security issues.

Is there a workaround for this?

**Comment by ashp8i** [comment]
still getting /usr/local/ncpa/ncpa_listener -n
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/cx_Freeze-4.3.4-py2.7-macosx-10.15-x86_64.egg/cx_Freeze/initscripts/Console.py", line 27, in <module>
  File "ncpa_listener.py", line 8, in <module>
  File "/Users/nagiosdev/repos/ncpa/agent/ncpadaemon.py", line 14, in <module>
  File "/Users/nagiosdev/repos/ncpa/agent/listener/database.py", line 3, in <module>
  File "/usr/local/Cellar/python@2/2.7.16_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/sqlite3/__init__.py", line 24, in <module>
  File "/usr/local/Cellar/python@2/2.7.16_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/sqlite3/dbapi2.py", line 28, in <module>
ImportError: dlopen(/usr/local/ncpa/_sqlite3.so, 2): Symbol not found: _sqlite3_enable_load_extension
  Referenced from: /usr/local/ncpa/_sqlite3.so
  Expected in: /usr/lib/libsqlite3.dylib
 in /usr/local/ncpa/_sqlite3.so

in ncpa-2.2.2 which as epaulsen5 has confirmed will not happed if SIP is disabled, also when ncpa-2.2.2 get installed macos complains it cannot verify the identity of developer

**Comment by loopway** [comment]
I've managed to get NCPA running on Big Sur with the following modifications:

```
# create links to dynlibs in /usr/local/lib
sudo mkdir /usr/local/lib
sudo find /usr/local/ncpa -name "*.dylib" -exec ln -s {} /usr/local/lib/ \;

# allow binaries and libraries to be executed within Gatekeeper (part of SIP)
sudo spctl --add --label "NCPA" /usr/local/ncpa/ncpa_listener
sudo spctl --add --label "NCPA" /usr/local/ncpa/ncpa_passive
sudo find /usr/local/ncpa -name "*.so" -exec spctl --add --label "NCPA" {} \;
sudo find /usr/local/ncpa -name "*.dylib" -exec spctl --add --label "NCPA" {} \;
sudo spctl --enable --label "NCPA"

# start with launchtl. first start has to be confirmed within finder, could not find a way around it...
sudo launchctl start com.nagios.ncpa.passive
sudo launchctl start com.nagios.ncpa.listener
```

Obviously it would be helpful if NCPA would be signed with an official Apple Developer Cert and the library path problems fixed. 😃

**Comment by ashp8i** [comment]
@loopway Many Thanks for looking into this would be a huge help for those who need to keep SIP on and actually use NCPA on macOS hopefully @jomann09 can look into incorporating your work in to the next release of NCPA.

**Comment by ashp8i** [comment]
Can't get my head around this one: -

jmladmin@Mac-Pro ~ % /usr/local/ncpa/ncpa_listener -n                     
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/cx_Freeze-4.3.4-py2.7-macosx-10.15-x86_64.egg/cx_Freeze/initscripts/Console.py", line 27, in <module>
  File "ncpa_listener.py", line 113, in <module>
  File "/Users/nagiosdev/repos/ncpa/agent/ncpadaemon.py", line 78, in main
  File "/Users/nagiosdev/repos/ncpa/agent/ncpadaemon.py", line 131, in read_basic_config
  File "/Users/nagiosdev/repos/ncpa/agent/ncpadaemon.py", line 378, in get_uid_gid
KeyError: 'getpwnam(): name not found: nagios'

**Comment by ashp8i** [comment]
looks like a half baked install, I cannot tell if the uninstall script works properly
