### ISSUE TITLE
NCPA 2.2.1 regex match service status bug in check mode

### ISSUE THREAD

**Issue by ludmilmm** [NagiosEnterprises/ncpa#620]
The issue was reported on the Nagios XI support forums here:

https://support.nagios.com/forum/viewtopic.php?t=57736#304981

I was able to recreate the problem on CentOS 6 64-bit, running NCPA 2.2.1. 

Here's what I see in the ncpa_listener.log:

`2020-03-04 09:30:59,862 9756 INFO ::ffff:192.168.0.10 - - [2020-03-04 09:30:59] "GET /api/services?service=^ssh$|^sshd$&match=regex HTTP/1.1" 200 388 0.930978
2020-03-04 09:31:04,364 9756 ERROR Exception on /api/services [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
  File "/root/ncpa/agent/listener/server.py", line 185, in token_auth_decoration
  File "/root/ncpa/agent/listener/server.py", line 946, in api
  File "/root/ncpa/agent/listener/services.py", line 365, in run_check
ValueError: 'sshd' is not in list
2020-03-04 09:31:04,366 9756 INFO ::ffff:192.168.0.10 - - [2020-03-04 09:31:04] "GET /api/services?service=^ssh$|^sshd$&match=regex&check=true HTTP/1.1" 500 3980 0.920716`

Let me know if you need any additional information. Thanks!

**Comment by Guyver1wales** [comment]
I will add to this, normal search match is also broken and services are now suddenly strictly case-sensitive between Server 2008 R2 and 2012+
I've got about 30 broken service checks since deploying 2.2.1 and they are all normal search or case-sensitivity issues that did not exist when running 2.2.0.

**Comment by yderi** [comment]
Looking forward to 2.2.3
