### ISSUE TITLE
NCPA-2.2.1-1.el7     OSError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by pilot513** [NagiosEnterprises/ncpa#632]
Hello.
I test agent behavior on oel8 (10.0.2.31) and oel7 (10.0.2.22)
On oel8 agent works fine. Queries are executed locally and remotely. On oel7, an error occurs that I can not figure out. Verification scripts are the same on both systems.

Look at:
`for i in 10.0.2.31 10.0.2.22; do ./check_ncpa.py -H $i -t mytoken  -P 5693 -M 'plugins/check_netsnmp_memory.pl' -a '-L "Memory Utilization" -A "*" -H 127.0.0.1 -C VerySecretPwd'; done`
**OEL8**
`Memory Utilization OK | %buffer_real=0.05 total=7358.9 min_swap=16.0 buffer=3.3 total_free=1865.1 avail_swap=1261.6 %used_swap=0.00 total_swap=1261.6 %cached_real=39.22 avail_real=603.6 %used_real=90.10 total_real=6097.3 used_swap=0.0 cached=2391.6 %avail_real=9.90 %user_real=50.82 %avail_swap=100.00 user=3098.8`
**OEL7**
`UNKNOWN: An error occured connecting to API. (HTTP error: '500 INTERNAL SERVER ERROR')`

**In log ncpa (debug):**
`2020-05-09 10:54:40,443 5446 ERROR Exception on /api/plugins/check_netsnmp_memory.pl/-L/"Memory Utilization"/-A/"*"/-H/127.0.0.1/-C/VerySecretPwd [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
  File "/root/ncpa/agent/listener/server.py", line 185, in token_auth_decoration
  File "/root/ncpa/agent/listener/server.py", line 946, in api
  File "/root/ncpa/agent/listener/nodes.py", line 300, in run_check
  File "/root/ncpa/agent/listener/pluginnodes.py", line 107, in execute_plugin
  File "/usr/local/lib/python2.7/site-packages/gevent/subprocess.py", line 585, in __init__
  File "/usr/local/lib/python2.7/site-packages/gevent/subprocess.py", line 554, in __init__
  File "/usr/local/lib/python2.7/site-packages/gevent/subprocess.py", line 1312, in _execute_child
OSError: [Errno 13] Permission denied
2020-05-09 10:54:40,445 5446 INFO ::ffff:10.0.2.22 - - [2020-05-09 10:54:40] "GET /api/plugins/check_netsnmp_memory.pl/-L/%22Memory%20Utilization%22/-A/%22%2A%22/-H/127.0.0.1/-C/VerySecretPwd?token=mytoken&check=1 HTTP/1.1" 500 2362 0.012432`

**Comment by pilot513** [comment]
The script itself on the OEL7 server works without errors:
`[root@oel7cli pilot]# /usr/lib64/nagios/plugins/check_netsnmp_memory.pl -L "Memory Utilization" -A "*" -H 127.0.0.1 -C VerySecretPwd
Memory Utilization OK | total_free=2187.7 %avail_real=10.34 %avail_swap=99.32 %buffer_real=0.00 user=253.4 %user_real=24.99 avail_swap=2082.8 %used_real=89.66 used_swap=14.3 total=3111 %cached_real=66.08 cached=670.0 total_swap=2097.1 buffer=0.0 min_swap=16.0 avail_real=104.8 total_real=1013.9 %used_swap=0.68`

**Comment by pilot513** [comment]
Sorry for panic.
I check attributes on check script in /usr/lib64/nagios/plugins/.
For some of them there was no “executable” attribute for group "other" .
