### ISSUE TITLE
allowed_hosts not supporting host names

### ISSUE THREAD

**Issue by dipurane** [NagiosEnterprises/ncpa#653]
Hi , I have modified ncpa.cfg file and added entry for the allowed host as follows

allowed_hosts = monitor1-public.abcd.com
If I use an IP address instead of a hostname everything works fine. But I want to use the hostname as the servers running Nagios may change and IP address may get updated to avoid changing Nagios config on each Nagios client host I want to use DNS name. If I add DNS name it shows following error

`Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1473, in full_dispatch_request
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1666, in preprocess_request
  File "/root/ncpa/agent/listener/server.py", line 116, in before_request
  File "/usr/local/lib/python2.7/site-packages/ipaddress.py", line 204, in ip_network
ValueError: u'monitor1-public.abcd.com' does not appear to be an IPv4 or IPv6 network
2020-07-14 02:25:31,526 26820 INFO 198.24.36.210 - - [2020-07-14 02:25:31] "GET /api/cpu/percent/?token=Mytoken&warning=90&critical=95&check=1&aggregate=avg HTTP/1.1" 500 2362 0.009757`

I tried updating to latest ncpa version and running latest version.
"https://nagios-host-to-monitor:5693/api/system/agent_version?token=myToken"
{
    "agent_version": "2.2.1"
}

OS Details :

Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial

**Comment by jomann09** [comment]
I'll add this as a feature request, as of right now it only works with IPs.

**Comment by ccztux** [comment]
I am working on this issue and will provide a pull request.
