### ISSUE TITLE
Getting error while running linuxacadamy-dl

### ISSUE THREAD

**Issue by sowmian** [NagiosEnterprises/ncpa#661]
C:\LinuxAcademy>linuxacademy-dl https://linuxacademy.com/cp/modules/view/id/97
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\linuxacademy-dl.exe\__main__.py", line 4, in <module>
  File "c:\python27\lib\site-packages\linuxacademy_dl\__main__.py", line 38, in <module>
    from linuxacademy_dl.cli import CLI
  File "c:\python27\lib\site-packages\linuxacademy_dl\cli.py", line 38, in <module>
    from .linux_academy import LinuxAcademy
  File "c:\python27\lib\site-packages\linuxacademy_dl\linux_academy.py", line 42, in <module>
    from .course import Course
  File "c:\python27\lib\site-packages\linuxacademy_dl\course.py", line 42, in <module>
    from .assets import Asset
  File "c:\python27\lib\site-packages\linuxacademy_dl\assets.py", line 38, in <module>
    from .downloader import DownloadEngine
  File "c:\python27\lib\site-packages\linuxacademy_dl\downloader.py", line 41, in <module>
    from .hls_decrypt import HLSDecryptAES128
  File "c:\python27\lib\site-packages\linuxacademy_dl\hls_decrypt.py", line 38, in <module>
    from Crypto.Cipher import AES
  File "c:\users\User~1\appdata\local\temp\easy_install-_mqzhk\pycrypto-2.6.1-py2.7-win-amd64.egg.tmp\Crypto\Cipher\AES.py", line 50, in <module>
  File "c:\users\User~1\appdata\local\temp\easy_install-_mqzhk\pycrypto-2.6.1-py2.7-win-amd64.egg.tmp\Crypto\Cipher\_AES.py", line 7, in <module>
  File "c:\users\User~1\appdata\local\temp\easy_install-_mqzhk\pycrypto-2.6.1-py2.7-win-amd64.egg.tmp\Crypto\Cipher\_AES.py", line 6, in __bootstrap__
ImportError: DLL load failed: %1 is not a valid Win32 application.

**Comment by ccztux** [comment]
Has this anything to do with NCPA?
