### ISSUE TITLE
PSUtils causing "UNKNOWN: An error occured connecting to API. (HTTP error: '500 INTERNAL SERVER ERROR')" for any API call.

### ISSUE THREAD

**Issue by tgriep** [NagiosEnterprises/ncpa#670]
When any API call is received by the NCPA Agent, the psutils tries to gather data from the following mounts.
/proc/diskstats and /sys/block filesystem

If those mounts are not available on the system, it will cause not only the drive checks to fail, but other checks to fail as well.
The plugin displays this error.
"UNKNOWN: An error occured connecting to API. (HTTP error: '500 INTERNAL SERVER ERROR')"
 
ncla_listener.log debugging shows this.

2020-08-11 08:06:46,689 6301 INFO ::ffff:82.166.70.94 - - [2020-08-11 08:06:46] "GET /api/cpu/percent?aggregate=avg&token=xxxxxxxxxxxxxx HTTP/1.0" 500 2381 0.001660
2020-08-11 08:06:47,299 6301 ERROR Exception on /api/user/count [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
  File "/root/ncpa/agent/listener/server.py", line 185, in token_auth_decoration
  File "/root/ncpa/agent/listener/server.py", line 931, in api
  File "/root/ncpa/agent/listener/psapi.py", line 279, in getter
  File "/root/ncpa/agent/listener/psapi.py", line 260, in refresh
  File "/root/ncpa/agent/listener/psapi.py", line 230, in get_root_node
  File "/root/ncpa/agent/listener/psapi.py", line 162, in get_disk_node
  File "/usr/local/lib/python2.7/site-packages/psutil/__init__.py", line 2061, in disk_io_counters
  File "/usr/local/lib/python2.7/site-packages/psutil/_pslinux.py", line 1121, in disk_io_counters
NotImplementedError: /proc/diskstats nor /sys/block filesystem are available on this system

**Comment by ccztux** [comment]
Can you provide which OS version and NCPA version are in use?

**Comment by tgriep** [comment]
Sorry, forgot to add that here.
Ubuntu 16 and 18.
The user tried both NCPA 2.2.1 and 2.2.2 and they both failed.

**Comment by dani-cobwebs** [comment]
Hey,

It's happening on both OS version when the mount points are not default. Also I tried clean installation without any pre-installations like Zabbix and etc., but it's not solved the problem

**Comment by ccztux** [comment]
Unfortunately i have no system for testing where these directories are missing. I can try to fix it and provide you a custom build, but i cant tell you when this will be.

**Comment by jomann09** [comment]
I'm going to update the psutils version and re-build a test version that you can try out. If that works I will have it set up for the next release. I think that should fix it. I'll do it sometime in the next day or two.

**Comment by ccztux** [comment]
I will provide a patch in my existing pull request #671 which prevents that an issue in a endpoint breaks the whole api. In this example all nodes, except the affected one (disk) will work.

Test scenario: Faked exception with ```raise``` in ```get_disk_node```.

Client output (without the patch):
It doesnt work, because the exception in the disk node will break the whole api.
```
[root@centos7_ncpa_build build]# ../client/check_ncpa.py -H 10.0.0.76 -M user/count  -t mytoken 
UNKNOWN: An error occured connecting to API. (HTTP error: '500 INTERNAL SERVER ERROR')
```

ncpa_listener.log (without the patch):
```
2020-09-01 20:35:49,426 5314 INFO started
2020-09-01 20:35:49,436 5314 INFO Using SSL version TLSv1_2
2020-09-01 20:35:49,440 5314 INFO Failed to start in dual stack mode: [Errno 97] Address family not supported by protocol
2020-09-01 20:35:49,440 5314 INFO Falling back to IPv4 only
2020-09-01 20:35:52,526 5314 ERROR Exception on /api/user/count/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/git-repos/ncpa/agent/listener/server.py", line 289, in token_auth_decoration
  File "/root/git-repos/ncpa/agent/listener/server.py", line 1035, in api
  File "/root/git-repos/ncpa/agent/listener/psapi.py", line 324, in getter
  File "/root/git-repos/ncpa/agent/listener/psapi.py", line 305, in refresh
  File "/root/git-repos/ncpa/agent/listener/psapi.py", line 283, in get_root_node
UnboundLocalError: local variable 'disk' referenced before assignment
2020-09-01 20:35:52,541 5314 INFO 10.0.0.78 - - [2020-09-01 20:35:52] "GET /api/user/count/?token=mytoken&check=1 HTTP/1.1" 500 2362 0.020027
```

Client output (with the patch):
It works:
```
[root@centos7_ncpa_build build]# ../client/check_ncpa.py -H 10.0.0.76 -M user/count  -t mytoken 
OK: Count was 1 users | 'count'=1;;;
```

ncpa_listener.log (with the patch):
The exception will be logged, but all other, not affected nodes work.
```
2020-09-01 20:37:39,161 5555 INFO started
2020-09-01 20:37:39,174 5555 INFO Using SSL version TLSv1_2
2020-09-01 20:37:39,178 5555 INFO Failed to start in dual stack mode: [Errno 97] Address family not supported by protocol
2020-09-01 20:37:39,179 5555 INFO Falling back to IPv4 only
2020-09-01 20:37:43,166 5555 ERROR psutil.Error NotImplementedError
Traceback (most recent call last):
  File "/root/git-repos/ncpa/agent/listener/psapi.py", line 242, in get_root_node
  File "/root/git-repos/ncpa/agent/listener/psapi.py", line 159, in get_disk_node
Error: psutil.Error NotImplementedError
2020-09-01 20:37:43,196 5555 INFO 10.0.0.78 - - [2020-09-01 20:37:43] "GET /api/user/count/?token=mytoken&check=1 HTTP/1.1" 200 296 0.033858
```

**Comment by dani-cobwebs** [comment]
Do you have any dates when the new version will be released?

**Comment by jomann09** [comment]
This is in 2.3.0 which should be out soon. With that changes that ccztux made, it will no longer cause the program to stop working it'll just skip that section if it cannot access that data.

**Comment by jomann09** [comment]
I'm closing this since I am starting testing and prepping the release.
