### ISSUE TITLE
Passive checks stop sending if there are multiple NRDP servers configured and both NRDP servers are not listening.

### ISSUE THREAD

**Issue by tgriep** [NagiosEnterprises/ncpa#715]
If NCPA is setup to send passive checks to 2 different servers and the Apache process will not receive the checks on both XI servers, NCPA will generate this error and it will stop sending the checks.

2020-11-24 14:25:40,067 54886 ERROR HTTPSConnectionPool(host='192.168.112.129', port=443): Max retries exceeded with url: /nrdp/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f09ffeade90>: Failed to establish a new connection: [Errno 111] Connection refused',))
Traceback (most recent call last):
  File "ncpa_passive.py", line 51, in run_all_handlers
  File "/root/ncpa/agent/passive/nrdp.py", line 124, in run
  File "/root/ncpa/agent/passive/nrdp.py", line 195, in submit_to_nagios
  File "/root/ncpa/agent/passive/utils.py", line 13, in send_request
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 119, in post
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 61, in request
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 530, in request
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 643, in send
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
ConnectionError: HTTPSConnectionPool(host='192.168.112.129', port=443): Max retries exceeded with url: /nrdp/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f09ffeade90>: Failed to establish a new connection: [Errno 111] Connection refused',))

If starting up apache/NRDP on one of the servers, the NCPA agent will not send the checks to the one server that is listening.

Starting both apache/NRDP processes on both XI servers, the passive checks started to be sent to both servers.

**Comment by ccztux** [comment]
With pull request #720 it works.
One example log cycle (2 NRDP servers, 1 server has an issue with check_results_dir):
```
2020-12-09 18:55:10,278 9811 INFO Message from NRDP server (https://10.0.0.85/nrdp/): BAD CHECK RESULTS DIR
2020-12-09 18:55:10,278 9811 INFO Meta output from NRDP server (https://10.0.0.85/nrdp/): Nonexistent
2020-12-09 18:55:10,320 9811 INFO Message from NRDP server (https://10.0.0.86/nrdp/): OK
2020-12-09 18:55:10,320 9811 INFO Meta output from NRDP server (https://10.0.0.86/nrdp/): 6 checks processed
2020-12-09 18:55:40,398 9811 INFO Running check: system/agent_version
2020-12-09 18:55:40,406 9811 INFO Did not receive normal values. Unable to find meaningful check.
2020-12-09 18:55:40,436 9811 INFO Running check: disk/logical/C:|/used_percent --warning 80 --critical 90 --units Gi
2020-12-09 18:55:40,460 9811 INFO Running check: cpu/percent --warning 60 --critical 80 --aggregate avg
2020-12-09 18:55:40,998 9811 INFO Running check: memory/swap --warning 60 --critical 80 --units Gi
2020-12-09 18:55:41,022 9811 INFO Running check: memory/virtual --warning 80 --critical 90 --units Gi
2020-12-09 18:55:41,052 9811 INFO Running check: processes --warning 300 --critical 400
2020-12-09 18:55:41,208 9811 WARNING XML returned did not contain a message, or was malformed.
2020-12-09 18:55:41,209 9811 INFO Message from NRDP server (https://10.0.0.85/nrdp/): BAD CHECK RESULTS DIR
2020-12-09 18:55:41,209 9811 INFO Meta output from NRDP server (https://10.0.0.85/nrdp/): Nonexistent
2020-12-09 18:55:41,239 9811 INFO Message from NRDP server (https://10.0.0.86/nrdp/): OK
2020-12-09 18:55:41,240 9811 INFO Meta output from NRDP server (https://10.0.0.86/nrdp/): 6 checks processed
```

One example log cycle (2 NRDP servers, 1 servers apache is down):
```
2020-12-09 18:57:43,191 10140 INFO Running check: system/agent_version
2020-12-09 18:57:43,197 10140 INFO Did not receive normal values. Unable to find meaningful check.
2020-12-09 18:57:43,219 10140 INFO Running check: disk/logical/C:|/used_percent --warning 80 --critical 90 --units Gi
2020-12-09 18:57:43,238 10140 INFO Running check: cpu/percent --warning 60 --critical 80 --aggregate avg
2020-12-09 18:57:43,769 10140 INFO Running check: memory/swap --warning 60 --critical 80 --units Gi
2020-12-09 18:57:43,800 10140 INFO Running check: memory/virtual --warning 80 --critical 90 --units Gi
2020-12-09 18:57:43,821 10140 INFO Running check: processes --warning 300 --critical 400
2020-12-09 18:57:43,954 10140 ERROR Connection Error: HTTPSConnectionPool(host='10.0.0.85', port=443): Max retries exceeded with url: /nrdp/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8784317e10>: Failed to establish a new connection: [Errno 111] Connection refused',))
2020-12-09 18:57:43,993 10140 INFO Message from NRDP server (https://10.0.0.86/nrdp/): OK
2020-12-09 18:57:43,994 10140 INFO Meta output from NRDP server (https://10.0.0.86/nrdp/): 6 checks processed
2020-12-09 18:58:13,208 10140 INFO Running check: system/agent_version
2020-12-09 18:58:13,217 10140 INFO Did not receive normal values. Unable to find meaningful check.
2020-12-09 18:58:13,255 10140 INFO Running check: disk/logical/C:|/used_percent --warning 80 --critical 90 --units Gi
2020-12-09 18:58:13,296 10140 INFO Running check: cpu/percent --warning 60 --critical 80 --aggregate avg
2020-12-09 18:58:13,830 10140 INFO Running check: memory/swap --warning 60 --critical 80 --units Gi
2020-12-09 18:58:13,861 10140 INFO Running check: memory/virtual --warning 80 --critical 90 --units Gi
2020-12-09 18:58:13,892 10140 INFO Running check: processes --warning 300 --critical 400
2020-12-09 18:58:14,001 10140 ERROR Connection Error: HTTPSConnectionPool(host='10.0.0.85', port=443): Max retries exceeded with url: /nrdp/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f87840a7790>: Failed to establish a new connection: [Errno 111] Connection refused',))
2020-12-09 18:58:14,031 10140 INFO Message from NRDP server (https://10.0.0.86/nrdp/): OK
2020-12-09 18:58:14,032 10140 INFO Meta output from NRDP server (https://10.0.0.86/nrdp/): 6 checks processed
```

**Comment by jomann09** [comment]
This seems to work fine, so closing this for 2.3 release.
