### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by tgriep** [NagiosEnterprises/ncpa#769]
When trying to monitor the /boot partition of a Linux system, this error is generated in the ncpa_listener.log file
2021-05-12 19:40:21,714 521180 ERROR float division by zero
Traceback (most recent call last):
  File "/root/ncpa/agent/listener/psapi.py", line 257, in get_root_node
  File "/root/ncpa/agent/listener/psapi.py", line 211, in get_disk_node
  File "/root/ncpa/agent/listener/psapi.py", line 64, in make_mountpoint_nodes
ZeroDivisionError: float division by zero

And the API disk check for that partition displays this error.
{ "error": { "node": "disk", "path": "/api/disk", "message": "The node requested does not exist.", "code": 100 } }

In the NCPA agent, this following line is what is generating the error.
https://github.com/NagiosEnterprises/ncpa/blob/master/agent/listener/psapi.py#L64

iu = st.f_files - st.f_ffree
this line should make iu = 0 or < 0 if the st.f_files is 0, and then this line should not run if that's the case:
if iu > 0:
    iup = math.ceil(100 * float(iu) / float(st.f_files))

but somehow it is running anyway and is causing the errors.

See this ticket.
https://support.nagios.com/tickets/scp/tickets.php?id=14242

**Comment by ccztux** [comment]
Can you provide details about the affected partition? For example the output of the following df commands:
```
[root@centos7-01 src]# df -ih /boot/
Filesystem     Inodes IUsed IFree IUse% Mounted on
/dev/sda1        512K   355  512K    1% /boot

[root@centos7-01 src]# df -ahHT /boot/
Filesystem     Type  Size  Used Avail Use% Mounted on
/dev/sda1      xfs   1.1G  322M  742M  31% /boot
```

**Comment by tgriep** [comment]
I asked the customer to run those commands. As soon as I get the data, I'll update it here.

**Comment by tgriep** [comment]
Here is the data.
df -ih /boot/
Filesystem Inodes IUsed IFree IUse% Mounted on
/dev/sda1 398K 349 398K 1% /boot

df -ahHT /boot/
Filesystem Type Size Used Avail Use% Mounted on
/dev/sda1 xfs 411M 273M 139M 67% /boot

**Comment by tgriep** [comment]
The customer has a partition that has the inodes full so that is the issue.
Filesystem   Inodes        IUsed           IFree      IUse%  Mounted on
nfs:/unix    262615775312  262506836208    108939104  100%   /data

They cannot exclude the file system types as they are checking other partitions of the same type.

**Comment by ccztux** [comment]
Thank you for providing these helpful infos. I will investigate further and get back to you.

**Comment by ccztux** [comment]
I have no idea, whats going wrong here.
How often does the exception occure?
Does any check on the ```disk``` node work, if the exception occures?

I can only tell you, that the fix in #775 definitely fixes the issue on my testserver. Which operating system and version is in use? Maybe i can provide you an unofficial build including the fix if you like?

**Comment by tgriep** [comment]
The operating they are running is the following.
Red Hat Enterprise Linux Server release 7.6 (Maipo)

The ERROR float division by zero error in the ncpa_listener.log file happens on every disk call in the system and the error for the /boot partition is constant.

But as far as I know, all of the disk checks are failing.

If you can provide an unofficial build, I can send that to the user and have them test it.

**Comment by ccztux** [comment]
RHEL 7 sounds great, because i work on such a system and can provide you the unofficial build. You can find the build [here](https://github.com/ccztux/ncpa/blob/testbuild-issue-769/build/ncpa-2.3.1-2.el7.x86_64.rpm)
I hope, that the testbuild fixes the issue. Please let us know, if it does or not.

**Comment by ccztux** [comment]
Please let me know, when you have downloaded the testbuild, because i want to remove it as soon as possible. Thank you.

**Comment by tgriep** [comment]
I do not have access to the users system to install the updated package but I will let them know that about the updated RPM.
I'll update the issue on the results of the new package.
