### ISSUE TITLE
Performing a service check using "match" fails

### ISSUE THREAD

**Issue by MrPippin66** [NagiosEnterprises/ncpa#771]
Platform = Red Hat Enterprise Linux Server release 7.9 (Maipo)
NCPA = ncpa-2.3.0-1.el7.x86_64

When trying to do a service query using a "match" block, I get an 500 internal error:

Example:

# /usr/local/nagios/libexec/check_ncpa.py -H [server]  -t [token] -M 'services' -q 'match=regex,service=sshd,status=running'
UNKNOWN: An error occured connecting to API. (HTTP error: '500 INTERNAL SERVER ERROR')

Debug log on agent shows:

2021-05-21 08:35:01,611 1714 ERROR Exception on /api/services/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
  File "/root/ncpa/agent/listener/server.py", line 292, in token_auth_decoration
  File "/root/ncpa/agent/listener/server.py", line 1099, in api
  File "/root/ncpa/agent/listener/services.py", line 365, in run_check
ValueError: 'sshd-keygen' is not in list
2021-05-21 08:35:01,612 1714 INFO 10.170.136.156 - - [2021-05-21 08:35:01] "GET /api/services/?token=<topken>&check=1&match=regex&service=sshd&status=running HTTP/1.1" 500 2362 0.046096

**Comment by MrPippin66** [comment]
Nothing has changed that I'm aware of, but this is now working for our servers.
