### ISSUE TITLE
ncap 2.3.1 count process internal error underscore in process name

### ISSUE THREAD

**Issue by KUTYLA-Serge** [NagiosEnterprises/ncpa#772]
Hi,
I install ncpa 2.3.1 on a windows serveur.
From my linux nagios server i try to count ncpa_listener.exe 
using the script 
check_ncpa.py, Version 1.2.0
whith argument
./check_ncpa.py -H MySrv -t StrongToken -P 9999 -M 'processes' -q 'name=ncpa_listener.exe' -c 1:1

i've got the error
UNKNOWN: An error occured connecting to API. (HTTP error: '500 INTERNAL SERVER ERROR')
The log of my window serveur is
2021-05-21 17:16:43,457:ERROR:app:Exception on /api/processes/ [GET]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
  File "C:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
  File "C:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
  File "C:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
  File "C:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
  File "C:\ncpa\agent\listener\server.py", line 292, in token_auth_decoration
  File "C:\ncpa\agent\listener\server.py", line 1099, in api
  File "C:\ncpa\agent\listener\processes.py", line 420, in run_check
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe8 in position 212: ordinal not in range(128)

it's like the char _ not in 128 range but in ascii table _ it is 95
Can you help me ?

**Comment by jomann09** [comment]
Unfortunately this is likely due to the utf8 issues that python seems to have with Windows, is your Windows server not running in English?

**Comment by KUTYLA-Serge** [comment]
Yes my windows server is not in english but in french.
We use nagios for 12 years now and initally on linux server i use nrpe and on windows server nclient++.
nsclient++ have no more new release (the last is in 2018) therefore i choose to change to ncpa on linux and windows.
i find a workaround with a powershell plugin.

**Comment by jeritiana** [comment]
@KUTYLA-Serge would you please share the workaround using a powershell plugin?

**Comment by KUTYLA-Serge** [comment]
I install icinga-powershell-plugins powershell module on windows server
then i add a personal powershell script in the folder plugin
C:\Program Files (x86)\Nagios\NCPA\plugins
for sample check_my_process_sample.ps1
which contain only 3 lines
Use-Icinga;
$retcode=Invoke-IcingaCheckProcessCount -Process my_process -Warning 2:2 -Critical 2:2
exit($retcode)
that all in my sample i need to check exactly 2 process running no more no less.
and it's work perfectly.
In the nagios config file use the command :
check_ncpa!-M 'plugins/check_my_process_sample.ps1'
an from nagios server  command line
/usr/local/nagios/libexec/check_ncpa.py -H MyHost -t MyTokenKey -P 123456 -M 'plugins/check_my_process_sample.ps1'
and the result should be :
[OK] Process Check: 1 Ok
| 'process_count_my_process_sample'=2;2:2;2:2
