### ISSUE TITLE
NCPA API not getting any service

### ISSUE THREAD

**Issue by veskoz** [NagiosEnterprises/ncpa#785]
As title says, im not getting any service from a client: 
`{
  "value": {
    "services": {}
  }
}`
ncpa version 1.8.1 on  Microsoft Windows Server 2003 Standard (32-bit) 
Other clients with the same os and ncpa version, are running smoothly even with previos os like windows XP.
ncpa.cfg
```
`[listener]
uid = nagios
certificate = adhoc
loglevel = debug
ip = 0.0.0.0
gid = nagcmd
logfile = var/ncpa_listener.log
port = 5693
pidfile = var/ncpa_listener.pid
ssl_version = TLSv1


[passive]
uid = nagios
handlers = nrds,nrdp
loglevel = debug
gid = nagcmd
sleep = 300
logfile = var/ncpa_passive.log
pidfile = var/ncpa_passive.pid

[nrdp]
token =
hostname =server2
parent =

[nrds]
URL =
CONFIG_VERSION =0
TOKEN =
CONFIG_NAME =
CONFIG_OS = None
PLUGIN_DIR=plugins/
UPDATE_CONFIG=1
UPDATE_PLUGINS=1

[api]
community_string =mySecretToken

[plugin directives]
plugin_path = plugins/
.sh = /bin/sh $plugin_name $plugin_args
.ps1 = powershell -ExecutionPolicy Bypass -File $plugin_name $plugin_args
.vbs = cscript $plugin_name $plugin_args //NoLogo

[passive checks]
%HOSTNAME%|cpu usage = /cpu/percent --warning 20 --critical 30
%HOSTNAME%|swap usage = /memory/swap/percent --warning 40 --critical 80
%HOSTNAME%|memory usage = /memory/virtual/percent --warning 60 --critical 80
`
```
ncpa_listener.log
`2021-06-23 11:55:15,403:DEBUG:handler:Validating WebSocket request
2021-06-23 11:55:15,434:INFO:handler:10.71.0.232 - - [2021-06-23 11:55:15] "GET /api/services/ HTTP/1.1" 200 233 0.032000`

ncpa_passive.log
`2021-06-23 11:57:07,841:DEBUG:__init__:JSON response handled found stdout='OK: percent was 29% | 'percent_0'=29%;60;80;', returncode=0
2021-06-23 11:57:07,841:DEBUG:__init__:XML to be submitted: <?xml version="1.0" ?><checkresults><checkresult type="service"><servicename>cpu usage</servicename><hostname>server2</hostname><state>0</state><output>OK: percent was 0%,0% | 'percent_0'=0%;20;30; 'percent_1'=0%;20;30;</output></checkresult><checkresult type="service"><servicename>swap usage</servicename><hostname>server2</hostname><state>0</state><output>OK: percent was 15% | 'percent_0'=15%;40;80;</output></checkresult><checkresult type="service"><servicename>memory usage</servicename><hostname>server2</hostname><state>0</state><output>OK: percent was 29% | 'percent_0'=29%;60;80;</output></checkresult></checkresults>
2021-06-23 11:57:07,841:ERROR:__init__:Invalid URL u'/': No schema supplied. Perhaps you meant http:///?
Traceback (most recent call last):
  File "C:\ncpa\agent\ncpa_windows.py", line 192, in run_all_handlers
  File "C:\Programmi\Nagios\NCPA\passive\nrdp.py", line 112, in run
    self.submit_to_nagios(checkresults)
  File "C:\Programmi\Nagios\NCPA\passive\nrdp.py", line 165, in submit_to_nagios
    ret_xml = utils.send_request(url=server, token=token, XMLDATA=checkresults, cmd='submitcheck')
  File "C:\Programmi\Nagios\NCPA\passive\utils.py", line 13, in send_request
    r = requests.post(url, data=kwargs, verify=False, allow_redirects=True)
  File "C:\Python27\lib\site-packages\requests\api.py", line 88, in post
  File "C:\Python27\lib\site-packages\requests\api.py", line 44, in request
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 349, in request
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 287, in prepare_request
  File "C:\Python27\lib\site-packages\requests\models.py", line 287, in prepare
  File "C:\Python27\lib\site-packages\requests\models.py", line 338, in prepare_url
MissingSchema: Invalid URL u'/': No schema supplied. Perhaps you meant http:///?`

**Comment by yderi** [comment]
Are there any requirements to run the NCPA agent version 1.8.1 on that machine?

**Comment by HunnyPuns** [comment]
Shouldn't be any special requirement. However, I don't think Server 2003 supports TLS1. There is documentation for enabling TLS support In XP and Server 2003. Maybe it was enabled for your XP machines? Try setting ssl_version to SSLv3 and see if it accepts that.
