### ISSUE TITLE
NCPA Windows UTF8

### ISSUE THREAD

**Issue by Marcel-IA** [NagiosEnterprises/ncpa#790]
I installed ncpa 2.3.1 on windows but I'm having language encoding error [UTF8]: 
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc7 in position 19: ordinal not in range(128);​​

​
-----------
​2021-07-15 09:23:37,145:ERROR:app:Exception on /ws/top [GET]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
  File "C:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
  File "C:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
  File "C:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
  File "C:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
  File "C:\ncpa\agent\listener\server.py", line 292, in token_auth_decoration
  File "C:\ncpa\agent\listener\server.py", line 859, in top_websocket
  File "C:\Python27\lib\json\__init__.py", line 251, in dumps
  File "C:\Python27\lib\json\encoder.py", line 207, in encode
  File "C:\Python27\lib\json\encoder.py", line 270, in iterencode
  File "C:\Python27\lib\json\encoder.py", line 233, in _encoder
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc7 in position 19: ordinal not in range(128)
2021-07-15 09:23:37,148:DEBUG:websocket:Closed WebSocket
----------
​
Thanks

**Comment by ccztux** [comment]
This is a known issue and should be fixed with version ```3.0.0```:
- #439 
- #608
- #770

**Comment by Marcel-IA** [comment]
Thanks!
