### ISSUE TITLE
Kernel  5.3.18-57 causes ncpa_passive 2.1.8-1 crash

### ISSUE THREAD

**Issue by omnitec** [NagiosEnterprises/ncpa#800]
Looks like a current kernel introduces incompatibility again with ncpa_passive, .. system just updated, 2.1.8-1 is current in repos. OpenSuSE 15.3, .. is there a known solution?

**Comment by omnitec** [comment]
Looks like 2.3.1 is current on nagios.com, .. however there seem to be more serious issues there.

Output when starting ncpa_passive:
$ sudo ./ncpa_passive 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/cx_Freeze/initscripts/Console.py", line 27, in <module>
  File "ncpa_passive.py", line 6, in <module>
  File "/root/ncpa/agent/ncpadaemon.py", line 14, in <module>
  File "/root/ncpa/agent/listener/database.py", line 5, in <module>
  File "/root/ncpa/agent/listener/server.py", line 11, in <module>
  File "/root/ncpa/agent/listener/psapi.py", line 255, in <module>
  File "/root/ncpa/agent/listener/psapi.py", line 226, in get_root_node
  File "/root/ncpa/agent/listener/psapi.py", line 162, in get_disk_node
  File "/usr/local/lib/python2.7/site-packages/psutil/__init__.py", line 2169, in disk_io_counters
  File "/usr/local/lib/python2.7/site-packages/psutil/_pslinux.py", line 1120, in disk_io_counters
  File "/usr/local/lib/python2.7/site-packages/psutil/_pslinux.py", line 1093, in read_procfs
ValueError: not sure how to interpret line '   8       0 sda 82239 363 20062176 630998 154581 56932 37921696 106882 0 203784 737993 0 0 0 0 11980 112\n'

**Comment by omnitec** [comment]
ncpa 2.3.1 from Nagios fixed the problem.
