### ISSUE TITLE
NCPA-1.7.2 CentOS 7 RPM does not install

### ISSUE THREAD

**Issue by snkgak** [NagiosEnterprises/ncpa#90]
It appears the cx_Freeze and gevent issue still exists for the CentOS 7 RPM available here:
http://assets.nagios.com/downloads/ncpa/download.php?type=rpm&arch=x86_64&os=el7
```
[root@build7 ~]# md5sum ncpa-1.7.2.el7.centos.x86_64.rpm 
01aeda9f762ddbad2447c32b1a72a194  ncpa-1.7.2.el7.centos.x86_64.rpm
[root@build7 ~]# rpm -ivh --nomd5 ncpa-1.7.2.el7.centos.x86_64.rpm
Preparing...                          ################################# [100%]
uid=1008(nagios) gid=1008(nagcmd) groups=1008(nagcmd)
Updating / installing...
   1:ncpa-1.7.2-1.el7.centos          ################################# [100%]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/cx_Freeze-4.3.2-py2.7-linux-x86_64.egg/cx_Freeze/initscripts/Console.py", line 27, in <module>
  File "ncpa_posix_listener.py", line 6, in <module>
  File "/root/Development/ncpa/agent/listener/server.py", line 15, in <module>
  File "/usr/local/lib/python2.7/site-packages/gevent/__init__.py", line 36, in <module>
  File "/usr/local/lib/python2.7/site-packages/gevent/hub.py", line 8, in <module>
ImportError: /usr/local/ncpa/greenlet.so: file too short
Started listener...
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/cx_Freeze-4.3.2-py2.7-linux-x86_64.egg/cx_Freeze/initscripts/Console.py", line 27, in <module>
  File "ncpa_posix_passive.py", line 7, in <module>
  File "/root/Development/ncpa/agent/passive/nrds.py", line 4, in <module>
  File "/root/Development/ncpa/agent/passive/nagioshandler.py", line 3, in <module>
  File "/root/Development/ncpa/agent/passive/ncpacheck.py", line 5, in <module>
  File "/root/Development/ncpa/agent/listener/server.py", line 15, in <module>
  File "/usr/local/lib/python2.7/site-packages/gevent/__init__.py", line 36, in <module>
  File "/usr/local/lib/python2.7/site-packages/gevent/hub.py", line 8, in <module>
ImportError: /usr/local/ncpa/greenlet.so: file too short
Started passive agent...
[root@build7 ~]# ps aux| grep ncpa
root      4798  0.0  0.0 112640   964 pts/0    S+   11:08   0:00 grep --color=auto ncpa
[root@build7 ~]# 
```
I tried installing it on two separate CentOS 7 installs, with latest *9.2* kernel. I've not yet tried building the RPM myself.

**Comment by scot0357** [comment]
I have tested working builds of the CentOS 7 and this will be fixed in 1.8, will mark this fixed in prep for clearing out the 1.8 issues.

**Comment by Petaris** [comment]
I am getting this on CentOS 7 as well.  Is there a fix for this?
Thanks!

**Comment by scot0357** [comment]
There will be 1.8.0, which will go into feature freeze and testing tomorrow.

**Comment by snkgak** [comment]
Hopefully there will be CentOS 6.6 builds as well - we've discovered that the CentOS 6 RPM does not work on CentOS 6.6, and building it (1.7.2) manually seems to fail.
