### ISSUE TITLE
NCPA 2.4.0 on Solaris 11.4: Exception on /api/memory/swap

### ISSUE THREAD

**Issue by topinet** [NagiosEnterprises/ncpa#917]
Checking for memory/swap returns "500 INTERNAL SERVER ERROR"

In /usr/local/ncpa/var/log/ncpa_listener.log:
```
2023-02-24 10:05:15,969 11388 ERROR Exception on /api/memory/swap/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
  File "/export/home/ijor/ncpa/agent/listener/server.py", line 292, in token_auth_decoration
  File "/export/home/ijor/ncpa/agent/listener/server.py", line 1099, in api
  File "/export/home/ijor/ncpa/agent/listener/nodes.py", line 99, in run_check
  File "/export/home/ijor/ncpa/agent/listener/nodes.py", line 284, in get_values
  File "/export/home/ijor/ncpa/agent/listener/psapi.py", line 158, in <lambda>
  File "/usr/local/lib/python2.7/site-packages/psutil/__init__.py", line 1982, in swap_memory
  File "/usr/local/lib/python2.7/site-packages/psutil/_pssunos.py", line 158, in swap_memory
ValueError: need more than 1 value to unpack
```

In /usr/local/ncpa/var/log/ncpa_passive.log:
```
2023-02-24 10:10:49,570 14290 INFO Running check: memory/swap --warning 60 --critical 80 --units B
2023-02-24 10:10:49,757 14290 ERROR Exception on /api/memory/swap/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
  File "/export/home/ijor/ncpa/agent/listener/server.py", line 292, in token_auth_decoration
  File "/export/home/ijor/ncpa/agent/listener/server.py", line 1099, in api
  File "/export/home/ijor/ncpa/agent/listener/nodes.py", line 99, in run_check
  File "/export/home/ijor/ncpa/agent/listener/nodes.py", line 284, in get_values
  File "/export/home/ijor/ncpa/agent/listener/psapi.py", line 158, in <lambda>
  File "/usr/local/lib/python2.7/site-packages/psutil/__init__.py", line 1982, in swap_memory
  File "/usr/local/lib/python2.7/site-packages/psutil/_pssunos.py", line 158, in swap_memory
ValueError: need more than 1 value to unpack
2023-02-24 10:10:49,818 14290 ERROR Error with JSON: No JSON object could be decoded. JSON was: <!DOCTYPE html>
<html lang='en'>
    <head>
        <title>Page Not Found &middot; NCPA</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="NCPA Web Interface">
[...]
```

**Comment by topinet** [comment]
I've upgraded to NCPA 2.4.1 and it seems to be solved
